// EVA → Hebrew character mapping
export const MAPPING = [
  { eva: 'a',    heb: 'אַ',    name: 'Alef / Patach' },
  { eva: 'b',    heb: 'בּ',    name: 'Bet' },
  { eva: 'c',    heb: 'כּ',    name: 'Kaf (stark)' },
  { eva: 'ch',   heb: 'כ/ח',  name: 'Kaf / Ḥet' },
  { eva: 'd',    heb: 'ד',    name: 'Dalet' },
  { eva: 'e',    heb: 'ֶ',    name: 'Vokal: Segol' },
  { eva: 'ee',   heb: 'ֵ',    name: 'Vokal: Ṣere' },
  { eva: 'f',    heb: 'פ/ף',  name: 'Pe (schwach)' },
  { eva: 'g',    heb: 'ג',    name: 'Gimel' },
  { eva: 'h',    heb: 'ה',    name: 'He' },
  { eva: 'i',    heb: 'י',    name: 'Yod / Ḥiriq' },
  { eva: 'ii',   heb: 'יִ',   name: 'Yod + Ḥiriq' },
  { eva: 'k',    heb: 'כ',    name: 'Kaf (weich)' },
  { eva: 'l',    heb: 'ל',    name: 'Lamed' },
  { eva: 'm',    heb: 'מ',    name: 'Mem' },
  { eva: 'n',    heb: 'נ',    name: 'Nun' },
  { eva: 'o',    heb: 'ע/ֹ',  name: 'Ayin / Ḥolam' },
  { eva: 'oo',   heb: 'וֹ',   name: 'Vav Ḥolam' },
  { eva: 'p',    heb: 'פּ',   name: 'Pe (stark)' },
  { eva: 'q',    heb: 'ק',    name: 'Qof' },
  { eva: 'r',    heb: 'ר',    name: 'Reš' },
  { eva: 's',    heb: 'שׂ/ס', name: 'Sin / Samech' },
  { eva: 'sh',   heb: 'שׁ',   name: 'Šin' },
  { eva: 't',    heb: 'ת/ט',  name: 'Tav / Ṭet' },
  { eva: 'y',    heb: 'יְ/וֹ', name: 'Yod-Vav / Verb-Präfix' },
  { eva: 'aiin', heb: 'עַיִן', name: 'Auge-Suffix' },
  { eva: 'ai',   heb: 'ַי',   name: 'Patach + Yod' },
];

// Morphological prefix table (sorted longest-first for greedy matching)
export const PREFIXES = [
  { eva: 'qok', heb: 'וְכְּ', de: 'und wie' },
  { eva: 'qod', heb: 'וְדְּ', de: 'und von' },
  { eva: 'qo',  heb: 'וְ',   de: 'und/auch' },
  { eva: 'o',   heb: 'עַ',   de: 'auf/bei' },
  { eva: 'l',   heb: 'לְ',   de: 'zu/für' },
  { eva: 'd',   heb: 'דְּ',  de: 'von/aus' },
  { eva: 'p',   heb: 'פְּ',  de: 'Pe-Präfix' },
  { eva: 'y',   heb: 'יְ',   de: 'Imperfekt 3.Sg.m.' },
  { eva: 't',   heb: 'תָּ',  de: 'Imperfekt 3.Sg.f./2.Sg.' },
];

// Confirmed lexicon v5.2 — 65 entries ★★★+
export const LEXICON = [
  // ── Medizinische Nomina & Symptome ──────────────────
  { eva: 'dam',       heb: 'דָּם',         de: 'Blut',                             stars: '★★★★★', cat: 'symptom' },
  { eva: 'dal',       heb: 'דַּל',         de: 'schwach / abgemagert',             stars: '★★★★',  cat: 'symptom' },
  { eva: 'ckhy',      heb: 'כְּהִי',       de: 'Blässe / Trübheit',                stars: '★★★★',  cat: 'symptom' },
  { eva: 'okaiin',    heb: 'עַכְּעַיִן',   de: 'auf das Auge',                     stars: '★★★★',  cat: 'symptom' },
  { eva: 'qokaiin',   heb: 'וְכְּעַיִן',   de: 'und gemäß dem Auge',               stars: '★★★★',  cat: 'symptom' },
  { eva: 'qotal',     heb: 'וְטַל',        de: 'Tau / Schweißzeichen',             stars: '★★★',   cat: 'symptom' },
  { eva: 'ram',       heb: 'רָם',          de: 'erhöht / Fieber',                  stars: '★★★',   cat: 'symptom' },
  { eva: 'chor',      heb: 'חֹר',          de: 'Pupille / Höhle',                  stars: '★★★★',  cat: 'symptom' },
  { eva: 'dain',      heb: 'דַּעַיִן',     de: 'das Auge (Kurzform)',              stars: '★★★',   cat: 'symptom' },
  { eva: 'sheoldam',  heb: 'שְׁאוֹל+דָּם', de: 'tödlicher Blutverlust',            stars: '★★★★★', cat: 'symptom' },
  { eva: 'damo',      heb: 'דָּמוֹ',       de: 'sein Blut (Possessiv)',            stars: '★★★★',  cat: 'symptom' },
  { eva: 'cham',      heb: 'חַם',          de: 'Wärme / Entzündung',               stars: '★★★',   cat: 'symptom' },
  { eva: 'dalor',     heb: 'דַּלאוֹר',     de: 'schwaches Augenlicht',             stars: '★★★',   cat: 'symptom' },
  { eva: 'shty',      heb: 'שְׁתִי',       de: 'Getränk / Trank',                  stars: '★★★',   cat: 'symptom' },
  { eva: 'pol',       heb: 'פֹּל',         de: 'Bohne / Beere',                    stars: '★★★',   cat: 'symptom' },
  { eva: 'otoaiin',   heb: 'עַתוֹעַיִן',   de: 'auf seine Augen',                  stars: '★★★',   cat: 'symptom' },
  { eva: 'char',      heb: 'חַר',          de: 'heiß / Fieber',                    stars: '★★★★',  cat: 'symptom' },
  { eva: 'dol',       heb: 'דָּוֶה',       de: 'Schmerz / Krankheit',              stars: '★★★',   cat: 'symptom' },
  { eva: 'shees',     heb: 'אֵשׁ',         de: 'Feuer / Fieberbrand',              stars: '★★★',   cat: 'symptom' },
  // ── Prognose-Termini ────────────────────────────────
  { eva: 'or',        heb: 'אוֹר',         de: 'Licht / Heilung',                  stars: '★★★',   cat: 'prognose' },
  { eva: 'sheol',     heb: 'שְׁאוֹל',      de: 'Scheol / Tod',                     stars: '★★★★',  cat: 'prognose' },
  { eva: 'shol',      heb: 'שׁוֹל',        de: 'Tod (apokor. Spr. A)',              stars: '★★★★★', cat: 'prognose' },
  { eva: 'daiin',     heb: 'דִּין',        de: 'Urteil / Prognose',                stars: '★★★★',  cat: 'prognose' },
  { eva: 'chalal',    heb: 'חָלָל',        de: 'Sterbender',                       stars: '★★★★',  cat: 'prognose' },
  { eva: 'aiin',      heb: 'אַיִן',        de: 'nichts / nicht vorhanden',         stars: '★★★',   cat: 'prognose' },
  { eva: 'eeor',      heb: 'אֵאוֹר',       de: 'kein Licht',                       stars: '★★★',   cat: 'prognose' },
  { eva: 'lor',       heb: 'לְאוֹר',       de: 'zum Licht / zur Heilung',          stars: '★★★★★', cat: 'prognose' },
  { eva: 'lshol',     heb: 'לְשׁוֹל',      de: 'zum Tod / zu Scheol',              stars: '★★★★★', cat: 'prognose' },
  { eva: 'chaiin',    heb: 'חַיִּין',      de: 'Leben (Chayyim)',                  stars: '★★★★',  cat: 'prognose' },
  { eva: 'sheey',     heb: 'שֵׁי',         de: 'Gabe / Wohlbefinden',              stars: '★★★★',  cat: 'prognose' },
  { eva: 'cheor',     heb: 'כְּאוֹר',      de: 'wie Licht (Heilungszeichen)',      stars: '★★★★',  cat: 'prognose' },
  { eva: 'otshol',    heb: 'אוֹתשׁוֹל',    de: 'das Zeichen des Todes',            stars: '★★★★★', cat: 'prognose' },
  { eva: 'chan',      heb: 'חָן',          de: 'Gnade / günstige Prognose',        stars: '★★★★',  cat: 'prognose' },
  { eva: 'dom',       heb: 'דּוֹם',        de: 'Stille / Ende',                    stars: '★★★★',  cat: 'prognose' },
  { eva: 'kaiim',     heb: 'קַיָּם',       de: 'gültig / beständig (Schlussformel)', stars: '★★★★★', cat: 'prognose' },
  // ── Syntaktische Konnektoren ────────────────────────
  { eva: 'chedy',     heb: 'כְּדֵי',       de: 'damit / um zu',                    stars: '★★★★',  cat: 'syntax' },
  { eva: 'kedy',      heb: 'כְּדֵי',       de: 'damit / um zu',                    stars: '★★★★',  cat: 'syntax' },
  { eva: 'shedy',     heb: 'שֶׁדִּי',      de: 'das/welches von',                  stars: '★★★★',  cat: 'syntax' },
  { eva: 'shdy',      heb: 'שֶׁדִּי',      de: 'das/welches von (Kurz)',           stars: '★★★★',  cat: 'syntax' },
  { eva: 'dy',        heb: 'דִּי',         de: 'von / dessen (Aram.)',             stars: '★★★★',  cat: 'syntax' },
  { eva: 'lchedy',    heb: 'לְכְּדֵי',     de: 'um zu / bis zur Grenze',           stars: '★★★★',  cat: 'syntax' },
  { eva: 'chal',      heb: 'חָל',          de: 'gilt für / betrifft',              stars: '★★★',   cat: 'syntax' },
  { eva: 'shodaiin',  heb: 'שׁוֹדִּין',    de: 'Todesurteil',                      stars: '★★★★',  cat: 'syntax' },
  { eva: 'sheodaiin', heb: 'שְׁאוֹדִּין',  de: 'Todesurteil (Vollform)',           stars: '★★★★★', cat: 'syntax' },
  { eva: 'daiidy',    heb: 'דִּין+דִּי',   de: 'das Urteil dessen',                stars: '★★★★★', cat: 'syntax' },
  { eva: 'daiindy',   heb: 'דִּין+דִּי',   de: 'das Urteil dessen',                stars: '★★★★★', cat: 'syntax' },
  { eva: 'qodaiin',   heb: 'וְדִּין',      de: 'und Urteil',                       stars: '★★★★',  cat: 'syntax' },
  { eva: 'daiim',     heb: 'דִּין+ם',      de: 'Urteile (Plural)',                 stars: '★★★',   cat: 'syntax' },
  { eva: 'keey',      heb: 'כֵּי',         de: 'denn / weil (Kausalpartikel)',     stars: '★★★★',  cat: 'syntax' },
  { eva: 'cthom',     heb: 'כְּתֹם',       de: 'wie Vollständigkeit',              stars: '★★★',   cat: 'syntax' },
  // ── Verbformen ──────────────────────────────────────
  { eva: 'taiir',     heb: 'תָּאִיר',      de: 'es wird leuchten / heilen',        stars: '★★★★',  cat: 'verb' },
  { eva: 'yteechy',   heb: 'יִחְיֶה',      de: 'er wird gesund',                   stars: '★★★',   cat: 'verb' },
  { eva: 'yshdal',    heb: 'יְשַׁדַּל',    de: 'er wird schwächen',                stars: '★★★',   cat: 'verb' },
  { eva: 'ykeedy',    heb: 'יְכֵּדֵי',     de: 'er wird anordnen',                 stars: '★★★',   cat: 'verb' },
  { eva: 'ykchy',     heb: 'יְכְּהִי',     de: 'er wird blass',                    stars: '★★★',   cat: 'verb' },
  { eva: 'tsheoarom', heb: 'תְּשְׁאוֹרוֹם', de: 'du wirst von Scheol aufsteigen',  stars: '★★★★',  cat: 'verb' },
  { eva: 'chkar',     heb: 'חֲקַר',        de: 'er untersucht',                    stars: '★★★',   cat: 'verb' },
  { eva: 'ydaiin',    heb: 'יְדִּין',      de: 'er urteilt',                       stars: '★★★★',  cat: 'verb' },
  { eva: 'ysho',      heb: 'יְשׁוֹ',       de: 'es führt zum Tod',                 stars: '★★★★',  cat: 'verb' },
  { eva: 'ykeor',     heb: 'יְכְּאוֹר',    de: 'er heilt / wie Licht',             stars: '★★★★',  cat: 'verb' },
  { eva: 'ykoiin',    heb: 'יְכוֹיִן',     de: 'er wird sich erholen',             stars: '★★★',   cat: 'verb' },
  // ── Akteure, Anatomie & Botanik ─────────────────────
  { eva: 'sar',       heb: 'שַׂר',         de: 'Arzt / Meister / Vorsteher',       stars: '★★★★',  cat: 'akteur' },
  { eva: 'al',        heb: 'עַל',          de: 'auf / über / betreffend',          stars: '★★★★',  cat: 'akteur' },
  { eva: 'ol',        heb: 'עַל',          de: 'auf / über / betreffend',          stars: '★★★★',  cat: 'akteur' },
  { eva: 'saiin',     heb: 'שַׂעַיִן',     de: 'Augenarzt',                        stars: '★★★',   cat: 'akteur' },
  { eva: 'sam',       heb: 'שַׂם',         de: 'Arznei / er gibt',                 stars: '★★★',   cat: 'akteur' },
  { eva: 'chokeos',   heb: 'כֹּכֵּאוֹס',   de: 'wie ein Kelch (Botanik)',          stars: '★★★',   cat: 'akteur' },
];
