export const COMPARISON = [
  { feature: 'Kernvokabular', langB: 'sheol, daiin, dal, ckhy, dam, sar, or', langA: 'Identisch — alle 10 Ankerwörter je Folio bestätigt (f1r: 10/10 ★★★★★)' },
  { feature: 'qo-Präfix (R1/R33)', langB: '8+ Belege; Kernmerkmal Spr. B ★★★★★', langA: 'Absent in Quires I–II (0 / ~800 Token); ab Quire III präsent: 13 Belege f17r/f17v (~5%) + 8–10 in f18r/f18v (~4–5%) + ~18 in f19r/f19v (~10% = Quire-H-äquivalent, R33-Erweiterung); R37: qo-Präfix-Dopplung ab f18v; R49: y+t-Verb-Litanei f19v P.12' },
  { feature: 'Dominanter Vokal', langB: 'e / ee (Segol/Ṣere)', langA: 'o (Ḥolam) häufiger; dol statt dal, ckho neben ckhy' },
  { feature: 'Struktur', langB: 'Prosa ohne Bildtrennmarker', langA: '{plant}-Marker in Kräuter-Folios (R14); f1r: Prosa ohne Marker (Haskama-Typ, sui generis)' },
  { feature: 'Kolophon-Inventar', langB: 'cphedom=, daiin·cheeodam', langA: 'kaiim=, dom=, daiin=, chckhan=, Kurztitel (R23)' },
  { feature: 'Verbparadigma', langB: 'taiir, yshdal', langA: 'ykchaiin, ycheor, ychor, ytchody — vollständiger' },
  { feature: 'Quire-Grenze', langB: 'Quire A → B (f8v → f9r):', langA: 'textlich unsichtbar — identische Ankerverteilung' },
];

export const FOLIOS = [
  { folio: 'f1r', plant: 'Kein Botanical — Haskama (deklarativer Prosatext)', signal: 'qo-: 0 Belege; 10/10 Ankerwörter; 4 Absätze + T1–T4; &252/&253 Aries-Großinitialen; Erased Key (Jim Reeds 1994)', stars: '★★★★', is5: false },
  { folio: 'f1v', plant: 'Belladonna', signal: 'shol 5×, pol (Beere), otoaiin (Pupille)', stars: '★★★★★', is5: true },
  { folio: 'f2r', plant: 'Kornblume (Augenwasser)', signal: 'ytoain=, saiin, aiin 8+ Komposita', stars: '★★★★★', is5: true },
  { folio: 'f2v', plant: 'Seerose', signal: 'shty (Trank), chokeos (Kelch)', stars: '★★★★', is5: false },
  { folio: 'f3r', plant: 'Blutpflanze (Polygonum)', signal: 'dam 4×, damo 2×, sheoldam — höchste Blutdichte', stars: '★★★★★', is5: true },
  { folio: 'f4r/v', plant: 'Geranium-Typ', signal: 'shol·chaiin (abwägend)', stars: '★★★★', is5: false },
  { folio: 'f5r', plant: 'Mandragora', signal: 'shodaiin 4× pro Satz (narkotisch-toxisch)', stars: '★★★★', is5: false },
  { folio: 'f6r', plant: 'Schlafmohn', signal: 'alle drei shol-Formen; kaiim=', stars: '★★★★', is5: false },
  { folio: 'f6v', plant: 'Blaue Distel', signal: 'sar-Öffner; dom=; lor (Heilungsrichtung)', stars: '★★★★', is5: false },
  { folio: 'f7r', plant: 'Seerose (Nymphaea)', signal: 'sheey 3× (positiv)', stars: '★★★★', is5: false },
  { folio: 'f7v', plant: 'Lungenkraut', signal: 'otshol · sheodaiin · lshol — dichteste Todesformeln', stars: '★★★★★', is5: true },
  { folio: 'f8r', plant: 'Aronstab (Arum)', signal: 'chor 6×, shol 5×; shol·kaiin×4 + kaiim=', stars: '★★★★', is5: false },
  { folio: 'f8v', plant: 'Röhrenblüter / Lungenkraut', signal: 'saiin; chol·chol·chol; daiin= (Quire-Ende)', stars: '★★★★', is5: false },
  { folio: 'f9r', plant: 'Sauerampfer (Rumex)', signal: 'or·chaiin (positiv); dsholdy; chkar=', stars: '★★★★', is5: false },
  { folio: 'f9v', plant: 'Viola tricolor', signal: 'chkaiin·ckhy·chor= (Diagnosekolophon); daiin 7×', stars: '★★★★★', is5: true },
  { folio: 'f10r', plant: 'Wegwarte (Cichorium)', signal: 'Prognose-Tetrade chaiin·ckhy·or·aiin; chor 7×', stars: '★★★★', is5: false },
  { folio: 'f10v', plant: 'Convolvulus / Glockenblume', signal: 'daiin 8× (Rekord); shoiin×2; dsho=; chckhan=', stars: '★★★★', is5: false },
  { folio: 'f11r', plant: 'Lungenkraut-Typ II', signal: 'ykchor·dair·ycheor (Pupillenheilung-Tripel); positiver Kolophon', stars: '★★★★', is5: false },
  { folio: 'f11v', plant: 'Kräuter-Komplex', signal: 'chkaiin·ckhy·chor= (Diagnosekolophon, 2. Beleg); odl·chaiin', stars: '★★★★', is5: false },
  { folio: 'f13r', plant: 'Großer Alant (Inula helenium)', signal: 'torshor (NEU); pchy 4× — Atemweg-Rekord; shol×2; Doppelkolophon', stars: '★★★', is5: false },
  { folio: 'f13v', plant: 'Schachtelhalm-Typ (Equisetum)', signal: '9 × {plant}-Marker (Rekord Quire B); qoky·daiin= (Minikolophon)', stars: '★★★', is5: false },
  { folio: 'f14r', plant: 'Schlangenwurz-Typ (Bistorta officinalis)', signal: 'dain + chor dominant; chckhy= (3. Korpus-Beleg); Doppelkolophon P.7 + P.13; ykaiin (5. y+k-Verb)', stars: '★★★', is5: false },
  { folio: 'f14v', plant: 'Farn-Typ (Dryopteris-Gruppe)', signal: 'dam (Blut-Triade P.8, Erstbeleg Quire B); dchckhy= (Intensiv-Siegel); Dreisegment-Kolophon; dy×3 (R25)', stars: '★★★', is5: false },
  { folio: 'f15r', plant: 'Silberdistel (Carlina acaulis)', signal: 'qotchor ★★★★★ (Pupillen-Zeichen, Kolophon); ykshol P.12 (erster negativer y+k+Terminus); sheey·cthy·dain (Gabe+Heilung+Auge); chaiin+Abwägungskolophon', stars: '★★★★', is5: false },
  { folio: 'f15v', plant: 'Einbeere (Paris quadrifolia)', signal: 'soloiin P.11 (Arznei für Auge) ★★★★★; sor P.10 (Heilungsarznei); opchor P.1 (Atemweg-Pupillen-Befund); cthor·chor= (vollständige Heilung, Kolophon)', stars: '★★★★', is5: false },
  { folio: 'f16r', plant: 'Wunderbaum (Ricinus communis)', signal: 'tchor P2.5 (fem. Pupillen-Verb, 1. Beleg); saiin·ytaiin= (Intra-Paragraph-Kolophon); qokchor·dl·dy·shey= (Schlusskolophon)', stars: '★★★★', is5: false },
  { folio: 'f16v', plant: 'Alpen-Mannstreu (Eryngium alpinum)', signal: 'chkar·chkar (Doppel-Untersuchungsformel, einmalig); okaiin×2; otor P.12 (Zeichen des Lichts); sokar·oaorar= (Quire-B-Abschlusskolophon)', stars: '★★★★★', is5: true },
  { folio: 'f17r', plant: 'Skabiosen-Flockenblume (Centaurea scabiosa)', signal: '3 =-Kolophone P.3+P.6+P.12 (Corpus-Rekord für ein Folio); chor 3×; 7 qo-Formen in Spr. A (R33); Marginalinschrift (nicht Voynichesisch, vermutl. Latein)', stars: '★★★★', is5: false },
  { folio: 'f17v', plant: 'Schwarze Zaunrübe (Tamus communis)', signal: '23 Paragraphen (Kräuter-Rekord); sar P.17 ohne {plant} (wie f57r/f103r); sheol Vollform Spr. A P.13 (R34); char im Schlusskolophon; or·okaiin·or Palindrom P.6', stars: '★★★', is5: false },
  { folio: 'f18r', plant: 'Berg-Flockenblume (Centaurea montana)', signal: '13 P. + Siman T.14; 2 =-Kolophone P.4+P.13; chor/qokchor 5× (Leitterm); dar·dar R36-Erstbeleg P.6; doldaiin Corpus-Erstbeleg P.7; doppelter {plant}-Marker P.8; Schlusskolophon or·shaiin·cthor·okal·dar= (stark positiv ★★★★★)', stars: '★★★★', is5: false },
  { folio: 'f18v', plant: 'Drachenwurz (Dracunculus vulgaris)', signal: '10 P.; qokchy/chy 5× (Leitterm); Zoomorphe Drachen-Figur (Corpus-Erstbeleg bot. Abschnitt); {plant} am Kolophon-Anfang R38; qokchy·qokchy R37-Erstbeleg P.2; ykam/ytor (Auferstehungsverben) P.8; dom= Schlusskolophon-Finale Spr. A (R39)', stars: '★★★★', is5: false },
  { folio: 'f19r', plant: 'Stephanskraut (Delphinium staphisagria)', signal: '13 P. + Schlusskolophon P.13; pchor-Eröffnung (Pupillen-Direktional, Primärindikation); chor/ykchor 6×; ckhy-Kompositionen 8× (stärkste Blässe-Dichte in Quire C); ~9 qo-Formen (~11 %); daiin.cthor.chol.ykchor.chordy (P.10, f15v-Parallele)', stars: '★★★★', is5: false },
  { folio: 'f19v', plant: 'Teufelsabbiss (Succisa pratensis)', signal: '12 P. + T.13 Siman; 3 =-Kolophone (P.6a Mini + P.12 Haupt + T.13); daiin·daiin R19-Dopplung P.4 (Corpus-Erstbeleg); yees.ykchol.oty.ytor.ytar.ytchor.ytaiin= (P.12, 7-Verb-Litanei — R49, Corpus-Rekord); ytor 3. Folio-Beleg → ★★★★★; darom (Süden, erster Richtungsterm bot. Corpus)', stars: '★★★★', is5: false },
];
