export const CONCLUSION = {
  title: 'Schlussfolgerung: Sprache A = Sprache B — dialektale Variante',
  intro: 'Die Sprachen A und B sind dialektale Varianten desselben Mischna-Hebräisch/Aramäisch-Systems: A hat höhere o-Vokalfrequenz (Ḥolam), B mehr e-Vokale (Segol/Ṣere). Textgenre, Prognose-Schema, Präfix-System und Kolophon-Konventionen sind identisch — die Quire-Grenze A→B (f8v→f9r) ist textlich unsichtbar. Das Werk ist als Einheit konzipiert.',
  items: [
    '<strong>Quire C vollständig (f17r–f21v, bC1–bC4, 16/16):</strong> <span class="eva">qo-</span>-Präfix emergierend (R33 ★★★: bC1 ~5 %, bC2 ~4–5 %, bC3 ~10 %); <span class="eva">sheol</span> Vollform Spr. A (R34); qo-Dopplung (R37); <span class="eva">dom=</span> Kolophon-Finale (R39). bC3: erste daiin·daiin-Dopplung, 7-gliedrige y+t-Litanei (R49), <span class="eva">ytor</span> → ★★★★★. bC4: <span class="eva">cheol</span> ★★★★ (4. Beleg), R51 ★★★ (Illustrationszwickel), kompaktester Kolophon Corpus (f21v P.8).',
    '<strong>Quire K bK1 vollständig (f71r–f72r2):</strong> B-Register; R50 ★★★★ (ee/oo-Vokalklärung) + R52a ★★★★ (Determinans-y in Sternlabeln); 75 Sternlabeln, 12/12 Ankerwörter (100 %); Doppel-Stier-Hypothese (f71v kalendarisch / f72r1 astromedizinisch).',
    '<strong>Bifolio bD1 (f25r–f25v):</strong> daiin-reichstes Bifolio Corpus — 4 Doppelurteile + 3×daiin in einer Zeile (f25v P.2, R58 ★★★ Kand.); <span class="eva">orchaiin=</span> ★★★★ (neue Kolophon-Formel); <em>Urtica dioica</em> (f25r) + <em>Chelidonium majus</em> mit Drachen-Motiv (f25v).',
    '<strong>Bifolio bD2 (f26r–f26v, Sprache B):</strong> Spr.-B-Einschub; oraiin ★★★★ + dar·dar R36 ★★★★ + qotedy·qotedy R37 ★★★★ je R43 erfüllt; stärkste Sequenz f26v P.4: <span class="eva">or·cheos·oraiin·okeo·chekaiin=</span> (Augenlicht-Kolophon ★★★★).',
    '<strong>Bifolio bD3 vollständig (f27r+f27v+f30r+f30v):</strong> f27r/v (v7.7): <em>Symphytum officinale</em> + <em>Leucanthemum vulgare</em>; R56 ★★★ validiert (<span class="eva">sho·sho</span>-Emphase). f30r (v8.1): <em>Polygonatum multiflorum</em>; R19 Typ E Corpus-Erstbeleg (<span class="eva">cheor·chey·cheor·chey</span>), chain + opchol ★★★ validiert. f30v (v8.1): <em>Urtica dioica</em>; dain ★★★ validiert, R28→<span class="eva">ytor</span> Kand., <span class="eva">chokcheey</span> ★★★★ Kand. (Lebensvorschrift).',
    '<strong>Bifolio bD4 vollständig (f28r–f29v):</strong> ophthalmologischer Bogen — f28r: Diagnose Sehverlust (<em>Plantago major</em>, <span class="eva">ytchol·yteol·deaiin=</span>); f28v: Therapie Augenlicht (<em>Agrimonia eupatoria</em>, <span class="eva">sor·dar=</span> Heilerkolophon); f29r: Begleittherapie Blässe/Fieber (<em>Rumex crispus</em>, R15 Typ C Erstbeleg <span class="eva">shor·chor·sho</span>, shocthy+cheeol ★★★ validiert); f29v: Pharmakopöe Augenpflanzen (<em>Echium vulgare</em>, R35+ytchor ★★★★ + R59 ★★★ validiert).',
    '<strong>Quire D gesamt:</strong> Innenbifolios bD3+bD4 vollständig ✓ · bD1 (f25 ✓, f32 ausstehend) · bD2 (f26 ✓, f31 ausstehend) — <strong>12/16 Seiten analysiert (75 %)</strong>.',
    '<strong>Quire A Retroanalyse vollständig (f1v–f10r, v8.5):</strong> 9 neue Pflanzenteil-Positionskarten. Farbcode Belege 11+12 (f002r + f007r rote Wurzeln). f010r Oval-Strukturen = 3. Nicht-Wurzel-Rot-Beleg → Ebene 2 ★★★★★. FOLIUM-Textfreiheit (R60 Korollar 3): 21/21 Folios ohne Text in Blattzone — unabhängig von Blattfarbe. Quire-A-Therapeutisches Profil: Augenmittel + Atemwegspflanzen + Blutstillung.',
  ],
};

export const COMPARISON = [
  { feature: 'Kernvokabular', langB: 'sheol, daiin, dal, ckhy, dam, sar, or', langA: 'Identisch — alle 10 Ankerwörter je Folio bestätigt (f1r: 10/10 ★★★★★)' },
  { feature: 'qo-Präfix (R1/R33)', langB: '8+ Belege; Kernmerkmal Spr. B ★★★★★', langA: 'Absent in Quires I–II (0 / ~800 Token); ab Quire III präsent: 13 Belege f17r/f17v (~5%) + 8–10 in f18r/f18v (~4–5%) + ~18 in f19r/f19v (~10% = Quire-H-äquivalent, R33-Erweiterung); R37: qo-Präfix-Dopplung ab f18v; R49: y+t-Verb-Litanei f19v P.12; bC4 (f20–f21): Vollintegration bestätigt; bC3 (f22–f23) + bC1 (f24): konsistent — Quire C f17–f24 vollständig' },
  { feature: 'Dominanter Vokal', langB: 'e / ee (Segol/Ṣere)', langA: 'o (Ḥolam) häufiger; dol statt dal, ckho neben ckhy' },
  { feature: 'Struktur', langB: 'Prosa ohne Bildtrennmarker', langA: '{plant}-Marker in Kräuter-Folios (R14); f1r: Prosa ohne Marker (Haskama-Typ, sui generis)' },
  { feature: 'Kolophon-Inventar', langB: 'cphedom=, daiin·cheeodam', langA: 'kaiim=, dom=, daiin=, chckhan=, Kurztitel (R23)' },
  { feature: 'Verbparadigma', langB: 'taiir, yshdal', langA: 'ykchaiin, ycheor, ychor, ytchody — vollständiger' },
  { feature: 'Quire-Grenze', langB: 'Quire A → B (f8v → f9r):', langA: 'textlich unsichtbar — identische Ankerverteilung' },
];

export const FOLIOS = [
  { folio: 'f1r', plant: 'Kein Botanical — Haskama (deklarativer Prosatext)', signal: 'qo-: 0 Belege; 10/10 Ankerwörter; 4 Absätze + T1–T4; &252/&253 Aries-Großinitialen; Erased Key (Jim Reeds 1994)', stars: '★★★★' },
  { folio: 'f1v', plant: 'Belladonna', signal: 'shol 5×, pol (Beere), otoaiin (Pupille)', stars: '★★★★★' },
  { folio: 'f2r', plant: 'Kornblume (Augenwasser)', signal: 'ytoain=, saiin, aiin 8+ Komposita', stars: '★★★★★' },
  { folio: 'f2v', plant: 'Seerose', signal: 'shty (Trank), chokeos (Kelch)', stars: '★★★★' },
  { folio: 'f3r', plant: 'Blutpflanze (Polygonum)', signal: 'dam 4×, damo 2×, sheoldam — höchste Blutdichte', stars: '★★★★★' },
  { folio: 'f4r/v', plant: 'Geranium-Typ', signal: 'shol·chaiin (abwägend)', stars: '★★★★' },
  { folio: 'f5r', plant: 'Mandragora', signal: 'shodaiin 4× pro Satz (narkotisch-toxisch)', stars: '★★★★' },
  { folio: 'f6r', plant: 'Schlafmohn', signal: 'alle drei shol-Formen; kaiim=', stars: '★★★★' },
  { folio: 'f6v', plant: 'Blaue Distel', signal: 'sar-Öffner; dom=; lor (Heilungsrichtung)', stars: '★★★★' },
  { folio: 'f7r', plant: 'Seerose (Nymphaea)', signal: 'sheey 3× (positiv)', stars: '★★★★' },
  { folio: 'f7v', plant: 'Lungenkraut', signal: 'otshol · sheodaiin · lshol — dichteste Todesformeln', stars: '★★★★★' },
  { folio: 'f8r', plant: 'Aronstab (Arum)', signal: 'chor 6×, shol 5×; shol·kaiin×4 + kaiim=', stars: '★★★★' },
  { folio: 'f8v', plant: 'Röhrenblüter / Lungenkraut', signal: 'saiin; chol·chol·chol; daiin= (Quire-Ende)', stars: '★★★★' },
  { folio: 'f9r', plant: 'Sauerampfer (Rumex)', signal: 'or·chaiin (positiv); dsholdy; chkar=', stars: '★★★★' },
  { folio: 'f9v', plant: 'Viola tricolor', signal: 'chkaiin·ckhy·chor= (Diagnosekolophon); daiin 7×', stars: '★★★★★' },
  { folio: 'f10r', plant: 'Wegwarte (Cichorium)', signal: 'Prognose-Tetrade chaiin·ckhy·or·aiin; chor 7×', stars: '★★★★' },
  { folio: 'f10v', plant: 'Convolvulus / Glockenblume', signal: 'daiin 8× (Rekord); shoiin×2; dsho=; chckhan=', stars: '★★★★' },
  { folio: 'f11r', plant: 'Lungenkraut-Typ II', signal: 'ykchor·dair·ycheor (Pupillenheilung-Tripel); positiver Kolophon', stars: '★★★★' },
  { folio: 'f11v', plant: 'Kräuter-Komplex', signal: 'chkaiin·ckhy·chor= (Diagnosekolophon, 2. Beleg); odl·chaiin', stars: '★★★★' },
  { folio: 'f13r', plant: 'Großer Alant (Inula helenium)', signal: 'torshor; pchy 4× — Atemweg-Rekord; shol×2; Doppelkolophon', stars: '★★★' },
  { folio: 'f13v', plant: 'Schachtelhalm-Typ (Equisetum)', signal: '9 × {plant}-Marker (Rekord Quire B); qoky·daiin= (Minikolophon)', stars: '★★★' },
  { folio: 'f14r', plant: 'Schlafmohn (Papaver somniferum) ★★★★ · Alt.: Schlangenwurz-Typ (Bistorta officinalis) ★★★', signal: 'dain + chor dominant; chckhy= (3. Korpus-Beleg); Doppelkolophon P.7 + P.13; ykaiin (5. y+k-Verb); Layout Typ C (P.1–P.7 Blüte/Kapsel FLOS / P.8–P.9 Blätter bilateral FOLIUM); rote Wurzel ohne Text (R60 Ebene 2, Erstbeleg)', stars: '★★★' },
  { folio: 'f14v', plant: 'Farn-Typ (Dryopteris-Gruppe)', signal: 'dam (Blut-Triade P.8, Erstbeleg Quire B); dchckhy= (Intensiv-Siegel); Dreisegment-Kolophon; dy×3 (R25)', stars: '★★★' },
  { folio: 'f15r', plant: 'Silberdistel (Carlina acaulis)', signal: 'qotchor ★★★★★ (Pupillen-Zeichen, Kolophon); ykshol P.12 (erster negativer y+k+Terminus); sheey·cthy·dain (Gabe+Heilung+Auge); chaiin+Abwägungskolophon; Layout Typ B (bilateral: linke Spalte = linke Blütenknospe / rechte Spalte = rechte Blütenknospe); Doppel-{plant}-Marker alle Paragraphen; Sonnen-/Medaillonsymbol über Apex (R60 Muster VI Kand.); rote Wurzel ohne Text (R60 Ebene 2)', stars: '★★★★' },
  { folio: 'f15v', plant: 'Einbeere (Paris quadrifolia)', signal: 'soloiin P.11 (Arznei für Auge) ★★★★★; sor P.10 (Heilungsarznei); opchor P.1 (Atemweg-Pupillen-Befund); cthor·chor= (vollständige Heilung, Kolophon)', stars: '★★★★' },
  { folio: 'f16r', plant: 'Cannabis sativa (Hanf) ★★★★ · Alt.: Wunderbaum (Ricinus communis) ★★★', signal: 'tchor P2.5 (fem. Pupillen-Verb, 1. Beleg); saiin·ytaiin= (Intra-Paragraph-Kolophon); qokchor·dl·dy·shey= (Schlusskolophon); Layout Typ C (P.1.1–2 Blüten FLOS / P.1.3–P.2 Blätter FOLIUM); opchy+saiin+chor FLOS-Position (Atemweg+Augenarzt+Pupille); beige Wurzel ohne Text (R60 Ebene 1); Stolfi: „interrupted by the plant\'s flower" ★★★★★', stars: '★★★★' },
  { folio: 'f16v', plant: 'Alpen-Mannstreu (Eryngium alpinum)', signal: 'chkar·chkar (Doppel-Untersuchungsformel, einmalig); okaiin×2; otor P.12 (Zeichen des Lichts); sokar·oaorar= (Quire-B-Abschlusskolophon)', stars: '★★★★★' },
  { folio: 'f17r', plant: 'Skabiosen-Flockenblume (Centaurea scabiosa)', signal: '3 =-Kolophone P.3+P.6+P.12 (Corpus-Rekord für ein Folio); chor 3×; 7 qo-Formen in Spr. A (R33); Marginalinschrift (nicht Voynichesisch, vermutl. Latein)', stars: '★★★★' },
  { folio: 'f17v', plant: 'Schwarze Zaunrübe (Tamus communis)', signal: '23 Paragraphen (Kräuter-Rekord); sar P.17 ohne {plant} (wie f57r/f103r); sheol Vollform Spr. A P.13 (R34); char im Schlusskolophon; or·okaiin·or Palindrom P.6', stars: '★★★' },
  { folio: 'f18r', plant: 'Berg-Flockenblume (Centaurea montana)', signal: '13 P. + Siman T.14; 2 =-Kolophone P.4+P.13; chor/qokchor 5× (Leitterm); dar·dar R36-Erstbeleg P.6; doldaiin Corpus-Erstbeleg P.7; doppelter {plant}-Marker P.8; Schlusskolophon or·shaiin·cthor·okal·dar= (stark positiv ★★★★★)', stars: '★★★★' },
  { folio: 'f18v', plant: 'Drachenwurz (Dracunculus vulgaris)', signal: '10 P.; qokchy/chy 5× (Leitterm); Zoomorphe Drachen-Figur (Corpus-Erstbeleg bot. Abschnitt); {plant} am Kolophon-Anfang R38; qokchy·qokchy R37-Erstbeleg P.2; ykam/ytor (Auferstehungsverben) P.8; dom= Schlusskolophon-Finale Spr. A (R39)', stars: '★★★★' },
  { folio: 'f19r', plant: 'Kornblume (Centaurea cyanus) ★★★★ · Alt.: Stephanskraut (Delphinium staphisagria) ★★★', signal: '13 P. + Schlusskolophon P.13; pchor-Eröffnung (Pupillen-Direktional, Primärindikation); chor/ykchor 6×; ckhy-Kompositionen 8× (stärkste Blässe-Dichte in Quire C); ~9 qo-Formen (~11 %); daiin.cthor.chol.ykchor.chordy (P.10, f15v-Parallele); Layout Typ A (Gesamttext auf Blüten-Höhe — 0 Texte bei Blättern/Wurzel); saiin+chor = Blüten-Pharmakologie Kornblume (Augenwasser, Konjunktivitis ★★★★★)', stars: '★★★★' },
  { folio: 'f19v', plant: 'Teufelsabbiss (Succisa pratensis)', signal: '12 P. + T.13 Siman; 3 =-Kolophone (P.6a Mini + P.12 Haupt + T.13); daiin·daiin R19-Dopplung P.4 (Corpus-Erstbeleg); yees.ykchol.oty.ytor.ytar.ytchor.ytaiin= (P.12, 7-Verb-Litanei — R49, Corpus-Rekord); ytor 3. Folio-Beleg → ★★★★★; darom (Süden, erster Richtungsterm bot. Corpus)', stars: '★★★★' },
  { folio: 'f20r', plant: 'Süßes Tragant (Astragalus glycyphyllos)', signal: 'chor 6× (Pupillen-Leitterm); qotchol P.1 (Universal-Zeichen); dol·shol P.7 (Schmerz-Scheol, Erstbeleg therapeutisches Fenster); cheol Corpus-Erstbeleg botanisch → ★★★ (R43 erfüllt); doppeltes chor-Schlussparadigma R15 P.13: chor·chor·cheey·tchey= (Pupille—Pupille—Leben—sie belebt); Layout Typ A (Apex-Text: Gesamttext auf Blüten-/Fruchtstand-Höhe — kein Text bei Stängel/Wurzel)', stars: '★★★' },
  { folio: 'f20v', plant: 'Skabiosen-Flockenblume (Centaurea scabiosa)', signal: 'kompakteste Prognoseformel Corpus P.4 (5 Kernwörter im Kolophon); botanische Reihung mit f19v (Scabiosa-Gruppe, bewusste thematische Sequenzierung); Faserwurzelsystem + blaue Köpfchenblüten mit weißem Hüllkelch; balneologisch (Augenbad, Hildegard von Bingen); Quire C bC4 innerstes Bifolio vollständig', stars: '★★★★' },
  { folio: 'f21r', plant: 'Sand-Thymian (Thymus serpyllum)', signal: 'cheol ★★★★ gesichert (4. Beleg! f77r+f20v+f21r P.5+P.8 → R43 definitiv erfüllt, 3 Folios); Dreifache Licht-Formel P.7 (shoeor·cheor·cthor — Corpus-Erstbeleg, R52 Kand.); R15 Typ-B 4. Beleg P.12 (ykeea·chor·…·chor·chkaiin=); Dreifach-Scheol-Sequenz P.11 (shol·chol·shol·tchol — Corpus-Erstbeleg); or/cheol/chor Licht-Dichte 7× (höchste im Corpus); tshaiin Erstbeleg P.9 (★★★ Kand.); Layout Typ A; kein einziger {plant}-Marker in P.1–P.3 = Ganzpflanzen-Präparat TOTUS (R60 A-contrario-Beweis ★★★)', stars: '★★★★' },
  { folio: 'f21v', plant: 'Gemeine Akelei (Aquilegia vulgaris)', signal: 'einfachste Kolophon-Struktur im Corpus: 1 =-Marker (P.8, cho·l·kchochaiin=, 3 Wörter — neuer Rekord); chotshol Corpus-Erstbeleg P.6 (★★★ Kand.: alles-du-wirst-Scheol — intensivstes Negativ-Kompositum); daiin·daiin R19-Dopplung P.4 (2. Beleg → R19 ★★★ best.); doppeltes qokchy P.2; keeees Hapax P.3; s-Einschub R51 P.7 (2. Folio-Beleg → R51 ★★★); Bifolio bC4 vollständig', stars: '★★★★' },
  // ── v7.0 (f22r + f22v — Bifolio bC3 Abschluss: Papaver/kandelaberförmig + Veratrum album) ──
  { folio: 'f22r', plant: 'Papaver / kandelaberförmige Infloreszenz · Alt.: Spitzwegerich (Plantago lanceolata) ★★★', signal: 'oraiino P.9 (Kolophon-Formel: Licht seines Auges ★★★★); R15 5. Beleg (Typ B: qokchol·dar·qokchol — Wortspiegelung mit dar als Zwischentext); cthoinn P.10 (vollständige Augen-Heilung, Variante); ctheor ★★★ Kand. P.9; cphal ★★★ Kand. P.7; ctheen ★★★ Kand. P.6; schor ★★★ Kand. P.4; dsheor P.7 (d-Relativpräfix R45); Layout Typ C (P.1–P.2 Samenkapseln FRUCTUS / P.4+ Spiralinfloreszenz bilateral); pol an Kapsel-Position P.1 ★★★★★ (stärkster Einzelbeweis R60); rote Wurzel ohne Text (R60 Ebene 2)', stars: '★★★★' },
  { folio: 'f22v', plant: 'Weißer Germer (Veratrum album)', signal: 'daldalol= T.16 (R53 Subtyp A Erstbeleg: dal·dal+ol — doppelte Schwäche des Joches); ykcheor ★★★★ P.5 (R43 erfüllt: f22v + Zodiak-Register); okchain ★★★★ P.13 (Heilungsdirektional: auf Leben hin); pysaiinor ★★★ P.1 (Mund gleich dem Auge des Lichts); olshly P.14 (auf Scheol hin); shotoly P.13 (Scheol-Last hin, sho-Präfix R30)', stars: '★★★★' },
  // ── v7.1 (f23r + f23v — Bifolio bC2 Abschluss: Geranium pratense + Borago officinalis) ──
  { folio: 'f23r', plant: 'Wiesen-Storchschnabel (Geranium pratense)', signal: 'Drei-Kolophon-Architektur P.3+P.5+P.11 (strukturelle Parallele zu f17r — Außenbifolio-Korrespondenz Quire C); tshol P.6 als P.6-Strukturtoken (erster Beleg); R15 6. Beleg Typ B nominal: qokchol·dar·qokchol P.7; daiidal P.6 (Urteil der Schwäche ★★★); ytom P.5 (er wird vollständig ★★★); dalory P.11 (Schwäche zum Licht ★★★)', stars: '★★★★' },
  { folio: 'f23v', plant: 'Borretsch (Borago officinalis)', signal: 'dam·dam P.8 (bilateral — Corpus-Erstbeleg Quire C, Borago-Blutklärungsindikation); tshol P.6 (P.6-Strukturtoken 2. Beleg: beide Seiten desselben Folios f23r+f23v); sar P.6 (Arzt-Supervision über {plant}, 3. Folio-Beleg → ★★★★); qokor P.8 (und alles Licht ★★★); otshor P.6 (Zeichen des Lichts ★★★); olsar P.6 (ärztliche Aufsicht ★★★); aiior P.12 (Auge des Lichts ★★★); Bifolio bC2 vollständig', stars: '★★★★' },
  // ── v7.2 (f24r + f24v — Bifolio bC1 Abschluss: Silene vulgaris + Physalis-Typ/Scabiosa) ──
  { folio: 'f24r', plant: 'Taubenkropf-Leimkraut (Silene vulgaris)', signal: 'R53 3. T-Klassen-Beleg T.20: sam.chorly= (so heile meine Pupille — R43 erfüllt); sar×2 P.x (3. Folio-Beleg → sar ★★★★); dal·dam·dal-Triplette P.16 (R54 Erstbeleg ★★ Kand.); sshey P.17 (Doppel-Shin-Blässe, R56 ★★★ Kand.); otaiphy P.19 (Hapax ★★ Kand.); sam.chorly ★★★ Kand.; Botanik: Hämostase + Augenwirkung + Supervision', stars: '★★★★' },
  { folio: 'f24v', plant: 'Physalis-Typ / Scabiosa ★★★ · Alt.: Küchenschelle (Pulsatilla vulgaris) ★★', signal: 'Quire-Zeichen „39" = III = Quire C (letztes Folio Quire C); ot-Kompositum-Dreikette P.2 (otol+otaiir+otchos — R50-Beobachtung); olom ★★★★ P.7 (Ewigkeit/Welt); otaiir ★★★★ P.2 (Zeichen des Augenlichts); cheekdam ★★★★ P.14 (wie das Zeichen des Blutes); oro= P.5 (or-Palindrom-Reduplikation, R55 ★★★ Kand.); odaiim= P.16 (Abschluss-Kolophon-Marker, R57 ★★ Kand.); sho.sho P.14 (R56 ★★ Kand.); Quire C vollständig (16/16 = 100 %); Layout Typ C unilateral-links (oberer Block Blüten+Knollen FLOS / unterer Block Knollen+Blätter); grüne Knollen mit Text; orange Wurzel ohne Text (R60 Ebene 1)', stars: '★★★★' },
  // ── v7.3 (f25r + f25v — Bifolio bD1 Eröffnung: Urtica dioica + Chelidonium majus) ──
  { folio: 'f25r', plant: 'Brennnessel (Urtica dioica)', signal: 'R53 4. T-Klassen-Beleg T.7: dair.otaiir.otosy= (Subtyp C — deskriptiv/identifikatorisch: Zeichen-Augenlicht → R53 ★★★★); otaiir Zweitbeleg → ★★★★★ Kand. (R43 erfüllt); daiin·daiin P.5 + daiin P.1 (4×daiin im Bifolio); otosy ★★★ Kand. T.7 (Zeichen-Scheol-gleich-er); cheesees ★★★ Kand. P.3 (Dreifach-Licht-Zeichen); soshy ★★★ Kand. P.1; Bifolio bD1 (Quire D außen): Kontinuität zu Quire C bestätigt; Botanik: Blut/Anämie + Augenindikation; dunkelrote Bohnen an Stengelknoten ohne Text (R60 Ebene 2 Nicht-Wurzel-Erstbeleg ★★★★★ — Reeds: Colors: green,dark-red); T.7 als Pflanzenteil-Deskriptor an Blattspitze (grüne FOLIUM-Zone → R60-Erweiterung, ★★★★ Kand.)', stars: '★★★★' },
  { folio: 'f25v', plant: 'Schöllkraut (Chelidonium majus)', signal: 'orchaiin= P.7 (neue Kolophon-Abschlussformel ★★★★: or+chor/k+aiin = Licht-wie-Auge); 3×daiin P.2 (dchor.cthor.chor.daiin.s.okeeaiin.daiin.ckhey.daiin — Corpus-Erstbeleg 3×daiin in einer Zeile, R58 ★★★ Kand.); daiin·daiin P.5 (4. Doppelurteil im Bifolio); ckhear ★★★★ P.4 (ckh-Variante: wie das Licht); qokoral ★★★ Kand. P.6; daiity ★★★ Kand. P.3; R33 qo-Belege: qochol P.5, qokcho + qotchy P.6 (Quire-D-Einstieg Kontinuität); Drachen-Motiv (Toxizitätssignal + Augenheilung); Botanik: Augen (toxisch) + Scheol', stars: '★★★★' },
  // ── v7.6 (f26r + f26v — Bifolio bD2: Solanum nigrum + Centaurea cyanus — Sprache B) ──
  { folio: 'f26r', plant: 'Schwarzer Nachtschatten (Solanum nigrum) — Sprache B', signal: 'Erster Sprache-B-Einschub Quire D (bD2); Diagnose-Leitterm: psheoky (Pe+Scheol-Öffnung), chckhy (Blässe), dal (Schwäche); Therapie: sar+dal+dar; ykeechy ★★★ Kand. P.9 (8. y+k-Verb: er heilt wie Blässe-Licht); qoteedar ★★★ Kand. P.8 (und er/du wirst leuchten); eedy ★★★ Kand. P.5 (Negativ-Licht-Genitiv); 10 Paragraphen; ={plant}-Abschluss P.10 (otal=); Prognose: ambivalent (psheoky-Toxizität / sheey-Gabe); Indikation: Pallor, Augenschwäche, Atemwegsbefund', stars: '★★★' },
  { folio: 'f26v', plant: 'Kornblume (Centaurea cyanus) — Sprache B', signal: 'Sprache-B-Folgenseite bD2; oraiin ★★★★ P.4 (R43 erfüllt: f22r+f26v = 2 Folios); R36 dar·dar Typ B → ★★★★ P.6 (f18r+f26v = 2 Folios); R37 qo-Dopplung → ★★★★ P.5: qotedy·qotedy (f18v+f26v = 2 Folios); stärkste Sequenz P.4: or·cheos·oraiin·okeo·chekaiin= (Augenlicht-Kolophonformel ★★★★, H/C/F/U einig); saraiir ★★★ Kand. P.2 (Arzt des Leuchtenden); daiiin ★★★ Kand. P.1+P.7; cheeol ★★★ Kand. P.3; ory ★★★ Kand. P.8; 9 Paragraphen; ={plant}-Abschluss P.9 (dy=); beidseitige ={plant}-Symmetrie mit f26r; Indikation: Augenlicht, Augenentzündung', stars: '★★★★' },
  // ── v7.7 (f27r + f27v — Bifolio bD3: Symphytum officinale + Leucanthemum vulgare) ──
  { folio: 'f27r', plant: 'Beinwell (Symphytum officinale) · Alt.: Ochsenzunge (Anchusa officinalis) ★★★', signal: 'ksor+shey-Eignungsformel P.1 (ksor ★★★ Kand.); Scheol-Trias P.2; chol·shy-Parallelismus P.3 (Herzstück); qokey P.4 + qotchey P.10 (R33 qo- in Spr. A Quire D bestätigt); cphary ★★★ Kand. P.5 (Sühnopfer-Formel); Doppelkolophon P.6= + P.12a=; daiiin P.12 → ★★★★ (R43 dreifach erfüllt: f1r+f26v+f27r = 3 Folios); shod ★★★ Kand. P.1; chees·chos (Kälte/Hitze, hippokratische Diagnosekontraste) P.12; 12 Paragraphen + 1 Titelzeile; Indikation: Lungenentzündung, Wunden, Blutstillstand', stars: '★★★★' },
  { folio: 'f27v', plant: 'Wiesen-Margerite (Leucanthemum vulgare) · Alt.: Mutterkraut (Tanacetum parthenium) ★★★', signal: 'Dreifach-Scheol + kchor·chor P.1 (schwere ophthalmologische Diagnose); shy·shy-Gabe-Intensivierung P.2 (Heilungsoptimismus R19); dsho P.3 + P.6 (Scheol-Genealogie); qoky P.5 (R33 qo- in Spr. A Quire D); sho·sho-Emphase P.7 → R56 ★★★ validiert (R43 erfüllt: f24v P.14 + f27v P.7 = 2 Folios); Heilungskolophon kshy= P.8 (kshy ★★★ Kand.); fochof/chof ★★★ Kand. P.1 (Mund/Kehle-alles); kchrrr Hapax P.6 (Dreifach-r); 8 Paragraphen + Kolophon-Pflanzensegment; Indikation: Augenentzündung, ophthalmologische Komplikation; Bifolio bD3 abgeschlossen', stars: '★★★★' },
  // ── v7.8 (f28r + f28v — Bifolio bD4: Plantago major + Agrimonia eupatoria) ──
  { folio: 'f28r', plant: 'Großer Wegerich (Plantago major)', signal: 'Ophthalmologische Diagnosesequenz: or+chor+otaiin Leitterm; ytchol·yteol·deaiin= (y+t-Doppelverb-Kolophon, Corpus-Erstbeleg) P.9; pchodar ★★★ Kand. P.1 (Finsternis/Dunkelheit); kshol ★★★★ P.1 (wie Scheol); qo-Solitär P.1 → R59 ★★★ validiert (R43 erfüllt: f1v+f28r = 2 Folios); shod ★★★ validiert P.1 (R43 erfüllt: f27r+f28r); 9 Paragraphen; dreifache Dunkelheits-Metaphorik; Indikation: Sehverlust, Scheol-Ophthalmologie; Bifolio bD4 (innerstes Quire D); Layout Typ B (bilateral-Ähre: Diagnose links / Therapie rechts auf gleicher Spadix-Höhe); rote Wurzel ohne Text (R60 Ebene 2)', stars: '★★★★' },
  { folio: 'f28v', plant: 'Odermennig (Agrimonia eupatoria) · Alt.: Baldrian (Valeriana officinalis) ★★★', signal: 'Augenheilungs-Therapiesequenz: ykcholy ★★★★ P1.2 (er heilt alles); tshoiin ★★★★ P1.4 ([sie] wendet das Auge von Scheol); dreifache {plant}-Marker P2.8 (Corpus-Erstbeleg — Dreiphasen-Rezept); Heilerkolophon sor·dar= P2.9 (sor ★★★★ Arzt-Variante); Kurztitel T1.6: daiin.chkaiin= (R23 2. Quire-D-Beleg); chear ★★★ Kand. P2.9; 5+1T+3 Texteinheiten; Bifolio bD4 vollständig — Quire-D-Zentrum ophthalmologisch gesichert', stars: '★★★★' },
  // ── v7.9 (f29r + f29v — Bifolio bD4 Abschluss: Rumex crispus + Echium vulgare) ──
  { folio: 'f29r', plant: 'Krauser Ampfer (Rumex crispus)', signal: 'Begleittherapie Blässe + Fieber; poraiin ★★★ Kand. P.1 (Licht des Auges); shor·shor P.6 → R19-Erweiterung auf shor-Stamm (Corpus-Erstbeleg shor-Dopplung, ★★★ Kand.); R15 Typ C Erstbeleg P.8: shor·chor·sho — Dreikette als semantisches Spannungsfeld; shocthy ★★★ validiert (R43: f28r P.7+f29r P.6); cheeol ★★★ validiert (R43: f26v P.3+f29r P.5); shos ★★★ Kand. P.5; shokchy ★★★ Kand. P.7; ychom ★★★ Kand. P.9; 9 Paragraphen; Kolophon-Marker P.4+P.9; Indikation: Blutarmut, Blässe, Fieber', stars: '★★★' },
  { folio: 'f29v', plant: 'Natternkopf / Viper\'s Bugloss (Echium vulgare)', signal: 'Pharmakopöe-Katalog Augenpflanzen (21+ {plant}-Marker); chol·chol R35-Cluster P.2+P.3 → R35 ★★★ validiert (R43: f17v+f29v = 2 Folios); ytchor ★★★★ P.2 (R43: f16v+f29v = 2 Folios); tchor Zweitbeleg P.8 → ★★★★ bestätigt; shot ★★★ Kand. P.4; chain ★★★ Kand. P.5 → R43 erfüllt f30r; chykar ★★ Kand. P.10; Dual-Kolophon: shot·sho·okaiin= (neg.) + ykaiin-oaiin= (pos.); 12 Paragraphen; Bifolio bD4 vollständig — Quire D abgeschlossen', stars: '★★★★' },
  // ── v8.1 (f30r + f30v — Bifolio bD3 Abschluss: Polygonatum multiflorum + Urtica dioica) ──
  { folio: 'f30r', plant: 'Salomonssiegel (Polygonatum multiflorum) ★★★★ · Alt.: Traubenhyazinthe (Muscari racemosum) ★★★', signal: '13 Paragraphen; R19 Typ E Corpus-Erstbeleg P.11: cheor·chey·cheor·chey (ABAB-Licht-Leben-Verflechtung, ★★★ Kand.); chor solitär zwischen 2 {plant} P.12 (diagnostischer Kern visuell eingerahmt); chain ★★★ validiert P.7 (R43 erfüllt: f29v+f30r); opchol ★★★ validiert P.8 (R43 erfüllt: f28r+f30r); Kolophon P.7: qor·chain·cthorchy= (Dreiterm positiv); Kolophon P.13: chodaiin·chtchey·chear·shy·keey=; chorain ★★★ Kand. P.3; cthorchy ★★★ Kand. P.7; dchorol + chseeor ★★★ Kand. P.6; soin ★★★ Kand. P.4; ~14× {plant}-Marker; Indikation: Blässe-Ophthalmologie, Pupillenheilung, Licht-Sandwich-Formel; Layout Typ C (P.1–P.7 Beeren FRUCTUS / P.8–P.13 Blatt+Rhizom FOLIUM/CAULIS — zwei Zonen, chor solitär P.12 = Rhizom-Kernterm)', stars: '★★★★★' },
  { folio: 'f30v', plant: 'Brennnessel (Urtica dioica) ★★★★ · Alt.: Hängebirke (Betula pendula) ★★★', signal: '11 Paragraphen; stärkste Scheol-Dichte bD3 (~8× sho/shol); dain ★★★ validiert P.5 (R43 erfüllt: f1r+f30v); R28 Erweiterung ytor = y+t+or Kand. P.5 (erste Anwendung auf kurzen or-Stamm); Schlusskolophon P.11: shol·chokcheey·daiin·kchydy= (chokcheey ★★★★ Kand. Lebensvorschrift); shosaiin ★★★★ Kand. P.1 (Scheol des Augenarztes); cphoaiin ★★★ Kand. P.8 (wie der Atemweg des Auges, 3/3 Transkriptoren); sos ★★★ Kand. P.7+P.9 (2× auf diesem Folio); kcho·tcho·ctho morphologisches Triplett P.7; 9× {plant}-Marker; Bifolio bD3 vollständig; Quire-D-Innenbifolios bD3+bD4 abgeschlossen; orange-braune Wurzel ohne Text (R60 Ebene 1 — Folgebeleg zu f24v)', stars: '★★★★' },
];
