// Confirmed lexicon with entries ★★★+
export const LEXICON = [
  // ── Medizinische Nomina & Symptome ──────────────────
  { eva: 'dam',       heb: 'דָּם',              de: 'Blut',                                        stars: '★★★★★', cat: 'symptom' },
  { eva: 'dal',       heb: 'דַּל',              de: 'schwach / abgemagert',                        stars: '★★★★',  cat: 'symptom' },
  { eva: 'daly',      heb: 'דַּלִּי',           de: 'seine/meine Schwäche (Possessiv)',             stars: '★★★★',  cat: 'symptom' },
  { eva: 'ckhy',      heb: 'כְּהִי',            de: 'Blässe / Trübheit',                           stars: '★★★★',  cat: 'symptom' },
  { eva: 'okaiin',    heb: 'עַכְּעַיִן',        de: 'auf das Auge',                                stars: '★★★★',  cat: 'symptom' },
  { eva: 'qokaiin',   heb: 'וְכְּעַיִן',        de: 'und gemäß dem Auge',                          stars: '★★★★',  cat: 'symptom' },
  { eva: 'qotal',     heb: 'וְטַל',             de: 'Tau / Schweißzeichen',                        stars: '★★★',   cat: 'symptom' },
  { eva: 'ram',       heb: 'רָם',               de: 'erhöht / Fieber',                             stars: '★★★',   cat: 'symptom' },
  { eva: 'chor',      heb: 'חֹר',               de: 'Pupille / Höhle',                             stars: '★★★★',  cat: 'symptom' },
  { eva: 'otchor',    heb: 'אוֹת+חֹר',          de: 'das Zeichen der Pupille',                     stars: '★★★★',  cat: 'symptom' },
  { eva: 'oraiin',    heb: 'אוֹר+עַיִן',        de: 'Licht des Auges / Augenheilung',              stars: '★★★★',  cat: 'symptom' },
  { eva: 'sheoldam',  heb: 'שְׁאוֹל+דָּם',      de: 'tödlicher Blutverlust',                       stars: '★★★★★', cat: 'symptom' },
  { eva: 'damo',      heb: 'דָּמוֹ',            de: 'sein Blut (Possessiv)',                       stars: '★★★★',  cat: 'symptom' },
  { eva: 'cham',      heb: 'חַם',               de: 'Wärme / Entzündung',                          stars: '★★★',   cat: 'symptom' },
  { eva: 'torshor',   heb: 'תֹּר+שׁוֹר',        de: 'Jahreszeit-Zeichen / saisonaler Eintrag',     stars: '★★★',   cat: 'symptom' },
  { eva: 'dchm',      heb: 'דְּ+חָם',           de: 'von der Entzündung',                          stars: '★★★',   cat: 'symptom' },
  { eva: 'dalor',     heb: 'דַּלאוֹר',          de: 'schwaches Augenlicht',                        stars: '★★★',   cat: 'symptom' },
  { eva: 'char',      heb: 'חַר',               de: 'heiß / Fieber',                               stars: '★★★★',  cat: 'symptom' },
  { eva: 'chary',     heb: 'חַרִי',             de: 'sein Fieber (Possessiv)',                     stars: '★★★',   cat: 'symptom' },
  { eva: 'ckhal',     heb: 'כְּהַל',            de: 'Nachlassen des Fiebers',                      stars: '★★★',   cat: 'symptom' },
  { eva: 'dol',       heb: 'דָּוֶה',            de: 'Schmerz / Krankheit',                         stars: '★★★',   cat: 'symptom' },
  { eva: 'odol',      heb: 'עַ+דָּוֶה',         de: 'auf die Krankheit (o+dol)',                   stars: '★★★★',  cat: 'symptom' },
  { eva: 'dolar',     heb: 'דָּוֶה+לְאוֹר',     de: 'Krankheit zur Heilung',                       stars: '★★★',   cat: 'symptom' },
  { eva: 'shees',     heb: 'אֵשׁ',              de: 'Feuer / Fieberbrand',                         stars: '★★★',   cat: 'symptom' },
  { eva: 'shorodo',   heb: 'שׁוֹר+עוֹדוֹ',      de: 'das Zeichen besteht fort',                    stars: '★★★',   cat: 'symptom' },
  { eva: 'oeees',     heb: 'עַ+אֵשׁ',           de: 'auf dem Feuer/Fieber',                        stars: '★★★',   cat: 'symptom' },
  { eva: 'octhos',    heb: 'עַ+כְּ+תֹ+שׁ',      de: 'auf wie Feuer/Fieber',                        stars: '★★★',   cat: 'symptom' },
  // ── Prognose-Termini ────────────────────────────────
  { eva: 'or',        heb: 'אוֹר',              de: 'Licht / Heilung',                             stars: '★★★★',  cat: 'prognose' },
  { eva: 'sheol',     heb: 'שְׁאוֹל',           de: 'Scheol / Tod',                                stars: '★★★★',  cat: 'prognose' },
  { eva: 'shol',      heb: 'שׁוֹל',             de: 'Tod (apokor. Spr. A)',                        stars: '★★★★★', cat: 'prognose' },
  { eva: 'daiin',     heb: 'דִּין',             de: 'Urteil / Prognose',                           stars: '★★★★',  cat: 'prognose' },
  { eva: 'chalal',    heb: 'חָלָל',             de: 'Sterbender',                                  stars: '★★★★',  cat: 'prognose' },
  { eva: 'chodl',     heb: 'חֹדֵל',             de: 'der Aufhörende / der Sterbende',              stars: '★★★',   cat: 'prognose' },
  { eva: 'dair',      heb: 'דְּ+אִיר',          de: 'der Leuchtende / Licht davon',                stars: '★★★',   cat: 'prognose' },
  { eva: 'aiin',      heb: 'אַיִן',             de: 'nichts / nicht vorhanden',                    stars: '★★★',   cat: 'prognose' },
  { eva: 'eeor',      heb: 'אֵאוֹר',            de: 'kein Licht',                                  stars: '★★★',   cat: 'prognose' },
  { eva: 'lor',       heb: 'לְאוֹר',            de: 'zum Licht / zur Heilung',                     stars: '★★★★★', cat: 'prognose' },
  { eva: 'lshol',     heb: 'לְשׁוֹל',           de: 'zum Tod / zu Scheol',                         stars: '★★★★★', cat: 'prognose' },
  { eva: 'chaiin',    heb: 'חַיִּין',           de: 'Leben (Chayyim)',                             stars: '★★★★',  cat: 'prognose' },
  { eva: 'sheey',     heb: 'שֵׁי',              de: 'Gabe / Wohlbefinden',                         stars: '★★★★',  cat: 'prognose' },
  { eva: 'cheor',     heb: 'כְּאוֹר',           de: 'wie Licht (Heilungszeichen)',                 stars: '★★★★',  cat: 'prognose' },
  { eva: 'otshol',    heb: 'אוֹתשׁוֹל',         de: 'das Zeichen des Todes',                       stars: '★★★★★', cat: 'prognose' },
  { eva: 'chan',      heb: 'חָן',               de: 'Gnade / günstige Prognose',                  stars: '★★★★',  cat: 'prognose' },
  { eva: 'dom',       heb: 'דּוֹם',             de: 'Stille / Ende',                               stars: '★★★★',  cat: 'prognose' },
  { eva: 'dsholdy',   heb: 'דְּ+שׁוֹל+דִּי',    de: 'von Scheol — dessen (Genitiv)',               stars: '★★★★★', cat: 'prognose' },
  { eva: 'dsho',      heb: 'דְּ+שׁוֹ',          de: 'von Scheol (Kurzform)',                       stars: '★★★★',  cat: 'prognose' },
  { eva: 'shoiin',    heb: 'שׁוֹ+עַיִן',        de: 'Scheol des Auges',                            stars: '★★★★',  cat: 'prognose' },
  { eva: 'shoin',     heb: 'שׁוֹ+יִן',          de: 'Scheol des Auges (Var. von shoiin; abw. Transkription)', stars: '★★',    cat: 'prognose' },
  { eva: 'darchor',   heb: 'דַּרְכּוֹר',        de: 'sein Krankheitsverlauf',                      stars: '★★★',   cat: 'prognose' },
  { eva: 'otan',      heb: 'עֹתָן',             de: 'Zeit / Jahreszeit der Erkrankung',            stars: '★★★',   cat: 'prognose' },
  { eva: 'kaiim',     heb: 'קַיָּם',            de: 'gültig / beständig (Schlussformel)',          stars: '★★★★★', cat: 'kolophon' },
  { eva: 'okorory',   heb: 'עַכְּאוֹראוֹרִי',   de: 'auf das Licht — mein Licht / zum Licht',     stars: '★★★',   cat: 'kolophon' },
  { eva: 'cphar',     heb: 'כְּ+פַּר',          de: 'Sühne / Bedeckung (Kolophon-Formel)',         stars: '★★★',   cat: 'kolophon' },
  // ── Syntaktische Konnektoren ────────────────────────
  { eva: 'chedy',     heb: 'כְּדֵי',            de: 'damit / um zu (Var.: kedy)',                   stars: '★★★★',  cat: 'syntax' },
  { eva: 'shedy',     heb: 'שֶׁדִּי',           de: 'das/welches von',                             stars: '★★★★',  cat: 'syntax' },
  { eva: 'shdy',      heb: 'שֶׁדִּי',           de: 'das/welches von (Kurz)',                      stars: '★★★★',  cat: 'syntax' },
  { eva: 'dy',        heb: 'דִּי',              de: 'von / dessen (Aram.)',                        stars: '★★',    cat: 'syntax' },
  { eva: 'lchedy',    heb: 'לְכְּדֵי',          de: 'um zu / bis zur Grenze',                      stars: '★★★★',  cat: 'syntax' },
  { eva: 'chal',      heb: 'חָל',               de: 'gilt für / betrifft',                         stars: '★★★',   cat: 'syntax' },
  { eva: 'shodaiin',  heb: 'שׁוֹדִּין',         de: 'Todesurteil',                                 stars: '★★★★',  cat: 'syntax' },
  { eva: 'sheodaiin', heb: 'שְׁאוֹדִּין',       de: 'Todesurteil (Vollform)',                      stars: '★★★★★', cat: 'syntax' },
  { eva: 'daiindy',   heb: 'דִּין+דִּי',        de: 'das Urteil dessen (Var.: daiidy)',             stars: '★★★★★', cat: 'syntax' },
  { eva: 'qodaiin',   heb: 'וְדִּין',           de: 'und Urteil',                                  stars: '★★★★',  cat: 'syntax' },
  { eva: 'daiim',     heb: 'דִּין+ם',           de: 'Urteile (Plural)',                            stars: '★★★',   cat: 'syntax' },
  { eva: 'keey',      heb: 'כֵּי',              de: 'denn / weil (Kausalpartikel)',                stars: '★★★★',  cat: 'syntax' },
  { eva: 'qoky',      heb: 'וְ+כִּי',           de: 'und denn / weil',                             stars: '★★★★★', cat: 'syntax' },
  { eva: 'cthom',     heb: 'כְּ+תֹם',           de: 'wie Vollständigkeit (Kolophon; Vokalvar.: chetom)', stars: '★★★',   cat: 'kolophon' },
  // ── Verbformen ──────────────────────────────────────
  { eva: 'taiir',     heb: 'תָּאִיר',           de: 'es wird leuchten / heilen',                   stars: '★★★★',  cat: 'verb' },
  { eva: 'yteechy',   heb: 'יִחְיֶה',           de: 'er wird gesund',                              stars: '★★★',   cat: 'verb' },
  { eva: 'yshdal',    heb: 'יְשַׁדַּל',         de: 'er wird schwächen',                           stars: '★★★',   cat: 'verb' },
  { eva: 'ykeedy',    heb: 'יְכֵּדֵי',          de: 'er wird anordnen',                            stars: '★★★',   cat: 'verb' },
  { eva: 'ykchy',     heb: 'יְ+כְּ+הִי',        de: 'er wird Blässe zeigen',                       stars: '★★★★',  cat: 'verb' },
  { eva: 'tsheoarom', heb: 'תְּשְׁאוֹרוֹם',     de: 'du wirst von Scheol aufsteigen',              stars: '★★★★',  cat: 'verb' },
  { eva: 'chkar',     heb: 'חֲקַר',             de: 'er untersucht',                               stars: '★★★',   cat: 'verb' },
  { eva: 'ydaiin',    heb: 'יְדִּין',           de: 'er urteilt',                                  stars: '★★★★',  cat: 'verb' },
  { eva: 'ysho',      heb: 'יְשׁוֹ',            de: 'es führt zum Tod',                            stars: '★★★★',  cat: 'verb' },
  { eva: 'ykeor',     heb: 'יְכְּאוֹר',         de: 'er heilt / wie Licht',                        stars: '★★★★',  cat: 'verb' },
  { eva: 'ykchaiin',  heb: 'יְ+כְּ+חַיִּין',   de: 'er wird wie Leben werden',                    stars: '★★★★',  cat: 'verb' },
  { eva: 'ykchor',    heb: 'יְ+כְּ+חֹר',        de: 'er heilt die Pupille',                        stars: '★★★★★', cat: 'verb' },
  { eva: 'ycheor',    heb: 'יְ+כְּ+אוֹר',       de: 'er wird wie Licht werden',                    stars: '★★★★',  cat: 'verb' },
  { eva: 'tchey',     heb: 'תְּחִי',            de: 'möge es/sie leben! (Jussiv)',                 stars: '★★★★',  cat: 'verb' },
  { eva: 'ychor',     heb: 'יְ+חֹר',            de: 'er wird die Pupille weiten',                  stars: '★★★★',  cat: 'verb' },
  { eva: 'yodaiin',   heb: 'יוֹדִּין',          de: 'er weiß das Urteil',                          stars: '★★★★',  cat: 'verb' },
  { eva: 'ytchody',   heb: 'יְ+תְּ+כֹּ+דִּי',  de: 'er wird urteilen (Doppelpräfix)',              stars: '★★★',   cat: 'verb' },
  { eva: 'ytaiin',    heb: 'יְ+תָּ+עַיִן',      de: 'er wird das Auge heilen',                     stars: '★★★★',  cat: 'verb' },
  { eva: 'ykoiin',    heb: 'יְכוֹיִן',          de: 'er wird sich erholen',                        stars: '★★★',   cat: 'verb' },
  // ── Akteure, Anatomie & Botanik ─────────────────────
  { eva: 'sar',       heb: 'שַׂר',              de: 'Arzt / Meister / Vorsteher',                  stars: '★★★★',  cat: 'akteur' },
  { eva: 'sary',      heb: 'שַׂרִי',            de: 'mein Arzt (Possessiv)',                       stars: '★★★',   cat: 'akteur' },
  { eva: 'pchy',      heb: 'פְּחִי',            de: 'mein Atem / mein Mund',                       stars: '★★★',   cat: 'akteur' },
  { eva: 'opchor',    heb: 'עַ+פְּ+חֹר',        de: 'auf die Pupille (Atemweg-Befund)',             stars: '★★★',   cat: 'akteur' },
  { eva: 'al',        heb: 'עַל',               de: 'auf / über / betreffend (Var.: ol)',           stars: '★★★★',  cat: 'akteur' },
  { eva: 'saiin',     heb: 'שַׂעַיִן',          de: 'Augenarzt',                                   stars: '★★★★',  cat: 'akteur' },
  { eva: 'dain',      heb: 'דַּ+עַיִן',         de: 'das Auge (Kurzform)',                         stars: '★★★',   cat: 'akteur' },
  { eva: 'oiin',      heb: 'עַ+יִן',            de: 'das Auge (direkte Form)',                     stars: '★★★★',  cat: 'akteur' },
  { eva: 'doaiin',    heb: 'דְּ+עַיִן',         de: 'vom Auge (Var.: doiin)',                       stars: '★★★★',  cat: 'akteur' },
  { eva: 'kchol',     heb: 'כְּ+חֹל',           de: 'wie Augensalbe / Kohl-Pigment (Blaupigment)', stars: '★★★',   cat: 'akteur' },
  { eva: 'sam',       heb: 'שַׂם',              de: 'Arznei / er gibt',                            stars: '★★★',   cat: 'akteur' },
  { eva: 'shty',      heb: 'שְׁתִי',            de: 'Getränk / Trank',                             stars: '★★★',   cat: 'akteur' },
  { eva: 'pol',       heb: 'פֹּל',              de: 'Bohne / Beere',                               stars: '★★★',   cat: 'akteur' },
  { eva: 'otoaiin',   heb: 'עַתוֹעַיִן',        de: 'auf seine Augen',                             stars: '★★★',   cat: 'akteur' },
  { eva: 'chokeos',   heb: 'כֹּכֵּאוֹס',        de: 'wie ein Kelch (Botanik)',                     stars: '★★★',   cat: 'akteur' },
  // ── Bestätigte Komposita ────────────────────────────
  { eva: 'qokedam',   heb: 'וְ+כְּ+דָּם',       de: 'und wie das Blut',                            stars: '★★★★',  cat: 'kompositum' },
  { eva: 'okoldm',    heb: 'עַל+כֹּל+דָּם',     de: 'über alles Blut',                             stars: '★★★★',  cat: 'kompositum' },
  { eva: 'pchedal',   heb: 'פְּ+כֶּ+דַּל',      de: 'bei dem Schwachen',                           stars: '★★★',   cat: 'kompositum' },
  { eva: 'cholar',    heb: 'כֹּ+לוֹ+ר',         de: 'alles sein Licht',                            stars: '★★★',   cat: 'kompositum' },
  { eva: 'qokchor',   heb: 'וְ+עַ+כְּ+חֹר',     de: 'und für die Pupille',                         stars: '★★★★★', cat: 'kompositum' },
  { eva: 'shydal',    heb: 'שֵׁי+דַּל',         de: 'die Gabe der Schwäche',                       stars: '★★★',   cat: 'kompositum' },
  // ── Possessiv-Formen ────────────────────────────────
  { eva: 'olsho',     heb: 'שׁוֹ+לוֹ',          de: 'sein Scheol (Possessiv)',                     stars: '★★★',   cat: 'possessiv' },
  // ── v5.6 (f14r + f14v) ────────────────
  { eva: 'pcho',      heb: 'פְּחֹ',             de: 'Atem/Mund (Spr.-A-Variante von pchy)',         stars: '★★★',   cat: 'akteur' },
  { eva: 'chok',      heb: 'חֹק',               de: 'Vorschrift / ärztliche Anordnung / Rezept',    stars: '★★★',   cat: 'symptom' },
  { eva: 'choky',     heb: 'חֹקֵּי',            de: 'die Vorschriften des [Falls] (Konstr.-Plural)',stars: '★★★',   cat: 'symptom' },
  { eva: 'chokshor',  heb: 'כְּ+חֹק+שׁוֹר',    de: 'wie die Vorschrift des Zeichens',              stars: '★★★★',  cat: 'kompositum' },
  { eva: 'ykaiin',    heb: 'יְ+כְּ+עַיִן',      de: 'er heilt das Auge (5. y+k+Terminus-Verb)',     stars: '★★★★',  cat: 'verb' },
  { eva: 'yfodain',   heb: 'יְ+פָּדָה+יִן',     de: 'er wird das Auge erlösen/befreien',            stars: '★★★★',  cat: 'verb' },
  { eva: 'ydain',     heb: 'יְ+דַ+יִן',         de: 'er wird das Auge behandeln',                  stars: '★★★★',  cat: 'verb' },
  { eva: 'ypchor',    heb: 'יְ+פְּ+חֹר',        de: 'er heilt die Pupille [durch Atem]',            stars: '★★★',   cat: 'verb' },
  { eva: 'teor',      heb: 'תְּ+אוֹר',          de: 'sie wird heilen (fem. Imperfekt von or)',       stars: '★★★★',  cat: 'verb' },
  { eva: 'qotchor',   heb: 'קוֹ+תְּ+כֹּר',       de: 'Pupillen-Zeichen / Urteil der Pupille (Schlusskolophon f15r)', stars: '★★★★★', cat: 'kompositum' },
  { eva: 'otcho',     heb: 'אוֹת+כֹּ',          de: 'das Zeichen des [Atems] (Kolophon-Kurzform)',  stars: '★★★',   cat: 'kolophon' },
  { eva: 'otchy',     heb: 'אוֹת+כְּ+הִי',      de: 'das Zeichen der Blässe',                       stars: '★★★★',  cat: 'symptom' },
  { eva: 'dchckhy',   heb: 'דְּ+כְּ+כְּ+הִי',  de: 'von tiefer Blässe (Intensiv-Diagnosesiegel)',  stars: '★★★★',  cat: 'kolophon' },
  { eva: 'chey',      heb: 'חֵי',               de: 'lebendig / am Leben (Adj.)',                   stars: '★★★',   cat: 'prognose' },
  { eva: 'oeeen',     heb: 'עַ+אֵין',           de: 'auf das Fehlen / Nichts (emphatic null)',       stars: '★★★',   cat: 'prognose' },
  { eva: 'oir',       heb: 'עַ+אוֹר',           de: 'auf das Licht / Direktional-Heilung',          stars: '★★★',   cat: 'prognose' },
  { eva: 'choor',     heb: 'כְּ+אוּר',          de: 'wie das Licht (lang-vokalisierte Variante)',   stars: '★★★',   cat: 'prognose' },
  { eva: 'ksho',      heb: 'כְּ+שׁוֹ',          de: 'wie Scheol/Tod (Komparativform)',              stars: '★★★',   cat: 'prognose' },
  { eva: 'schol',     heb: 'שׂ+כֹּל',           de: 'Arznei für alles / Universalheilmittel',       stars: '★★★',   cat: 'akteur' },
  { eva: 'dala',      heb: 'דַּלָּ',            de: 'Schwäche (fem., Femininum von dal)',            stars: '★★★',   cat: 'symptom' },
  { eva: 'koiin',     heb: 'כֹּ+עַיִן',         de: 'wie das Auge (komparativ, kol-Stamm)',         stars: '★★★',   cat: 'akteur' },
  { eva: 'kaiin',     heb: 'כְּ+עַיִן',         de: 'wie das Auge (komparativ, k-Präfix; Var.: keaiin)', stars: '★★★',   cat: 'akteur' },
  { eva: 'okshy',     heb: 'עַ+כְּ+שֵׁי',       de: 'auf/für die Gabe (therapeutischer Direktional)',stars: '★★★',  cat: 'akteur' },
  { eva: 'cthor',     heb: 'כְּ+תֹּר',          de: 'vollständige Heilung',                         stars: '★★★',   cat: 'verb' },
  { eva: 'dshy',      heb: 'דְּ+שֵׁי',          de: 'von der Gabe (d-Genitivkonstrukt)',            stars: '★★★',   cat: 'kompositum' },
  // ── v5.8 (f16r + f16v) ────────────────
  // f16r
  { eva: 'tchor',     heb: 'תְּ+חֹר',           de: 'sie heilt die Pupille (fem. Imperfekt)',        stars: '★★★★',  cat: 'verb' },
  { eva: 'ykair',     heb: 'יְ+כְּ+אִיר',        de: 'er heilt leuchtend (Kandidat 7. y+k+Terminus) — R43 provisorisch ★★: nur f16r (1×), unter Mindestgrenze 8×', stars: '★★',    cat: 'verb' },
  { eva: 'pocheody',  heb: 'פְּ+חֹ+דִּי',        de: 'des Atemwegs (Genitiv von pcho)',              stars: '★★★',   cat: 'akteur' },
  { eva: 'toror',     heb: 'תְּ+אוֹר+אוֹר',      de: 'sie heilt — Licht — Licht (Doppel-Licht-Heilung)', stars: '★★★', cat: 'verb' },
  { eva: 'daly·dal',  heb: 'דַּלִּי+דַּל',       de: 'seine Schwäche — schwach (R19 Dopplung ×2)',   stars: '★★★★',  cat: 'symptom' },
  { eva: 'dalchy',    heb: 'דַּל+כְּהִי',        de: 'die Schwäche der Blässe',                      stars: '★★★★',  cat: 'symptom' },
  { eva: 'dainod',    heb: 'דַּ+אִין+עֹד',       de: 'er behandelt das Auge weiter',                 stars: '★★★',   cat: 'verb' },
  { eva: 'shody',     heb: 'שְׁאוֹ+דִּי',        de: 'von Scheol — dessen (Genitiv)',                stars: '★★★',   cat: 'prognose' },
  { eva: 'otly',      heb: 'אוֹת+לֵ',            de: 'Zeichen zu/für (oto-Direktional)',             stars: '★★★',   cat: 'kompositum' },
  { eva: 'opchy',     heb: 'עַ+פְּ+הִי',         de: 'auf den Atemweg (o+pchy-Direktional)',         stars: '★★★',   cat: 'akteur' },
  // f16v
  { eva: 'ytchor',    heb: 'יְ+תְּ+חֹר',         de: 'er/sie wird die Pupille heilen (y+t-Doppelpräfix)', stars: '★★★', cat: 'verb' },
  { eva: 'ytchy',     heb: 'יְ+תְּ+כְּהִי',      de: 'er/sie wird Blässe zeigen (y+t-Doppelpräfix)', stars: '★★★',  cat: 'verb' },
  { eva: 'pchraiin',  heb: 'פְּ+רְ+עַיִן',       de: 'für/bei das Licht des Auges',                 stars: '★★★',   cat: 'akteur' },
  { eva: 'sholo',     heb: 'שְׁאוֹ+לוֹ',         de: 'Scheol für ihn (Dativ-Form)',                  stars: '★★★',   cat: 'prognose' },
  { eva: 'otor',      heb: 'אוֹת+אוֹר',          de: 'Zeichen des Lichts / der Heilung',             stars: '★★★',   cat: 'kompositum' },
  { eva: 'otain',     heb: 'אוֹת+אַיִן',         de: 'Zeichen des Nichts / Endes',                   stars: '★★★',   cat: 'kompositum' },
  { eva: 'okytaiin',  heb: 'עַ+כְּ+תָּ+עַיִן',   de: 'auf die Weise, dass er das Auge heilt',        stars: '★★★',   cat: 'verb' },
  { eva: 'dairin',    heb: 'דְּ+אִיר+יִן',       de: 'von dem Leuchtenden (Genitiv-Form)',           stars: '★★★',   cat: 'prognose' },
  { eva: 'sokar',     heb: 'שׂ+אוֹ+כְּ+אָר',     de: 'Heilungs-Arzt des Lichts (Quire-B-Kolophon)',  stars: '★★★',   cat: 'kolophon' },
  { eva: 'oaorar',    heb: 'עַ+אַ+אוֹר+אָר',     de: 'auf das Licht der Heilung (Doppel-Licht-Formel)', stars: '★★★★', cat: 'kolophon' },
  { eva: 'dan',       heb: 'דָּן',               de: 'er hat geurteilt (Qal Perfekt)',               stars: '★★★',   cat: 'verb' },
  { eva: 'koshet',    heb: 'כֹּ+שֵׁ+תְּ',        de: 'Scheol-Vollständigkeit (temporaler Abschlussterm)', stars: '★★', cat: 'prognose' },
  // ── v5.9 (f1r — Eröffnungsfolio, Haskama) ────────────
  { eva: 'shodain',  heb: 'שׁוֹד+דַּ+עַיִן',   de: 'Zerstörung des Auges (schärfste negative Augenprognose)', stars: '★★★★', cat: 'kompositum' },
  { eva: 'shoaiin',  heb: 'שְׁאוֹל+עַיִן',      de: 'Scheol des Auges (Todesurteil für das Sehorgan)',        stars: '★★★★', cat: 'prognose'   },
  { eva: 'kchom',    heb: 'כְּ+חֹם',            de: 'wie Hitze / wie Fieber (Temperatur-Komparativ) — R43 Kand.-Flag: f001r (2×, 1 Folio), nächste 5 Folios prüfen',  stars: '★★★',  cat: 'symptom'    },
  { eva: 'oksho',    heb: 'עַ+כְּ+שׁוֹ',        de: 'auf/gegen Scheol (erste präpositionale Scheol-Form Spr. A)', stars: '★★★★', cat: 'prognose' },
  { eva: 'dydyd',    heb: 'דִּי+דִּי+דִּי',     de: 'dreifacher Relativpartikel — extremer Betonungsmodus',  stars: '★★★',  cat: 'syntax'     },
  // ── v6.0 (f17r + f17v — Quire C Eröffnung) ───────────
  // f17r
  { eva: 'chom',      heb: 'חֹם',               de: 'Wärme / Hitze (eigenständige Form, Schwesterform von cham)',    stars: '★★★',  cat: 'symptom'    },
  { eva: 'fshody',    heb: 'פְּ+שׁוֹ+דִּי',     de: 'von Scheol — dessen (Pe-Genitiv-Scheol-Konstrukt)',              stars: '★★★',  cat: 'prognose'   },
  { eva: 'oldckhy',   heb: 'עַל+דְּ+כְּ+הִי',  de: 'über die Blässe davon (dreifach-präpositionaler Terminus)',      stars: '★★★',  cat: 'symptom'    },
  { eva: 'qokcheor',  heb: 'וְ+כְּ+כְּ+אֵוֹר', de: 'und wie das Licht (doppelter k-Komparativ + Vav)',               stars: '★★★',  cat: 'kompositum' },
  { eva: 'dor',       heb: 'דֹּר',              de: 'Generation / Zeitraum der Erkrankung',                          stars: '★★★',  cat: 'symptom'    },
  { eva: 'otchol',    heb: 'אוֹת+כֹּל',         de: 'Zeichen von allem / Universalzeichen',                          stars: '★★★',  cat: 'kompositum' },
  { eva: 'cphor',     heb: 'כְּ+פְּ+אֹר',       de: 'wie der Mund des Lichts',                                       stars: '★★',   cat: 'kompositum' },
  { eva: 'ychody',    heb: 'יְ+כֹּ+דִּי',       de: 'er wird urteilen (Variante von ytchody)',                       stars: '★★★',  cat: 'verb'       },
  { eva: 'tsho',      heb: 'תְּ+שׁוֹ',          de: 'sie entfernt sich von Scheol (fem. Impf. + Scheol-Kurzform)',   stars: '★★★',  cat: 'verb'       },
  { eva: 'opydaiin',  heb: 'עַ+פִּי+דִּין',     de: 'bei/beim Urteil des Mundes (Atemweg-Urteil-Verbund)',           stars: '★★★',  cat: 'kompositum' },
  // f17v
  { eva: 'pchodol',   heb: 'פְּחֹ+דֹּל',         de: 'Atemweg der Krankheit / Mundschmerz (pcho + dol)',             stars: '★★★',  cat: 'symptom'    },
  { eva: 'qopchaiin', heb: 'וְ+פְּ+כְּ+עַיִן',  de: 'und Atemweg des Auges (Atemweg-Auge-Verbund)',                 stars: '★★★',  cat: 'kompositum' },
  { eva: 'sholor',    heb: 'שׁוֹל+אֹר',          de: 'Scheol-Licht (Todes-Licht-Kompositum, Kandidat)',              stars: '★★',   cat: 'prognose'   },
  { eva: 'okeor',     heb: 'עַ+כְּ+אֵוֹר',       de: 'auf/zu dem Licht hin (direktionale Variante)',                 stars: '★★★',  cat: 'prognose'   },
  { eva: 'ycheol',    heb: 'יְ+כְּ+אֵוֹל',       de: 'er wird wie Scheol-Licht sein (ambivalente Verbform)',         stars: '★★',   cat: 'verb'       },
  { eva: 'chol·chol', heb: 'כֹּל·כֹּל',          de: 'alles-alles (R19 Intensivierungsdopplung, Nominalstamm)',      stars: '★★★',  cat: 'syntax'     },
  { eva: 'sheor',     heb: 'שֶׁ+אֹר',            de: 'das/welches Licht ist (Relativpartikel + Licht)',              stars: '★★★',  cat: 'syntax'     },
  { eva: 'odaldy',    heb: 'עַ+דַּל+דִּי',       de: 'über die Schwäche dessen (o-Direktional + dal + Genitiv)',     stars: '★★★',  cat: 'kompositum' },
  { eva: 'chkeey',    heb: 'כְּ+כְּ+אֵ+יִ',      de: 'wie wie Lebendigkeit (doppelter Lebens-Komparativ)',           stars: '★★★',  cat: 'kolophon'   },
  { eva: 'oekor',     heb: 'עַ+אֵ+קֹר',          de: 'auf die Kälte / das Uprooting (direktional)',                  stars: '★★',   cat: 'symptom'    },
  { eva: 'okeom',     heb: 'עַ+כְּ+אֵוֹם',       de: 'auf die Vollendung hin (Kolophon-Direktional)',                stars: '★★★',  cat: 'kolophon'   },
  // ── v6.1 (f18r + f18v — Bifolio bC2) ────────────────
  // f18r — Centaurea montana (Berg-Flockenblume)
  { eva: 'ytchar',    heb: 'יְ+תְּ+חַר',         de: 'er/sie wird Fieber zeigen (y+t-Doppelpräfix + char)',          stars: '★★★',  cat: 'verb'       },
  { eva: 'ykchol',    heb: 'יְ+כֹּל / יְ+כָּ+חֹל', de: 'er heilt alles / er heilt Augenpigment',                    stars: '★★★',  cat: 'verb'       },
  { eva: 'cthaiin',   heb: 'כְּ+תַּ+עַיִן',       de: 'vollständige Augen-Heilung (cthor-Variante + Auge-Suffix)',   stars: '★★★',  cat: 'verb'       },
  { eva: 'cthal',     heb: 'כְּ+תַּ+חַל',         de: 'wie vollständig (Kolophon-Variante von cthor)',               stars: '★★★',  cat: 'kolophon'   },
  { eva: 'chckhy',    heb: 'חֶ+כָּ+הִי',          de: 'Blässe-Hitze-Zeichen (Kompositum: char+ckhy)',                stars: '★★★',  cat: 'symptom'    },
  { eva: 'okain',     heb: 'עַ+כְּ+עַיִן',        de: 'auf das Auge (Kurzform von okaiin)',                          stars: '★★★',  cat: 'akteur'     },
  { eva: 'doldaiin',  heb: 'דּוֹל+דִּין',         de: 'Krankheits-Urteil (analog zu shodaiin = Todesurteil)',        stars: '★★★',  cat: 'syntax'     },
  { eva: 'doldy',     heb: 'דּוֹל+דִּי',          de: 'von der Krankheit davon (dol + Genitivpartikel)',             stars: '★★★',  cat: 'syntax'     },
  { eva: 'dary',      heb: 'דַּרִי',              de: 'mein Leuchtendes / mein Licht (Possessiv von dar)',           stars: '★★★',  cat: 'prognose'   },
  { eva: 'sotchaiin', heb: 'שׁ+אוֹת+כְּ+עַיִן',  de: 'das Zeichen dem Auge gleich (sho+otchor+aiin-Kompositum)',   stars: '★★★',  cat: 'kompositum' },
  { eva: 'chokchy',   heb: 'חֹק+כְּ+הִי',         de: 'Vorschrift der Blässe (chok + ckhy-Kompositum)',             stars: '★★★',  cat: 'symptom'    },
  { eva: 'chekhol',   heb: 'כְּ+כָּ+חֹל',         de: 'wie das Augenpigment (doppelter Komparativ)',                 stars: '★★★',  cat: 'akteur'     },
  { eva: 'ychair',    heb: 'יְ+חַ+אִיר',          de: 'er wird durch Wärme leuchten (Heilungsverb mit char-Stamm)',  stars: '★★★',  cat: 'verb'       },
  { eva: 'ychekchy',  heb: 'יְ+כְּ+כְּ+הִי',      de: 'er heilt wie totale Blässe (doppelter k-Komparativ)',         stars: '★★★',  cat: 'verb'       },
  { eva: 'kchaiin',   heb: 'כְּ+חַ+עַיִן',        de: 'wie die Wärme des Auges (Siman-Formel)',                      stars: '★★★',  cat: 'kompositum' },
  { eva: 'okal',      heb: 'עַ+כָּל',             de: 'auf/über alles (o-Direktional + kol)',                        stars: '★★★',  cat: 'kompositum' },
  { eva: 'yoar',      heb: 'יְ+אַ+אָר',           de: 'er wird zum Licht hin [heilen] (y-Imperfekt + ar-Licht)',     stars: '★★',   cat: 'verb'       },
  // f18v — Dracunculus vulgaris (Drachenwurz)
  { eva: 'told',      heb: 'תּוֹלֵד',             de: 'es erzeugt/bringt hervor (Imperfekt Qal von ילד)',            stars: '★★★',  cat: 'verb'       },
  { eva: 'ytchm',     heb: 'יְ+תְּ+חֵם',          de: 'er/sie wird Wärme bringen (y+t-Doppelpräfix + cham)',         stars: '★★★',  cat: 'verb'       },
  { eva: 'otchdal',   heb: 'אוֹת+כְּ+דַּל',       de: 'Zeichen der Schwäche (oto + Direktional + dal)',              stars: '★★★★', cat: 'kompositum' },
  { eva: 'dchal',     heb: 'דְּ+חַל',             de: 'von dem was gilt / von dem Sterbenden (d-Genitiv + chal)',    stars: '★★★',  cat: 'syntax'     },
  { eva: 'dchy',      heb: 'דְּ+כָּ+הִי',          de: 'von der Blässe davon (d-Genitiv + ckhy)',                    stars: '★★★',  cat: 'symptom'    },
  { eva: 'qotchy',    heb: 'וְ+אוֹת+כְּ+הִי',     de: 'und das Zeichen der Blässe (qo + otchy)',                    stars: '★★★★', cat: 'kompositum' },
  { eva: 'qokay',     heb: 'וְ+כְּ+חַי',          de: 'und wie lebendig (qo + k + chay)',                           stars: '★★★',  cat: 'syntax'     },
  { eva: 'ydl',       heb: 'יִדַּל',              de: 'er wird schwach werden (Imperfekt Qal von דלל)',              stars: '★★★',  cat: 'verb'       },
  { eva: 'ychoees',   heb: 'יְ+כֹּ+עֵשׁ',         de: 'er löscht das Feuer / heilt das Fieber (y + kol + esh)',     stars: '★★★',  cat: 'verb'       },
  { eva: 'qol',       heb: 'וְ+עַל',              de: 'und auf/über (qo-Präfix + ol-Direktional)',                   stars: '★★★',  cat: 'syntax'     },
  { eva: 'qotchol',   heb: 'וְ+אוֹת+כֹּל',        de: 'und das Universal-Zeichen (qo + otchol)',                    stars: '★★★',  cat: 'kompositum' },
  { eva: 'daiir',     heb: 'דַּ+אִיר',            de: 'der Leuchtende (verlängerte Form von dair)',                  stars: '★★★',  cat: 'prognose'   },
  { eva: 'ychol',     heb: 'יְ+כֹּל',             de: 'er heilt alles (Verbform, y-Imperfekt + kol; Var.: ykol f18v P.10)', stars: '★★★★', cat: 'verb'       },
  { eva: 'chod',      heb: 'חֹד',                 de: 'Schärfe / Akutheit (medizinischer Terminus)',                 stars: '★★★',  cat: 'symptom'    },
  { eva: 'tolol',     heb: 'תֹּלֹל',              de: 'geschwächt / hängend (med. Zustand, Adj.)',                   stars: '★★★',  cat: 'symptom'    },
  { eva: 'cphoy',     heb: 'כְּ+פְּ+הוֹ',         de: 'wie sein Atemweg / wie sein Mund (Komparativ)',               stars: '★★★',  cat: 'akteur'     },
  { eva: 'ytor',      heb: 'יְ+תֹּ+אוֹר',         de: 'er/sie wird zum Licht werden / erleuchten (Auferstehungs-/Illuminations-Verb; Langform: yteor) — R43 dreifach bestätigt: f18v (3×) + f58r P.30 + f19v P.12 → ★★★★★ Kand.', stars: '★★★★★', cat: 'verb'       },
  { eva: 'ykam',      heb: 'יְ+קָם',              de: 'er wird aufstehen / sich erheben (y-Imperfekt von קום qum) — R43 Kand.: nur f18v (4×), zweiter Folio-Beleg ausstehend',  stars: '★★★',  cat: 'verb'       },
  { eva: 'doky',      heb: 'דּוֹ+כִּי',           de: 'sein denn / weil (Genitiv-Kausalpartikel)',                   stars: '★★★',  cat: 'syntax'     },
  { eva: 'qoeees',    heb: 'וְ+עַ+אֵשׁ',          de: 'und auf dem Feuer / Fieber (qo + oeees)',                    stars: '★★★★', cat: 'symptom'    },
  { eva: 'qokeees',   heb: 'וְ+כְּ+עֵשׁ',         de: 'und wie Feuer / Fieber (qo + k + esh)',                      stars: '★★★★', cat: 'symptom'    },
  { eva: 'qokshy',    heb: 'וְ+כְּ+שֵׁי',         de: 'und wie die Gabe (qo-Präfix + okshy)',                       stars: '★★★',  cat: 'kompositum' },
  { eva: 'ykar',      heb: 'יְ+כְּ+אָר',          de: 'er heilt leuchtend (Variante von ykair, Quire-C-Form)',       stars: '★★★★', cat: 'verb'       },
  // ── v6.4 (f58r — Erster astronomischer Stresstest, Quire H) ──────────────
  { eva: 'shalom',      heb: 'שָׁלוֹם',                de: 'Friede / günstige Konstellation — Corpus-Erstbeleg; R43-Kand.: f58r P.4 (beide Transkriptoren identisch)',              stars: '★★★',  cat: 'prognose'   },
  { eva: 'qor',         heb: 'וְ+אֹר',                 de: 'und Licht (qo-Konjunktion + or-Anker, astronomisch) — f58r P.5',                                                       stars: '★★★★', cat: 'kompositum' },
  { eva: 'ytalar',      heb: 'יְ+תַּ+אֹר',             de: 'er wird [Licht] geben/erleuchten (or-Ketten-Verb, f58r P.5)',                                                          stars: '★★★',  cat: 'verb'       },
  { eva: 'dshor',       heb: 'דְּ+שׁוֹר / דְּ+אֹר',   de: 'von/des Lichts (Aramaismus: d-Relativpräfix R45, kein D1-Flag) — f58r P.4',                                           stars: '★★★',  cat: 'prognose'   },
  { eva: 'opsheolaiin', heb: 'עַ+פֶּ+שְׁאוֹל+עַיִן',  de: 'am Nadir-Punkt des Sternauges (op-Koordinatenmarker, R41-Erweiterung) — f58r P.26',                                   stars: '★★★',  cat: 'kompositum' },
  // ── v6.5 (f19r + f19v — Bifolio bC3: Stephanskraut + Teufelsabbiss) ──────
  // f19r — Delphinium staphisagria
  { eva: 'oscheor',   heb: 'עַ+שֶׁ+אוֹר',          de: 'auf dem was Licht ist (o + she + cheor-Kompositum) — f19r P.3',                                                          stars: '★★★',  cat: 'prognose'   },
  { eva: 'qokorar',   heb: 'וְ+כֹּ+אוֹר+אָר',       de: 'und alles Licht der Heilung (qo + kol + or + ar) — f19r P.4',                                                           stars: '★★★',  cat: 'kompositum' },
  { eva: 'cthar',     heb: 'כְּ+תַּ+חַר',           de: 'wie vollständiges Fieber (Quire-C-a-Vokal-Variante von cthor) — f19r P.7',                                              stars: '★★★',  cat: 'symptom'    },
  { eva: 'otytchy',   heb: 'אוֹת+יְ+תְּ+כְּ+הִי',  de: 'das Zeichen er-wird-Blässe-zeigen (ot + ytchy-Kompositum) — f19r P.6',                                                 stars: '★★★',  cat: 'kompositum' },
  { eva: 'daiinol',   heb: 'דִּין+עַל',             de: 'Urteil über [etwas] (daiin + ol-Direktional) — f19r P.12',                                                              stars: '★★★',  cat: 'syntax'     },
  { eva: 'octhor',    heb: 'עַ+כְּ+תֹּר',           de: 'auf vollständige Heilung (o-Direktional + cthor, Schlusskolophon-Term) — f19r P.13',                                    stars: '★★★★', cat: 'kolophon'   },
  // f19v — Succisa pratensis
  { eva: 'pochaiin',  heb: 'פֹּ+כְּ+עַיִן',         de: 'beim/am Auge (Pe-Direktional + kaiin-Basis) — f19v P.1',                                                               stars: '★★★',  cat: 'akteur'     },
  { eva: 'darom',     heb: 'דָּרוֹם',               de: 'Süden (erster Richtungsterm im botanischen Corpus) — f19v P.2',                                                         stars: '★★★',  cat: 'symptom'    },
  { eva: 'ytol',      heb: 'יְ+תֹּלֹל',             de: 'er wird geschwächt (y-Imperfekt von tolol) — f19v P.3',                                                                 stars: '★★★',  cat: 'verb'       },
  { eva: 'ddor',      heb: 'דְּ+דֹּר',              de: 'von Generation/Zeitraum [intensiv] (d-Relativpräfix + dor) — f19v P.8',                                                 stars: '★★★',  cat: 'symptom'    },
  { eva: 'okchan',    heb: 'עַ+כְּ+חָן',            de: 'auf/für die Gnade (o + k + chan, positive Prognose-Direktional) — f19v P.9',                                            stars: '★★★★', cat: 'prognose'   },
  { eva: 'otam',      heb: 'אוֹת+תָּם',             de: 'Zeichen der Vollständigkeit/Integrität (ot + tam) — f19v P.10',                                                         stars: '★★★',  cat: 'kompositum' },
  { eva: 'okchod',    heb: 'עַ+כְּ+חֹד',            de: 'auf die Schärfe/Akutheit (o + k + chod, therapeutischer Direktional) — f19v P.11',                                     stars: '★★★★', cat: 'kompositum' },
  { eva: 'yees',      heb: 'יְ+אֵשׁ',               de: 'er löscht das Feuer/Fieber (y-Imperfekt + esh-Stamm) — f19v P.12',                                                      stars: '★★★',  cat: 'verb'       },
  { eva: 'ytar',      heb: 'יְ+תַּ+אָר',            de: 'er wird Licht geben (Quire-C-a-Vokal-Variante von ytor) — f19v P.12',                                                  stars: '★★★',  cat: 'verb'       },
];
