// Confirmed lexicon with entries ★★★+
export const LEXICON = [
  // ── Medizinische Nomina & Symptome ──────────────────
  { eva: 'dam',       heb: 'דָּם',              de: 'Blut',                                        stars: '★★★★★', cat: 'symptom' },
  { eva: 'dal',       heb: 'דַּל',              de: 'schwach / abgemagert',                        stars: '★★★★',  cat: 'symptom' },
  { eva: 'daly',      heb: 'דַּלִּי',           de: 'seine/meine Schwäche (Possessiv)',             stars: '★★★★',  cat: 'symptom' },
  { eva: 'ckhy',      heb: 'כְּהִי',            de: 'Blässe / Trübheit',                           stars: '★★★★',  cat: 'symptom' },
  { eva: 'okaiin',    heb: 'עַכְּעַיִן',        de: 'auf das Auge',                                stars: '★★★★',  cat: 'symptom' },
  { eva: 'qokaiin',   heb: 'וְכְּעַיִן',        de: 'und gemäß dem Auge',                          stars: '★★★★',  cat: 'symptom' },
  { eva: 'qotal',     heb: 'וְטַל',             de: 'Tau / Schweißzeichen',                        stars: '★★★',   cat: 'symptom' },
  { eva: 'ram',       heb: 'רָם',               de: 'erhöht / Fieber',                             stars: '★★★',   cat: 'symptom' },
  { eva: 'chor',      heb: 'חֹר',               de: 'Pupille / Höhle',                             stars: '★★★★',  cat: 'symptom' },
  { eva: 'otchor',    heb: 'אוֹת+חֹר',          de: 'das Zeichen der Pupille',                     stars: '★★★★',  cat: 'symptom' },
  { eva: 'oraiin',    heb: 'אוֹר+עַיִן',        de: 'Licht des Auges / Augenheilung',              stars: '★★★★',  cat: 'symptom' },
  { eva: 'sheoldam',  heb: 'שְׁאוֹל+דָּם',      de: 'tödlicher Blutverlust',                       stars: '★★★★★', cat: 'symptom' },
  { eva: 'damo',      heb: 'דָּמוֹ',            de: 'sein Blut (Possessiv)',                       stars: '★★★★',  cat: 'symptom' },
  { eva: 'cham',      heb: 'חַם',               de: 'Wärme / Entzündung',                          stars: '★★★',   cat: 'symptom' },
  { eva: 'torshor',   heb: 'תֹּר+שׁוֹר',        de: 'Jahreszeit-Zeichen / saisonaler Eintrag',     stars: '★★★',   cat: 'symptom' },
  { eva: 'dchm',      heb: 'דְּ+חָם',           de: 'von der Entzündung',                          stars: '★★★',   cat: 'symptom' },
  { eva: 'dalor',     heb: 'דַּלאוֹר',          de: 'schwaches Augenlicht',                        stars: '★★★',   cat: 'symptom' },
  { eva: 'char',      heb: 'חַר',               de: 'heiß / Fieber',                               stars: '★★★★',  cat: 'symptom' },
  { eva: 'chary',     heb: 'חַרִי',             de: 'sein Fieber (Possessiv)',                     stars: '★★★',   cat: 'symptom' },
  { eva: 'ckhal',     heb: 'כְּהַל',            de: 'Nachlassen des Fiebers',                      stars: '★★★',   cat: 'symptom' },
  { eva: 'dol',       heb: 'דָּוֶה',            de: 'Schmerz / Krankheit',                         stars: '★★★',   cat: 'symptom' },
  { eva: 'odol',      heb: 'עַ+דָּוֶה',         de: 'auf die Krankheit (o+dol)',                   stars: '★★★★',  cat: 'symptom' },
  { eva: 'dolar',     heb: 'דָּוֶה+לְאוֹר',     de: 'Krankheit zur Heilung',                       stars: '★★★',   cat: 'symptom' },
  { eva: 'shees',     heb: 'אֵשׁ',              de: 'Feuer / Fieberbrand',                         stars: '★★★',   cat: 'symptom' },
  { eva: 'shorodo',   heb: 'שׁוֹר+עוֹדוֹ',      de: 'das Zeichen besteht fort',                    stars: '★★★',   cat: 'symptom' },
  { eva: 'oeees',     heb: 'עַ+אֵשׁ',           de: 'auf dem Feuer/Fieber',                        stars: '★★★',   cat: 'symptom' },
  { eva: 'octhos',    heb: 'עַ+כְּ+תֹ+שׁ',      de: 'auf wie Feuer/Fieber',                        stars: '★★★',   cat: 'symptom' },
  // ── Prognose-Termini ────────────────────────────────
  { eva: 'or',        heb: 'אוֹר',              de: 'Licht / Heilung',                             stars: '★★★★',  cat: 'prognose' },
  { eva: 'sheol',     heb: 'שְׁאוֹל',           de: 'Scheol / Tod',                                stars: '★★★★',  cat: 'prognose' },
  { eva: 'shol',      heb: 'שׁוֹל',             de: 'Tod (apokor. Spr. A)',                        stars: '★★★★★', cat: 'prognose' },
  { eva: 'daiin',     heb: 'דִּין',             de: 'Urteil / Prognose',                           stars: '★★★★',  cat: 'prognose' },
  { eva: 'chalal',    heb: 'חָלָל',             de: 'Sterbender',                                  stars: '★★★★',  cat: 'prognose' },
  { eva: 'chodl',     heb: 'חֹדֵל',             de: 'der Aufhörende / der Sterbende',              stars: '★★★',   cat: 'prognose' },
  { eva: 'dair',      heb: 'דְּ+אִיר',          de: 'der Leuchtende / Licht davon',                stars: '★★★',   cat: 'prognose' },
  { eva: 'aiin',      heb: 'אַיִן',             de: 'nichts / nicht vorhanden',                    stars: '★★★',   cat: 'prognose' },
  { eva: 'eeor',      heb: 'אֵאוֹר',            de: 'kein Licht',                                  stars: '★★★',   cat: 'prognose' },
  { eva: 'lor',       heb: 'לְאוֹר',            de: 'zum Licht / zur Heilung',                     stars: '★★★★★', cat: 'prognose' },
  { eva: 'lshol',     heb: 'לְשׁוֹל',           de: 'zum Tod / zu Scheol',                         stars: '★★★★★', cat: 'prognose' },
  { eva: 'chaiin',    heb: 'חַיִּין',           de: 'Leben (Chayyim)',                             stars: '★★★★',  cat: 'prognose' },
  { eva: 'sheey',     heb: 'שֵׁי',              de: 'Gabe / Wohlbefinden',                         stars: '★★★★',  cat: 'prognose' },
  { eva: 'cheor',     heb: 'כְּאוֹר',           de: 'wie Licht (Heilungszeichen)',                 stars: '★★★★',  cat: 'prognose' },
  { eva: 'otshol',    heb: 'אוֹתשׁוֹל',         de: 'das Zeichen des Todes',                       stars: '★★★★★', cat: 'prognose' },
  { eva: 'chan',      heb: 'חָן',               de: 'Gnade / günstige Prognose',                  stars: '★★★★',  cat: 'prognose' },
  { eva: 'dom',       heb: 'דּוֹם',             de: 'Stille / Ende',                               stars: '★★★★',  cat: 'prognose' },
  { eva: 'dsholdy',   heb: 'דְּ+שׁוֹל+דִּי',    de: 'von Scheol — dessen (Genitiv)',               stars: '★★★★★', cat: 'prognose' },
  { eva: 'dsho',      heb: 'דְּ+שׁוֹ',          de: 'von Scheol (Kurzform)',                       stars: '★★★★',  cat: 'prognose' },
  { eva: 'shoiin',    heb: 'שׁוֹ+עַיִן',        de: 'Scheol des Auges',                            stars: '★★★★',  cat: 'prognose' },
  { eva: 'shoin',     heb: 'שׁוֹ+יִן',          de: 'Scheol des Auges (Kurzform)',                 stars: '★★★★',  cat: 'prognose' },
  { eva: 'darchor',   heb: 'דַּרְכּוֹר',        de: 'sein Krankheitsverlauf',                      stars: '★★★',   cat: 'prognose' },
  { eva: 'otan',      heb: 'עֹתָן',             de: 'Zeit / Jahreszeit der Erkrankung',            stars: '★★★',   cat: 'prognose' },
  { eva: 'kaiim',     heb: 'קַיָּם',            de: 'gültig / beständig (Schlussformel)',          stars: '★★★★★', cat: 'kolophon' },
  { eva: 'okorory',   heb: 'עַכְּאוֹראוֹרִי',   de: 'auf das Licht — mein Licht / zum Licht',     stars: '★★★',   cat: 'kolophon' },
  { eva: 'cphar',     heb: 'כְּ+פַּר',          de: 'Sühne / Bedeckung (Kolophon-Formel)',         stars: '★★★',   cat: 'kolophon' },
  // ── Syntaktische Konnektoren ────────────────────────
  { eva: 'chedy',     heb: 'כְּדֵי',            de: 'damit / um zu',                               stars: '★★★★',  cat: 'syntax' },
  { eva: 'kedy',      heb: 'כְּדֵי',            de: 'damit / um zu',                               stars: '★★★★',  cat: 'syntax' },
  { eva: 'shedy',     heb: 'שֶׁדִּי',           de: 'das/welches von',                             stars: '★★★★',  cat: 'syntax' },
  { eva: 'shdy',      heb: 'שֶׁדִּי',           de: 'das/welches von (Kurz)',                      stars: '★★★★',  cat: 'syntax' },
  { eva: 'dy',        heb: 'דִּי',              de: 'von / dessen (Aram.)',                        stars: '★★★★',  cat: 'syntax' },
  { eva: 'lchedy',    heb: 'לְכְּדֵי',          de: 'um zu / bis zur Grenze',                      stars: '★★★★',  cat: 'syntax' },
  { eva: 'chal',      heb: 'חָל',               de: 'gilt für / betrifft',                         stars: '★★★',   cat: 'syntax' },
  { eva: 'shodaiin',  heb: 'שׁוֹדִּין',         de: 'Todesurteil',                                 stars: '★★★★',  cat: 'syntax' },
  { eva: 'sheodaiin', heb: 'שְׁאוֹדִּין',       de: 'Todesurteil (Vollform)',                      stars: '★★★★★', cat: 'syntax' },
  { eva: 'daiidy',    heb: 'דִּין+דִּי',        de: 'das Urteil dessen',                           stars: '★★★★★', cat: 'syntax' },
  { eva: 'daiindy',   heb: 'דִּין+דִּי',        de: 'das Urteil dessen',                           stars: '★★★★★', cat: 'syntax' },
  { eva: 'qodaiin',   heb: 'וְדִּין',           de: 'und Urteil',                                  stars: '★★★★',  cat: 'syntax' },
  { eva: 'daiim',     heb: 'דִּין+ם',           de: 'Urteile (Plural)',                            stars: '★★★',   cat: 'syntax' },
  { eva: 'keey',      heb: 'כֵּי',              de: 'denn / weil (Kausalpartikel)',                stars: '★★★★',  cat: 'syntax' },
  { eva: 'qoky',      heb: 'וְ+כִּי',           de: 'und denn / weil',                             stars: '★★★★★', cat: 'syntax' },
  { eva: 'cthom',     heb: 'כְּ+תֹם',           de: 'wie Vollständigkeit (Kolophon)',              stars: '★★★',   cat: 'kolophon' },
  // ── Verbformen ──────────────────────────────────────
  { eva: 'taiir',     heb: 'תָּאִיר',           de: 'es wird leuchten / heilen',                   stars: '★★★★',  cat: 'verb' },
  { eva: 'yteechy',   heb: 'יִחְיֶה',           de: 'er wird gesund',                              stars: '★★★',   cat: 'verb' },
  { eva: 'yshdal',    heb: 'יְשַׁדַּל',         de: 'er wird schwächen',                           stars: '★★★',   cat: 'verb' },
  { eva: 'ykeedy',    heb: 'יְכֵּדֵי',          de: 'er wird anordnen',                            stars: '★★★',   cat: 'verb' },
  { eva: 'ykchy',     heb: 'יְ+כְּ+הִי',        de: 'er wird Blässe zeigen',                       stars: '★★★★',  cat: 'verb' },
  { eva: 'tsheoarom', heb: 'תְּשְׁאוֹרוֹם',     de: 'du wirst von Scheol aufsteigen',              stars: '★★★★',  cat: 'verb' },
  { eva: 'chkar',     heb: 'חֲקַר',             de: 'er untersucht',                               stars: '★★★',   cat: 'verb' },
  { eva: 'ydaiin',    heb: 'יְדִּין',           de: 'er urteilt',                                  stars: '★★★★',  cat: 'verb' },
  { eva: 'ysho',      heb: 'יְשׁוֹ',            de: 'es führt zum Tod',                            stars: '★★★★',  cat: 'verb' },
  { eva: 'ykeor',     heb: 'יְכְּאוֹר',         de: 'er heilt / wie Licht',                        stars: '★★★★',  cat: 'verb' },
  { eva: 'ykchaiin',  heb: 'יְ+כְּ+חַיִּין',   de: 'er wird wie Leben werden',                    stars: '★★★★',  cat: 'verb' },
  { eva: 'ykchor',    heb: 'יְ+כְּ+חֹר',        de: 'er heilt die Pupille',                        stars: '★★★★★', cat: 'verb' },
  { eva: 'ycheor',    heb: 'יְ+כְּ+אוֹר',       de: 'er wird wie Licht werden',                    stars: '★★★★',  cat: 'verb' },
  { eva: 'tchey',     heb: 'תְּחִי',            de: 'möge es/sie leben! (Jussiv)',                 stars: '★★★★',  cat: 'verb' },
  { eva: 'ychor',     heb: 'יְ+חֹר',            de: 'er wird die Pupille weiten',                  stars: '★★★★',  cat: 'verb' },
  { eva: 'yodaiin',   heb: 'יוֹדִּין',          de: 'er weiß das Urteil',                          stars: '★★★★',  cat: 'verb' },
  { eva: 'ytchody',   heb: 'יְ+תְּ+כֹּ+דִּי',  de: 'er wird urteilen (Doppelpräfix)',              stars: '★★★',   cat: 'verb' },
  { eva: 'ytaiin',    heb: 'יְ+תָּ+עַיִן',      de: 'er wird das Auge heilen',                     stars: '★★★★',  cat: 'verb' },
  { eva: 'ykoiin',    heb: 'יְכוֹיִן',          de: 'er wird sich erholen',                        stars: '★★★',   cat: 'verb' },
  // ── Akteure, Anatomie & Botanik ─────────────────────
  { eva: 'sar',       heb: 'שַׂר',              de: 'Arzt / Meister / Vorsteher',                  stars: '★★★★',  cat: 'akteur' },
  { eva: 'sary',      heb: 'שַׂרִי',            de: 'mein Arzt (Possessiv)',                       stars: '★★★',   cat: 'akteur' },
  { eva: 'pchy',      heb: 'פְּחִי',            de: 'mein Atem / mein Mund',                       stars: '★★★',   cat: 'akteur' },
  { eva: 'opchor',    heb: 'עַ+פְּ+חֹר',        de: 'auf die Pupille (Atemweg-Befund)',             stars: '★★★',   cat: 'akteur' },
  { eva: 'al',        heb: 'עַל',               de: 'auf / über / betreffend',                     stars: '★★★★',  cat: 'akteur' },
  { eva: 'ol',        heb: 'עַל',               de: 'auf / über / betreffend',                     stars: '★★★★',  cat: 'akteur' },
  { eva: 'saiin',     heb: 'שַׂעַיִן',          de: 'Augenarzt',                                   stars: '★★★★',  cat: 'akteur' },
  { eva: 'dain',      heb: 'דַּ+עַיִן',         de: 'das Auge (Kurzform)',                         stars: '★★★',   cat: 'akteur' },
  { eva: 'oiin',      heb: 'עַ+יִן',            de: 'das Auge (direkte Form)',                     stars: '★★★★',  cat: 'akteur' },
  { eva: 'doaiin',    heb: 'דְּ+עַיִן',         de: 'vom Auge',                                    stars: '★★★★',  cat: 'akteur' },
  { eva: 'doiin',     heb: 'דְּ+עַיִן',         de: 'vom Auge (Kurzform)',                         stars: '★★★★',  cat: 'akteur' },
  { eva: 'kchol',     heb: 'כְּ+חֹל',           de: 'wie Kohl-Pigment / Blaupigment',              stars: '★★★',   cat: 'akteur' },
  { eva: 'sam',       heb: 'שַׂם',              de: 'Arznei / er gibt',                            stars: '★★★',   cat: 'akteur' },
  { eva: 'shty',      heb: 'שְׁתִי',            de: 'Getränk / Trank',                             stars: '★★★',   cat: 'akteur' },
  { eva: 'pol',       heb: 'פֹּל',              de: 'Bohne / Beere',                               stars: '★★★',   cat: 'akteur' },
  { eva: 'otoaiin',   heb: 'עַתוֹעַיִן',        de: 'auf seine Augen',                             stars: '★★★',   cat: 'akteur' },
  { eva: 'chokeos',   heb: 'כֹּכֵּאוֹס',        de: 'wie ein Kelch (Botanik)',                     stars: '★★★',   cat: 'akteur' },
  // ── Bestätigte Komposita ────────────────────────────
  { eva: 'qokedam',   heb: 'וְ+כְּ+דָּם',       de: 'und wie das Blut',                            stars: '★★★★',  cat: 'kompositum' },
  { eva: 'okoldm',    heb: 'עַל+כֹּל+דָּם',     de: 'über alles Blut',                             stars: '★★★★',  cat: 'kompositum' },
  { eva: 'pchedal',   heb: 'פְּ+כֶּ+דַּל',      de: 'bei dem Schwachen',                           stars: '★★★',   cat: 'kompositum' },
  { eva: 'cholar',    heb: 'כֹּ+לוֹ+ר',         de: 'alles sein Licht',                            stars: '★★★',   cat: 'kompositum' },
  { eva: 'qokchor',   heb: 'וְ+עַ+כְּ+חֹר',     de: 'und für die Pupille',                         stars: '★★★★★', cat: 'kompositum' },
  { eva: 'shydal',    heb: 'שֵׁי+דַּל',         de: 'die Gabe der Schwäche',                       stars: '★★★',   cat: 'kompositum' },
  // ── Possessiv-Formen ────────────────────────────────
  { eva: 'olsho',     heb: 'שׁוֹ+לוֹ',          de: 'sein Scheol (Possessiv)',                     stars: '★★★',   cat: 'possessiv' },
];
