// Confirmed lexicon with entries ★★★+
export const LEXICON = [
  // ── Medizinische Nomina & Symptome ──────────────────
  { eva: 'dam',       heb: 'דָּם',        de: 'Blut',                                        stars: '★★★★★', cat: 'symptom' },
  { eva: 'dal',       heb: 'דַּל',        de: 'schwach / abgemagert',                        stars: '★★★★',  cat: 'symptom' },
  { eva: 'daly',      heb: 'דַּלִּי',       de: 'seine/meine Schwäche (Possessiv)',             stars: '★★★★',  cat: 'symptom' },
  { eva: 'ckhy',      heb: 'כְּהִי',       de: 'Blässe / Trübheit',                           stars: '★★★★',  cat: 'symptom' },
  { eva: 'okaiin',    heb: 'עַכְּעַיִן',     de: 'auf das Auge',                                stars: '★★★★',  cat: 'symptom' },
  { eva: 'qokaiin',   heb: 'וְכְּעַיִן',     de: 'und gemäß dem Auge',                          stars: '★★★★',  cat: 'symptom' },
  { eva: 'qotal',     heb: 'וְטַל',       de: 'Tau / Schweißzeichen',                        stars: '★★★',   cat: 'symptom' },
  { eva: 'ram',       heb: 'רָם',        de: 'erhöht / Fieber',                             stars: '★★★',   cat: 'symptom' },
  { eva: 'chor',      heb: 'חֹר',        de: 'Pupille / Höhle',                             stars: '★★★★',  cat: 'symptom' },
  { eva: 'otchor',    heb: 'אוֹת+חֹר',    de: 'das Zeichen der Pupille',                     stars: '★★★★',  cat: 'symptom' },
  { eva: 'oraiin',    heb: 'אוֹר+עַיִן',   de: 'Licht des Auges / Augenheilung — R43 erfüllt: f22r + f26v P.4 (reichste Augenlicht-Kolophonformel im Corpus: or·cheos·oraiin·okeo·chekaiin=)',  stars: '★★★★',  cat: 'symptom' },
  { eva: 'sheoldam',  heb: 'שְׁאוֹל+דָּם',   de: 'tödlicher Blutverlust',                       stars: '★★★★★', cat: 'symptom' },
  { eva: 'damo',      heb: 'דָּמוֹ',       de: 'sein Blut (Possessiv)',                       stars: '★★★★',  cat: 'symptom' },
  { eva: 'cham',      heb: 'חַם',        de: 'Wärme / Entzündung / hippokratischer Befund-Term (f69r P.2 als kosmologischer Register-Beleg: Fieber-Diagnose im Rad-Diagramm)',                          stars: '★★★',   cat: 'symptom' },
  { eva: 'torshor',   heb: 'תֹּר+שׁוֹר',    de: 'Jahreszeit-Zeichen / saisonaler Eintrag',     stars: '★★★',   cat: 'symptom' },
  { eva: 'dchm',      heb: 'דְּ+חָם',      de: 'von der Entzündung',                          stars: '★★★',   cat: 'symptom' },
  { eva: 'dalor',     heb: 'דַּלאוֹר',     de: 'schwaches Augenlicht',                        stars: '★★★',   cat: 'symptom' },
  { eva: 'char',      heb: 'חַר',        de: 'heiß / Fieber',                               stars: '★★★★',  cat: 'symptom' },
  { eva: 'chary',     heb: 'חַרִי',       de: 'sein Fieber (Possessiv)',                     stars: '★★★',   cat: 'symptom' },
  { eva: 'ckhal',     heb: 'כְּהַל',       de: 'Nachlassen des Fiebers',                      stars: '★★★',   cat: 'symptom' },
  { eva: 'dol',       heb: 'דָּוֶה',       de: 'Schmerz / Krankheit',                         stars: '★★★',   cat: 'symptom',  part: 'FOLIUM' },
  { eva: 'odol',      heb: 'עַ+דָּוֶה',     de: 'auf die Krankheit (o+dol)',                   stars: '★★★★',  cat: 'symptom' },
  { eva: 'dolar',     heb: 'דָּוֶה+לְאוֹר',  de: 'Krankheit zur Heilung',                       stars: '★★★',   cat: 'symptom' },
  { eva: 'shees',     heb: 'אֵשׁ',         de: 'Feuer / Fieberbrand',                         stars: '★★★',   cat: 'symptom' },
  { eva: 'shorodo',   heb: 'שׁוֹר+עוֹדוֹ',  de: 'das Zeichen besteht fort',                    stars: '★★★',   cat: 'symptom' },
  { eva: 'oeees',     heb: 'עַ+אֵשׁ',       de: 'auf dem Feuer/Fieber',                        stars: '★★★',   cat: 'symptom' },
  { eva: 'octhos',    heb: 'עַ+כְּ+תֹ+שׁ',    de: 'auf wie Feuer/Fieber',                        stars: '★★★',   cat: 'symptom' },
  // ── Prognose-Termini ────────────────────────────────
  { eva: 'or',        heb: 'אוֹר',        de: 'Licht / Heilung',                             stars: '★★★★',  cat: 'prognose' },
  { eva: 'sheol',     heb: 'שְׁאוֹל',       de: 'Scheol / Tod',                                stars: '★★★★',  cat: 'prognose' },
  { eva: 'shol',      heb: 'שׁוֹל',        de: 'Tod (apokor. Spr. A)',                        stars: '★★★★★', cat: 'prognose' },
  { eva: 'daiin',     heb: 'דִּין',        de: 'Urteil / Prognose',                           stars: '★★★★',  cat: 'prognose' },
  { eva: 'chalal',    heb: 'חָלָל',        de: 'Sterbender',                                  stars: '★★★★',  cat: 'prognose' },
  { eva: 'chodl',     heb: 'חֹדֵל',        de: 'der Aufhörende / der Sterbende',              stars: '★★★',   cat: 'prognose' },
  { eva: 'dair',      heb: 'דְּ+אִיר',      de: 'der Leuchtende / Licht davon',                stars: '★★★',   cat: 'prognose' },
  { eva: 'aiin',      heb: 'אַיִן',        de: 'nichts / nicht vorhanden',                    stars: '★★★',   cat: 'prognose' },
  { eva: 'eeor',      heb: 'אֵאוֹר',       de: 'kein Licht',                                  stars: '★★★',   cat: 'prognose' },
  { eva: 'lor',       heb: 'לְאוֹר',       de: 'zum Licht / zur Heilung',                     stars: '★★★★★', cat: 'prognose' },
  { eva: 'lshol',     heb: 'לְשׁוֹל',       de: 'zum Tod / zu Scheol',                         stars: '★★★★★', cat: 'prognose' },
  { eva: 'chaiin',    heb: 'חַיִּין',       de: 'Leben (Chayyim)',                             stars: '★★★★',  cat: 'prognose' },
  { eva: 'sheey',     heb: 'שֵׁי',         de: 'Gabe / Wohlbefinden — THERAPEUTISCH-ALLGEMEIN (v8.4): erscheint sowohl in FLOS (f013r) als auch CAULIS (f002r P.8–P.9); kein reiner FLOS-Term',  stars: '★★★',   cat: 'prognose' },
  { eva: 'cheor',     heb: 'כְּאוֹר',       de: 'wie Licht (Heilungszeichen)',                 stars: '★★★★',  cat: 'prognose' },
  { eva: 'otshol',    heb: 'אוֹתשׁוֹל',     de: 'das Zeichen des Todes',                       stars: '★★★★★', cat: 'prognose' },
  { eva: 'chan',      heb: 'חָן',         de: 'Gnade / günstige Prognose',                   stars: '★★★★',  cat: 'prognose' },
  { eva: 'dom',       heb: 'דּוֹם',        de: 'Stille / Ende',                               stars: '★★★★',  cat: 'prognose' },
  { eva: 'dsholdy',   heb: 'דְּ+שׁוֹל+דִּי',   de: 'von Scheol — dessen (Genitiv)',               stars: '★★★★★', cat: 'prognose' },
  { eva: 'dsho',      heb: 'דְּ+שׁוֹ',       de: 'von Scheol (Kurzform)',                       stars: '★★★★',  cat: 'prognose' },
  { eva: 'shoiin',    heb: 'שׁוֹ+עַיִן',     de: 'Scheol des Auges',                            stars: '★★★★',  cat: 'prognose' },
  { eva: 'shoin',     heb: 'שׁוֹ+יִן',      de: 'Scheol des Auges (Var. von shoiin; abw. Transkription)', stars: '★★',    cat: 'prognose' },
  { eva: 'darchor',   heb: 'דַּרְכּוֹר',      de: 'sein Krankheitsverlauf',                      stars: '★★★',   cat: 'prognose' },
  { eva: 'otan',      heb: 'עֹתָן',        de: 'Zeit / Jahreszeit der Erkrankung',            stars: '★★★',   cat: 'prognose' },
  { eva: 'kaiim',     heb: 'קַיָּם',        de: 'gültig / beständig (Schlussformel)',          stars: '★★★★★', cat: 'kolophon' },
  { eva: 'okorory',   heb: 'עַכְּאוֹראוֹרִי',  de: 'auf das Licht — mein Licht / zum Licht',     stars: '★★★',   cat: 'kolophon' },
  { eva: 'cphar',     heb: 'כְּ+פַּר',       de: 'Sühne / Bedeckung (Kolophon-Formel)',         stars: '★★★',   cat: 'kolophon' },
  // ── Syntaktische Konnektoren ────────────────────────
  { eva: 'chedy',     heb: 'כְּדֵי',         de: 'damit / um zu (Var.: kedy)',                   stars: '★★★★',  cat: 'syntax' },
  { eva: 'shedy',     heb: 'שֶׁדִּי',        de: 'das/welches von',                             stars: '★★★★',  cat: 'syntax' },
  { eva: 'shdy',      heb: 'שֶׁדִּי',         de: 'das/welches von (Kurz)',                      stars: '★★★★',  cat: 'syntax' },
  { eva: 'dy',        heb: 'דִּי',          de: 'von / dessen (Aram.)',                        stars: '★★',    cat: 'syntax' },
  { eva: 'lchedy',    heb: 'לְכְּדֵי',        de: 'um zu / bis zur Grenze',                      stars: '★★★★',  cat: 'syntax' },
  { eva: 'chal',      heb: 'חָל',           de: 'gilt für / betrifft',                         stars: '★★★',   cat: 'syntax' },
  { eva: 'shodaiin',  heb: 'שׁוֹדִּין',         de: 'Todesurteil',                                 stars: '★★★★',  cat: 'syntax' },
  { eva: 'sheodaiin', heb: 'שְׁאוֹדִּין',       de: 'Todesurteil (Vollform)',                      stars: '★★★★★', cat: 'syntax' },
  { eva: 'daiindy',   heb: 'דִּין+דִּי',        de: 'das Urteil dessen (Var.: daiidy)',             stars: '★★★★★', cat: 'syntax' },
  { eva: 'qodaiin',   heb: 'וְדִּין',           de: 'und Urteil',                                  stars: '★★★★',  cat: 'syntax' },
  { eva: 'daiim',     heb: 'דִּין+ם',           de: 'Urteile (Plural)',                            stars: '★★★',   cat: 'syntax' },
  { eva: 'keey',      heb: 'כֵּי',              de: 'denn / weil (Kausalpartikel)',                stars: '★★★★',  cat: 'syntax' },
  { eva: 'qoky',      heb: 'וְ+כִּי',           de: 'und denn / weil',                             stars: '★★★★★', cat: 'syntax' },
  { eva: 'cthom',     heb: 'כְּ+תֹם',           de: 'wie Vollständigkeit (Kolophon; Vokalvar.: chetom)', stars: '★★★',   cat: 'kolophon' },
  // ── Verbformen ──────────────────────────────────────
  { eva: 'taiir',     heb: 'תָּאִיר',           de: 'es wird leuchten / heilen',                   stars: '★★★★',  cat: 'verb' },
  { eva: 'yteechy',   heb: 'יִחְיֶה',           de: 'er wird gesund',                              stars: '★★★',   cat: 'verb' },
  { eva: 'yshdal',    heb: 'יְשַׁדַּל',         de: 'er wird schwächen',                           stars: '★★★',   cat: 'verb' },
  { eva: 'ykeedy',    heb: 'יְכֵּדֵי',          de: 'er wird anordnen',                            stars: '★★★',   cat: 'verb' },
  { eva: 'ykchy',     heb: 'יְ+כְּ+הִי',        de: 'er wird Blässe zeigen',                       stars: '★★★★',  cat: 'verb' },
  { eva: 'tsheoarom', heb: 'תְּשְׁאוֹרוֹם',     de: 'du wirst von Scheol aufsteigen',              stars: '★★★★',  cat: 'verb' },
  { eva: 'chkar',     heb: 'חֲקַר',             de: 'er untersucht',                               stars: '★★★',   cat: 'verb' },
  { eva: 'ydaiin',    heb: 'יְדִּין',           de: 'er urteilt',                                  stars: '★★★★',  cat: 'verb' },
  { eva: 'ysho',      heb: 'יְשׁוֹ',            de: 'es führt zum Tod',                            stars: '★★★★',  cat: 'verb' },
  { eva: 'ykeor',     heb: 'יְכְּאוֹר',         de: 'er heilt / wie Licht',                        stars: '★★★★',  cat: 'verb' },
  { eva: 'ykchaiin',  heb: 'יְ+כְּ+חַיִּין',   de: 'er wird wie Leben werden',                    stars: '★★★★',  cat: 'verb' },
  { eva: 'ykchor',    heb: 'יְ+כְּ+חֹר',        de: 'er heilt die Pupille',                        stars: '★★★★★', cat: 'verb' },
  { eva: 'ycheor',    heb: 'יְ+כְּ+אוֹר',       de: 'er wird wie Licht werden',                    stars: '★★★★',  cat: 'verb' },
  { eva: 'tchey',     heb: 'תְּחִי',            de: 'möge es/sie leben! (Jussiv)',                 stars: '★★★★',  cat: 'verb' },
  { eva: 'ychor',     heb: 'יְ+חֹר',            de: 'er wird die Pupille weiten',                  stars: '★★★★',  cat: 'verb' },
  { eva: 'yodaiin',   heb: 'יוֹדִּין',          de: 'er weiß das Urteil',                          stars: '★★★★',  cat: 'verb' },
  { eva: 'ytchody',   heb: 'יְ+תְּ+כֹּ+דִּי',  de: 'er wird urteilen (Doppelpräfix)',              stars: '★★★',   cat: 'verb' },
  { eva: 'ytaiin',    heb: 'יְ+תָּ+עַיִן',      de: 'er wird das Auge heilen',                     stars: '★★★★',  cat: 'verb' },
  { eva: 'ykoiin',    heb: 'יְכוֹיִן',          de: 'er wird sich erholen',                        stars: '★★★',   cat: 'verb' },
  // ── Akteure, Anatomie & Botanik ─────────────────────
  { eva: 'sar',       heb: 'שַׂר',              de: 'Arzt / Meister / Vorsteher',                  stars: '★★★★',  cat: 'akteur' },
  { eva: 'sary',      heb: 'שַׂרִי',            de: 'mein Arzt / Apotheker (Possessiv) — Cross-Register ★★★★★: FLOS-Eröffner f009r P.1 (Bistorta-Ähre) + f57r + f103r + f77r; Arzt verschreibt den FLOS-Teil',  stars: '★★★★★', cat: 'akteur' },
  { eva: 'pchy',      heb: 'פְּחִי',            de: 'mein Atem / mein Mund',                       stars: '★★★★',  cat: 'akteur',  part: 'FLOS/FRUCTUS' },
  { eva: 'opchor',    heb: 'עַ+פְּ+חֹר',        de: 'auf die Pupille (Atemweg-Befund)',             stars: '★★★',   cat: 'akteur' },
  { eva: 'al',        heb: 'עַל',               de: 'auf / über / betreffend (Var.: ol)',           stars: '★★★★',  cat: 'akteur' },
  { eva: 'saiin',     heb: 'שַׂעַיִן',          de: 'Augenarzt',                                   stars: '★★★★',  cat: 'akteur' },
  { eva: 'dain',      heb: 'דַּ+עַיִן',         de: 'das Auge (Kurzform)',                         stars: '★★★',   cat: 'akteur' },
  { eva: 'oiin',      heb: 'עַ+יִן',            de: 'das Auge (direkte Form)',                     stars: '★★★★',  cat: 'akteur' },
  { eva: 'doaiin',    heb: 'דְּ+עַיִן',         de: 'vom Auge (Var.: doiin)',                       stars: '★★★★',  cat: 'akteur' },
  { eva: 'kchol',     heb: 'כְּ+חֹל',           de: 'wie Augensalbe / Kohl-Pigment (Blaupigment)', stars: '★★★',   cat: 'akteur' },
  { eva: 'sam',       heb: 'שַׂם',              de: 'Arznei / er gibt',                            stars: '★★★',   cat: 'akteur' },
  { eva: 'shty',      heb: 'שְׁתִי',            de: 'Getränk / Trank',                             stars: '★★★',   cat: 'akteur' },
  { eva: 'pol',       heb: 'פֹּל',              de: 'Bohne / Beere / Frucht',                      stars: '★★★',   cat: 'akteur',  part: 'FRUCTUS' },
  { eva: 'otoaiin',   heb: 'עַתוֹעַיִן',        de: 'auf seine Augen',                             stars: '★★★',   cat: 'akteur' },
  { eva: 'chokeos',   heb: 'כֹּכֵּאוֹס',        de: 'wie ein Kelch (Botanik)',                     stars: '★★★',   cat: 'akteur' },
  // ── Bestätigte Komposita ────────────────────────────
  { eva: 'qokedam',   heb: 'וְ+כְּ+דָּם',       de: 'und wie das Blut',                            stars: '★★★★',  cat: 'kompositum' },
  { eva: 'okoldm',    heb: 'עַל+כֹּל+דָּם',     de: 'über alles Blut',                             stars: '★★★★',  cat: 'kompositum' },
  { eva: 'pchedal',   heb: 'פְּ+כֶּ+דַּל',      de: 'bei dem Schwachen',                           stars: '★★★',   cat: 'kompositum' },
  { eva: 'cholar',    heb: 'כֹּ+לוֹ+ר',         de: 'alles sein Licht',                            stars: '★★★',   cat: 'kompositum' },
  { eva: 'qokchor',   heb: 'וְ+עַ+כְּ+חֹר',     de: 'und für die Pupille',                         stars: '★★★★★', cat: 'kompositum' },
  { eva: 'shydal',    heb: 'שֵׁי+דַּל',         de: 'die Gabe der Schwäche',                       stars: '★★★',   cat: 'kompositum' },
  // ── Possessiv-Formen ────────────────────────────────
  { eva: 'olsho',     heb: 'שׁוֹ+לוֹ',          de: 'sein Scheol (Possessiv)',                     stars: '★★★',   cat: 'possessiv' },
  // ── v5.6 (f14r + f14v) ────────────────
  { eva: 'pcho',      heb: 'פְּחֹ',             de: 'Atem/Mund (Spr.-A-Variante von pchy)',         stars: '★★★',   cat: 'akteur' },
  { eva: 'chok',      heb: 'חֹק',               de: 'Vorschrift / ärztliche Anordnung / Rezept',    stars: '★★★',   cat: 'symptom' },
  { eva: 'choky',     heb: 'חֹקֵּי',            de: 'die Vorschriften des [Falls] (Konstr.-Plural)',stars: '★★★',   cat: 'symptom' },
  { eva: 'chokshor',  heb: 'כְּ+חֹק+שׁוֹר',    de: 'wie die Vorschrift des Zeichens',              stars: '★★★★',  cat: 'kompositum' },
  { eva: 'ykaiin',    heb: 'יְ+כְּ+עַיִן',      de: 'er heilt das Auge (5. y+k+Terminus-Verb)',     stars: '★★★★',  cat: 'verb' },
  { eva: 'yfodain',   heb: 'יְ+פָּדָה+יִן',     de: 'er wird das Auge erlösen/befreien',            stars: '★★★★',  cat: 'verb' },
  { eva: 'ydain',     heb: 'יְ+דַ+יִן',         de: 'er wird das Auge behandeln',                  stars: '★★★★',  cat: 'verb' },
  { eva: 'ypchor',    heb: 'יְ+פְּ+חֹר',        de: 'er heilt die Pupille [durch Atem]',            stars: '★★★',   cat: 'verb' },
  { eva: 'teor',      heb: 'תְּ+אוֹר',          de: 'sie wird heilen (fem. Imperfekt von or)',       stars: '★★★★',  cat: 'verb' },
  { eva: 'qotchor',   heb: 'קוֹ+תְּ+כֹּר',       de: 'Pupillen-Zeichen / Urteil der Pupille (Schlusskolophon f15r)', stars: '★★★★★', cat: 'kompositum' },
  { eva: 'otcho',     heb: 'אוֹת+כֹּ',          de: 'das Zeichen des [Atems] (Kolophon-Kurzform)',  stars: '★★★',   cat: 'kolophon' },
  { eva: 'otchy',     heb: 'אוֹת+כְּ+הִי',      de: 'das Zeichen der Blässe',                       stars: '★★★★',  cat: 'symptom' },
  { eva: 'dchckhy',   heb: 'דְּ+כְּ+כְּ+הִי',  de: 'von tiefer Blässe (Intensiv-Diagnosesiegel)',  stars: '★★★★',  cat: 'kolophon' },
  { eva: 'chey',      heb: 'חֵי',               de: 'lebendig / am Leben (Adj.)',                   stars: '★★★',   cat: 'prognose', part: 'FLOS' },
  { eva: 'oeeen',     heb: 'עַ+אֵין',           de: 'auf das Fehlen / Nichts (emphatic null)',       stars: '★★★',   cat: 'prognose' },
  { eva: 'oir',       heb: 'עַ+אוֹר',           de: 'auf das Licht / Direktional-Heilung',          stars: '★★★',   cat: 'prognose' },
  { eva: 'choor',     heb: 'כְּ+אוּר',          de: 'wie das Licht (lang-vokalisierte Variante)',   stars: '★★★',   cat: 'prognose' },
  { eva: 'ksho',      heb: 'כְּ+שׁוֹ',          de: 'wie Scheol/Tod (Komparativform)',              stars: '★★★',   cat: 'prognose' },
  { eva: 'schol',     heb: 'שׂ+כֹּל',           de: 'Arznei für alles / Universalheilmittel',       stars: '★★★',   cat: 'akteur' },
  { eva: 'dala',      heb: 'דַּלָּ',            de: 'Schwäche (fem., Femininum von dal)',            stars: '★★★',   cat: 'symptom' },
  { eva: 'koiin',     heb: 'כֹּ+עַיִן',         de: 'wie das Auge (komparativ, kol-Stamm)',         stars: '★★★',   cat: 'akteur' },
  { eva: 'kaiin',     heb: 'כְּ+עַיִן',         de: 'wie das Auge (komparativ, k-Präfix; Var.: keaiin)', stars: '★★★',   cat: 'akteur' },
  { eva: 'okshy',     heb: 'עַ+כְּ+שֵׁי',       de: 'auf/für die Gabe (therapeutischer Direktional)',stars: '★★★',  cat: 'akteur' },
  { eva: 'cthor',     heb: 'כְּ+תֹּר',          de: 'vollständige Heilung',                         stars: '★★★',   cat: 'verb' },
  { eva: 'dshy',      heb: 'דְּ+שֵׁי',          de: 'von der Gabe (d-Genitivkonstrukt)',            stars: '★★★',   cat: 'kompositum' },
  // ── v5.8 (f16r + f16v) ────────────────
  // f16r
  { eva: 'tchor',     heb: 'תְּ+חֹר',           de: 'sie heilt die Pupille (fem. Imperfekt) — Zweitbeleg f29v P.8 → ★★★★ bestätigt',        stars: '★★★★',  cat: 'verb' },
  { eva: 'ykair',     heb: 'יְ+כְּ+אִיר',        de: 'er heilt leuchtend (Kandidat 7. y+k+Terminus) — R43 provisorisch ★★: nur f16r (1×), unter Mindestgrenze 8×', stars: '★★',    cat: 'verb' },
  { eva: 'pocheody',  heb: 'פְּ+חֹ+דִּי',        de: 'des Atemwegs (Genitiv von pcho)',              stars: '★★★',   cat: 'akteur' },
  { eva: 'toror',     heb: 'תְּ+אוֹר+אוֹר',      de: 'sie heilt — Licht — Licht (Doppel-Licht-Heilung)', stars: '★★★', cat: 'verb' },
  { eva: 'daly·dal',  heb: 'דַּלִּי+דַּל',       de: 'seine Schwäche — schwach (R19 Dopplung ×2)',   stars: '★★★★',  cat: 'symptom' },
  { eva: 'dalchy',    heb: 'דַּל+כְּהִי',        de: 'die Schwäche der Blässe',                      stars: '★★★★',  cat: 'symptom' },
  { eva: 'dainod',    heb: 'דַּ+אִין+עֹד',       de: 'er behandelt das Auge weiter',                 stars: '★★★',   cat: 'verb' },
  { eva: 'shody',     heb: 'שְׁאוֹ+דִּי',        de: 'von Scheol — dessen (Genitiv)',                stars: '★★★',   cat: 'prognose' },
  { eva: 'otly',      heb: 'אוֹת+לֵ',            de: 'Zeichen zu/für (oto-Direktional)',             stars: '★★★',   cat: 'kompositum' },
  { eva: 'opchy',     heb: 'עַ+פְּ+הִי',         de: 'auf den Atemweg (o+pchy-Direktional)',         stars: '★★★★',  cat: 'akteur',  part: 'FLOS/FRUCTUS' },
  // f16v
  { eva: 'ytchor',    heb: 'יְ+תְּ+חֹר',         de: 'er/sie wird die Pupille heilen (y+t-Doppelpräfix) — R43 erfüllt: f16v P.2 + f29v P.2 = 2 Folios → ★★★★', stars: '★★★★', cat: 'verb' },
  { eva: 'ytchy',     heb: 'יְ+תְּ+כְּהִי',      de: 'er/sie wird Blässe zeigen (y+t-Doppelpräfix)', stars: '★★★',  cat: 'verb' },
  { eva: 'pchraiin',  heb: 'פְּ+רְ+עַיִן',       de: 'für/bei das Licht des Auges',                 stars: '★★★',   cat: 'akteur' },
  { eva: 'sholo',     heb: 'שְׁאוֹ+לוֹ',         de: 'Scheol für ihn (Dativ-Form)',                  stars: '★★★',   cat: 'prognose' },
  { eva: 'otor',      heb: 'אוֹת+אוֹר',          de: 'Zeichen des Lichts / der Heilung — R43 erfüllt: f16v + f21r P.8 (2 Folios)', stars: '★★★',   cat: 'kompositum' },
  { eva: 'otain',     heb: 'אוֹת+אַיִן',         de: 'Zeichen des Nichts / Endes',                   stars: '★★★',   cat: 'kompositum' },
  { eva: 'okytaiin',  heb: 'עַ+כְּ+תָּ+עַיִן',   de: 'auf die Weise, dass er das Auge heilt',        stars: '★★★',   cat: 'verb' },
  { eva: 'dairin',    heb: 'דְּ+אִיר+יִן',       de: 'von dem Leuchtenden (Genitiv-Form)',           stars: '★★★',   cat: 'prognose' },
  { eva: 'sokar',     heb: 'שׂ+אוֹ+כְּ+אָר',     de: 'Heilungs-Arzt des Lichts (Quire-B-Kolophon)',  stars: '★★★',   cat: 'kolophon' },
  { eva: 'oaorar',    heb: 'עַ+אַ+אוֹר+אָר',     de: 'auf das Licht der Heilung (Doppel-Licht-Formel)', stars: '★★★★', cat: 'kolophon' },
  { eva: 'dan',       heb: 'דָּן',               de: 'er hat geurteilt (Qal Perfekt)',               stars: '★★★',   cat: 'verb' },
  { eva: 'koshet',    heb: 'כֹּ+שֵׁ+תְּ',        de: 'Scheol-Vollständigkeit (temporaler Abschlussterm)', stars: '★★', cat: 'prognose' },
  // ── v5.9 (f1r — Eröffnungsfolio, Haskama) ────────────
  { eva: 'shodain',  heb: 'שׁוֹד+דַּ+עַיִן',   de: 'Zerstörung des Auges (schärfste negative Augenprognose)', stars: '★★★★', cat: 'kompositum' },
  { eva: 'shoaiin',  heb: 'שְׁאוֹל+עַיִן',      de: 'Scheol des Auges (Todesurteil für das Sehorgan)',        stars: '★★★★', cat: 'prognose'   },
  { eva: 'kchom',    heb: 'כְּ+חֹם',            de: 'wie Hitze / wie Fieber (Temperatur-Komparativ) — R43 Kand.-Flag: f001r (2×, 1 Folio), nächste 5 Folios prüfen',  stars: '★★★',  cat: 'symptom'    },
  { eva: 'oksho',    heb: 'עַ+כְּ+שׁוֹ',        de: 'auf/gegen Scheol (erste präpositionale Scheol-Form Spr. A)', stars: '★★★★', cat: 'prognose' },
  { eva: 'dydyd',    heb: 'דִּי+דִּי+דִּי',     de: 'dreifacher Relativpartikel — extremer Betonungsmodus',  stars: '★★★',  cat: 'syntax'     },
  // ── v6.0 (f17r + f17v — Quire C Eröffnung) ───────────
  // f17r
  { eva: 'chom',      heb: 'חֹם',               de: 'Wärme / Hitze (eigenständige Form, Schwesterform von cham)',    stars: '★★★',  cat: 'symptom'    },
  { eva: 'fshody',    heb: 'פְּ+שׁוֹ+דִּי',     de: 'von Scheol — dessen (Pe-Genitiv-Scheol-Konstrukt)',              stars: '★★★',  cat: 'prognose'   },
  { eva: 'oldckhy',   heb: 'עַל+דְּ+כְּ+הִי',  de: 'über die Blässe davon (dreifach-präpositionaler Terminus)',      stars: '★★★',  cat: 'symptom'    },
  { eva: 'qokcheor',  heb: 'וְ+כְּ+כְּ+אֵוֹר', de: 'und wie das Licht (doppelter k-Komparativ + Vav)',               stars: '★★★',  cat: 'kompositum' },
  { eva: 'dor',       heb: 'דֹּר',              de: 'Generation / Wachstumszyklus / Zeitraum der Erkrankung — R43 bestätigt: f17r + f27r P.5 = 2 Folios',                          stars: '★★★',  cat: 'symptom'    },
  { eva: 'otchol',    heb: 'אוֹת+כֹּל',         de: 'Zeichen von allem / Universalzeichen',                          stars: '★★★',  cat: 'kompositum' },
  { eva: 'cphor',     heb: 'כְּ+פְּ+אֹר',       de: 'wie der Mund des Lichts',                                       stars: '★★',   cat: 'kompositum' },
  { eva: 'ychody',    heb: 'יְ+כֹּ+דִּי',       de: 'er wird urteilen (Variante von ytchody)',                       stars: '★★★',  cat: 'verb'       },
  { eva: 'tsho',      heb: 'תְּ+שׁוֹ',          de: 'sie entfernt sich von Scheol (fem. Impf. + Scheol-Kurzform)',   stars: '★★★',  cat: 'verb'       },
  { eva: 'opydaiin',  heb: 'עַ+פִּי+דִּין',     de: 'bei/beim Urteil des Mundes (Atemweg-Urteil-Verbund)',           stars: '★★★',  cat: 'kompositum' },
  // f17v
  { eva: 'pchodol',   heb: 'פְּחֹ+דֹּל',         de: 'Atemweg der Krankheit / Mundschmerz (pcho + dol)',             stars: '★★★',  cat: 'symptom'    },
  { eva: 'qopchaiin', heb: 'וְ+פְּ+כְּ+עַיִן',  de: 'und Atemweg des Auges (Atemweg-Auge-Verbund)',                 stars: '★★★',  cat: 'kompositum' },
  { eva: 'sholor',    heb: 'שׁוֹל+אֹר',          de: 'Scheol-Licht (Todes-Licht-Kompositum, Kandidat)',              stars: '★★',   cat: 'prognose'   },
  { eva: 'okeor',     heb: 'עַ+כְּ+אֵוֹר',       de: 'auf/zu dem Licht hin (direktionale Variante)',                 stars: '★★★',  cat: 'prognose'   },
  { eva: 'ycheol',    heb: 'יְ+כְּ+אֵוֹל',       de: 'er wird wie Scheol-Licht sein (ambivalente Verbform)',         stars: '★★',   cat: 'verb'       },
  { eva: 'chol·chol', heb: 'כֹּל·כֹּל',          de: 'alles-alles (R19 Intensivierungsdopplung, Nominalstamm)',      stars: '★★★',  cat: 'syntax'     },
  { eva: 'sheor',     heb: 'שֶׁ+אֹר',            de: 'das/welches Licht ist (Relativpartikel + Licht)',              stars: '★★★',  cat: 'syntax'     },
  { eva: 'odaldy',    heb: 'עַ+דַּל+דִּי',       de: 'über die Schwäche dessen (o-Direktional + dal + Genitiv)',     stars: '★★★',  cat: 'kompositum' },
  { eva: 'chkeey',    heb: 'כְּ+כְּ+אֵ+יִ',      de: 'wie wie Lebendigkeit (doppelter Lebens-Komparativ)',           stars: '★★★',  cat: 'kolophon'   },
  { eva: 'oekor',     heb: 'עַ+אֵ+קֹר',          de: 'auf die Kälte / das Uprooting (direktional)',                  stars: '★★',   cat: 'symptom'    },
  { eva: 'okeom',     heb: 'עַ+כְּ+אֵוֹם',       de: 'auf die Vollendung hin (Kolophon-Direktional)',                stars: '★★★',  cat: 'kolophon'   },
  // ── v6.1 (f18r + f18v — Bifolio bC2) ────────────────
  // f18r — Centaurea montana (Berg-Flockenblume)
  { eva: 'ytchar',    heb: 'יְ+תְּ+חַר',         de: 'er/sie wird Fieber zeigen (y+t-Doppelpräfix + char)',          stars: '★★★',  cat: 'verb'       },
  { eva: 'ykchol',    heb: 'יְ+כֹּל / יְ+כָּ+חֹל', de: 'er heilt alles / er heilt Augenpigment',                    stars: '★★★',  cat: 'verb'       },
  { eva: 'cthaiin',   heb: 'כְּ+תַּ+עַיִן',       de: 'vollständige Augen-Heilung (cthor-Variante + Auge-Suffix)',   stars: '★★★',  cat: 'verb'       },
  { eva: 'cthal',     heb: 'כְּ+תַּ+חַל',         de: 'wie vollständig (Kolophon-Variante von cthor)',               stars: '★★★',  cat: 'kolophon'   },
  { eva: 'chckhy',    heb: 'חֶ+כָּ+הִי',          de: 'Blässe-Hitze-Zeichen (Kompositum: char+ckhy)',                stars: '★★★',  cat: 'symptom'    },
  { eva: 'okain',     heb: 'עַ+כְּ+עַיִן',        de: 'auf das Auge (Kurzform von okaiin)',                          stars: '★★★',  cat: 'akteur'     },
  { eva: 'doldaiin',  heb: 'דּוֹל+דִּין',         de: 'Krankheits-Urteil (analog zu shodaiin = Todesurteil)',        stars: '★★★',  cat: 'syntax'     },
  { eva: 'doldy',     heb: 'דּוֹל+דִּי',          de: 'von der Krankheit davon (dol + Genitivpartikel)',             stars: '★★★',  cat: 'syntax'     },
  { eva: 'dary',      heb: 'דַּרִי',              de: 'mein Leuchtendes / mein Licht (Possessiv von dar)',           stars: '★★★',  cat: 'prognose'   },
  { eva: 'sotchaiin', heb: 'שׁ+אוֹת+כְּ+עַיִן',  de: 'das Zeichen dem Auge gleich (sho+otchor+aiin-Kompositum)',   stars: '★★★',  cat: 'kompositum' },
  { eva: 'chokchy',   heb: 'חֹק+כְּ+הִי',         de: 'Vorschrift der Blässe (chok + ckhy-Kompositum) — ★★★★ Kand. (Erstbeleg f30v P.7, H/C/F vollständig einig)',  stars: '★★★★', cat: 'symptom'    },
  { eva: 'chekhol',   heb: 'כְּ+כָּ+חֹל',         de: 'wie das Augenpigment (doppelter Komparativ)',                 stars: '★★★',  cat: 'akteur'     },
  { eva: 'ychair',    heb: 'יְ+חַ+אִיר',          de: 'er wird durch Wärme leuchten (Heilungsverb mit char-Stamm)',  stars: '★★★',  cat: 'verb'       },
  { eva: 'ychekchy',  heb: 'יְ+כְּ+כְּ+הִי',      de: 'er heilt wie totale Blässe (doppelter k-Komparativ)',         stars: '★★★',  cat: 'verb'       },
  { eva: 'kchaiin',   heb: 'כְּ+חַ+עַיִן',        de: 'wie die Wärme des Auges (Siman-Formel)',                      stars: '★★★',  cat: 'kompositum' },
  { eva: 'okal',      heb: 'עַ+כָּל',             de: 'auf/über alles (o-Direktional + kol)',                        stars: '★★★',  cat: 'kompositum' },
  { eva: 'yoar',      heb: 'יְ+אַ+אָר',           de: 'er wird zum Licht hin [heilen] (y-Imperfekt + ar-Licht)',     stars: '★★',   cat: 'verb'       },
  // f18v — Dracunculus vulgaris (Drachenwurz)
  { eva: 'told',      heb: 'תּוֹלֵד',             de: 'es erzeugt/bringt hervor (Imperfekt Qal von ילד)',            stars: '★★★',  cat: 'verb'       },
  { eva: 'ytchm',     heb: 'יְ+תְּ+חֵם',          de: 'er/sie wird Wärme bringen (y+t-Doppelpräfix + cham)',         stars: '★★★',  cat: 'verb'       },
  { eva: 'otchdal',   heb: 'אוֹת+כְּ+דַּל',       de: 'Zeichen der Schwäche (oto + Direktional + dal)',              stars: '★★★★', cat: 'kompositum' },
  { eva: 'dchal',     heb: 'דְּ+חַל',             de: 'von dem was gilt / von dem Sterbenden (d-Genitiv + chal)',    stars: '★★★',  cat: 'syntax'     },
  { eva: 'dchy',      heb: 'דְּ+כָּ+הִי',          de: 'von der Blässe davon (d-Genitiv + ckhy)',                    stars: '★★★',  cat: 'symptom'    },
  { eva: 'qotchy',    heb: 'וְ+אוֹת+כְּ+הִי',     de: 'und das Zeichen der Blässe (qo + otchy)',                    stars: '★★★★', cat: 'kompositum' },
  { eva: 'qokay',     heb: 'וְ+כְּ+חַי',          de: 'und wie lebendig (qo + k + chay)',                           stars: '★★★',  cat: 'syntax'     },
  { eva: 'ydl',       heb: 'יִדַּל',              de: 'er wird schwach werden (Imperfekt Qal von דלל)',              stars: '★★★',  cat: 'verb'       },
  { eva: 'ychoees',   heb: 'יְ+כֹּ+עֵשׁ',         de: 'er löscht das Feuer / heilt das Fieber (y + kol + esh)',     stars: '★★★',  cat: 'verb'       },
  { eva: 'qol',       heb: 'וְ+עַל',              de: 'und auf/über (qo-Präfix + ol-Direktional)',                   stars: '★★★',  cat: 'syntax'     },
  { eva: 'qotchol',   heb: 'וְ+אוֹת+כֹּל',        de: 'und das Universal-Zeichen (qo + otchol)',                    stars: '★★★',  cat: 'kompositum' },
  { eva: 'daiir',     heb: 'דַּ+אִיר',            de: 'der Leuchtende (verlängerte Form von dair)',                  stars: '★★★',  cat: 'prognose'   },
  { eva: 'ychol',     heb: 'יְ+כֹּל',             de: 'er heilt alles (Verbform, y-Imperfekt + kol; Var.: ykol f18v P.10)', stars: '★★★★', cat: 'verb'       },
  { eva: 'chod',      heb: 'חֹד',                 de: 'Schärfe / Akutheit (medizinischer Terminus)',                 stars: '★★★',  cat: 'symptom'    },
  { eva: 'tolol',     heb: 'תֹּלֹל',              de: 'geschwächt / hängend (med. Zustand, Adj.)',                   stars: '★★★',  cat: 'symptom'    },
  { eva: 'cphoy',     heb: 'כְּ+פְּ+הוֹ',         de: 'wie sein Atemweg / wie sein Mund (Komparativ)',               stars: '★★★',  cat: 'akteur'     },
  { eva: 'ytor',      heb: 'יְ+תֹּ+אוֹר',         de: 'er/sie wird zum Licht werden / erleuchten (Auferstehungs-/Illuminations-Verb; Langform: yteor) — R43 dreifach bestätigt: f18v (3×) + f58r P.30 + f19v P.12 → ★★★★★ Kand.', stars: '★★★★★', cat: 'verb'       },
  { eva: 'ykam',      heb: 'יְ+קָם',              de: 'er wird aufstehen / sich erheben (y-Imperfekt von קום qum) — R43 Kand.: nur f18v (4×), zweiter Folio-Beleg ausstehend',  stars: '★★★',  cat: 'verb'       },
  { eva: 'doky',      heb: 'דּוֹ+כִּי',           de: 'sein denn / weil (Genitiv-Kausalpartikel)',                   stars: '★★★',  cat: 'syntax'     },
  { eva: 'qoeees',    heb: 'וְ+עַ+אֵשׁ',          de: 'und auf dem Feuer / Fieber (qo + oeees)',                    stars: '★★★★', cat: 'symptom'    },
  { eva: 'qokeees',   heb: 'וְ+כְּ+עֵשׁ',         de: 'und wie Feuer / Fieber (qo + k + esh)',                      stars: '★★★★', cat: 'symptom'    },
  { eva: 'qokshy',    heb: 'וְ+כְּ+שֵׁי',         de: 'und wie die Gabe (qo-Präfix + okshy)',                       stars: '★★★',  cat: 'kompositum' },
  { eva: 'ykar',      heb: 'יְ+כְּ+אָר',          de: 'er heilt leuchtend / er wird leuchten (Variante von ykair; Quire-C-Form + f69r P.3 — register-übergreifend: Botanik + Kosmogramm) — R43 register-übergreifend erfüllt',       stars: '★★★★', cat: 'verb'       },
  // ── v6.4 (f58r — Erster astronomischer Stresstest, Quire H) ──────────────
  { eva: 'shalom',      heb: 'שָׁלוֹם',                de: 'Friede / günstige Konstellation — Corpus-Erstbeleg; R43-Kand.: f58r P.4 (beide Transkriptoren identisch)',              stars: '★★★',  cat: 'prognose'   },
  { eva: 'qor',         heb: 'וְ+אֹר',                 de: 'und Licht (qo-Konjunktion + or-Anker, astronomisch) — f58r P.5',                                                       stars: '★★★★', cat: 'kompositum' },
  { eva: 'ytalar',      heb: 'יְ+תַּ+אֹר',             de: 'er wird [Licht] geben/erleuchten (or-Ketten-Verb, f58r P.5)',                                                          stars: '★★★',  cat: 'verb'       },
  { eva: 'dshor',       heb: 'דְּ+שׁוֹר / דְּ+אֹר',   de: 'von/des Lichts (Aramaismus: d-Relativpräfix R45, kein D1-Flag) — f58r P.4',                                           stars: '★★★',  cat: 'prognose'   },
  { eva: 'opsheolaiin', heb: 'עַ+פֶּ+שְׁאוֹל+עַיִן',  de: 'am Nadir-Punkt des Sternauges (op-Koordinatenmarker, R41-Erweiterung) — f58r P.26',                                   stars: '★★★',  cat: 'kompositum' },
  // ── v6.5 (f19r + f19v — Bifolio bC3: Stephanskraut + Teufelsabbiss) ──────
  // f19r — Delphinium staphisagria
  { eva: 'oscheor',   heb: 'עַ+שֶׁ+אוֹר',          de: 'auf dem was Licht ist (o + she + cheor-Kompositum) — f19r P.3',                                                          stars: '★★★',  cat: 'prognose'   },
  { eva: 'qokorar',   heb: 'וְ+כֹּ+אוֹר+אָר',       de: 'und alles Licht der Heilung (qo + kol + or + ar) — f19r P.4',                                                           stars: '★★★',  cat: 'kompositum' },
  { eva: 'cthar',     heb: 'כְּ+תַּ+חַר',           de: 'wie vollständiges Fieber (Quire-C-a-Vokal-Variante von cthor) — f19r P.7',                                              stars: '★★★',  cat: 'symptom'    },
  { eva: 'otytchy',   heb: 'אוֹת+יְ+תְּ+כְּ+הִי',  de: 'das Zeichen er-wird-Blässe-zeigen (ot + ytchy-Kompositum) — f19r P.6',                                                 stars: '★★★',  cat: 'kompositum' },
  { eva: 'daiinol',   heb: 'דִּין+עַל',             de: 'Urteil über [etwas] (daiin + ol-Direktional) — f19r P.12',                                                              stars: '★★★',  cat: 'syntax'     },
  { eva: 'octhor',    heb: 'עַ+כְּ+תֹּר',           de: 'auf vollständige Heilung (o-Direktional + cthor, Schlusskolophon-Term) — f19r P.13',                                    stars: '★★★★', cat: 'kolophon'   },
  // f19v — Succisa pratensis
  { eva: 'pochaiin',  heb: 'פֹּ+כְּ+עַיִן',         de: 'beim/am Auge (Pe-Direktional + kaiin-Basis) — f19v P.1',                                                               stars: '★★★',  cat: 'akteur'     },
  { eva: 'darom',     heb: 'דָּרוֹם',               de: 'Süden (erster Richtungsterm im botanischen Corpus) — f19v P.2',                                                         stars: '★★★',  cat: 'symptom'    },
  { eva: 'ytol',      heb: 'יְ+תֹּלֹל',             de: 'er wird geschwächt (y-Imperfekt von tolol) — f19v P.3',                                                                 stars: '★★★',  cat: 'verb'       },
  { eva: 'ddor',      heb: 'דְּ+דֹּר',              de: 'von Generation/Zeitraum [intensiv] (d-Relativpräfix + dor) — f19v P.8',                                                 stars: '★★★',  cat: 'symptom'    },
  { eva: 'okchan',    heb: 'עַ+כְּ+חָן',            de: 'auf/für die Gnade (o + k + chan, positive Prognose-Direktional) — f19v P.9',                                            stars: '★★★★', cat: 'prognose'   },
  { eva: 'otam',      heb: 'אוֹת+תָּם / אוֹת+אָם',  de: 'Zeichen der Vollständigkeit (ot+tam, f19v P.10); im Zodiak-Register: Zeichen der Mutter/des Weiblichen (ot+am, f72r1 R1 3×, semantisch Taurus-kongruent); im botanischen Register: Prognosezeichen der Mutter (f22v P.3 rechts von {plant}) — R43 erfüllt: 2 Register (Zodiak + Botanisch) → ★★★★',                         stars: '★★★★', cat: 'kompositum' },
  { eva: 'okchod',    heb: 'עַ+כְּ+חֹד',            de: 'auf die Schärfe/Akutheit (o + k + chod, therapeutischer Direktional) — f19v P.11',                                     stars: '★★★★', cat: 'kompositum' },
  { eva: 'yees',      heb: 'יְ+אֵשׁ',               de: 'er löscht das Feuer/Fieber (y-Imperfekt + esh-Stamm) — f19v P.12',                                                      stars: '★★★',  cat: 'verb'       },
  { eva: 'ytar',      heb: 'יְ+תַּ+אָר',            de: 'er wird Licht geben (Quire-C-a-Vokal-Variante von ytor) — f19v P.12',                                                  stars: '★★★',  cat: 'verb'       },
  // ── v6.6 (f77r — D2-Phonotaktik-Härtetest, Quire M) ─────────────────────
  { eva: 'cheol',          heb: 'ח-ע-ל',           de: 'schöpfen / heben (R43 erfüllt: f77r P.21/P.24/P.38 + f20v P.2 + f21r P.5 + f21r P.8 → 4 Belege, 3 Folios, ★★★★ gesichert; Var. cheeol P.21; genuine ח-ע-Cluster, R50 greift nicht; balneologisch: Augenbad-Marker)', stars: '★★★★', cat: 'verb'       },
  // ── v6.7 (f20r + f20v — Bifolio bC4: Astragalus glycyphyllos + Centaurea scabiosa) ──
  { eva: 'cheey',          heb: 'חֵיי',             de: 'Leben / lebendig (Tsere-Variante von chey per R50; f20r P.13 Schlusskolophon: chor.chor.cheey.tchey= = Pupille—Pupille—Leben—sie belebt)', stars: '★★★',  cat: 'prognose', part: 'FLOS' },
  { eva: 'dol·shol',       heb: 'דָּוֶה+שׁוֹל',    de: 'Schmerz-Scheol (negatives Befundpaar: schwach+Tod; R15-Antonymenpaar; therapeutisches Warnsignal bei Überdosierung) — f20r P.7', stars: '★★★',  cat: 'prognose'   },
  // ── v6.8 (f21r + f21v — Bifolio bC4 Abschluss: Thymus serpyllum + Aquilegia vulgaris) ──
  { eva: 'tshaiin',        heb: 'תּ+שׁ+עַיִן',     de: 'du wirst das Auge [behandeln/waschen] — tav-Imperfekt 2. Sg. + aiin: therapeutischer Direktbefehl an den Arzt — ★★ (R43-Frist abgelaufen f29v, kein Folgebeleg)', stars: '★★',   cat: 'verb'       },
  { eva: 'chotshol',       heb: 'כֹּ+תּ+שְׁאוֹל',  de: 'alles-du-wirst-Scheol — ★★ (morphologisch fragwürdig: kol+tav-Futur+Scheol ohne Separator-Token, 3 Morpheme in einem Token ohne Corpus-Parallele; Wiederaufnahme auf ★★★ Kand. bei zweitem strukturidentischem Beleg) — Corpus-Erstbeleg f21v P.6', stars: '★★',   cat: 'prognose'   },
  { eva: 'ysheol',         heb: 'יְ+שׁ+אֹל',       de: 'er wird [aus] Scheol [aufsteigen] — positive Verbform: y-Imperfekt + sheol als Aufstiegs-Wendepunkt; eingerahmt von chor-chor in Schlusskolophon — ★★ (R43-Frist abgelaufen f29v, kein Folgebeleg)', stars: '★★',   cat: 'verb'       },
  { eva: 'dait',           heb: 'דַּ+עִת',          de: 'von/aus der Zeit / im Moment — zeitliche Deiktik (d-Präfix + ʿet = Zeit) — ★★ Kand. (Erstbeleg f21v P.5)', stars: '★★',   cat: 'syntax'     },
  { eva: 'keeees',         heb: '???',               de: 'Hapax — extreme Tsere-Emphase (vierfaches ee) oder Schreiberfehler; kein Parallelbeleg im Gesamtcorpus — f21v P.3', stars: '★',    cat: 'symptom'    },
  // ── v6.9 (f71r + f71v + f72r1 + f72r2 — Quire K · Zodiak-Tetraptychon bK1) ──
  { eva: 'alef',       heb: 'אָלֶף',             de: 'Aleph (Ochse) — erste ikonographische Buchstabenreferenz im Zodiak; exklusiv im Stier-dunkel-Panel (f72r1), semantisch direkt: Aleph = Piktogramm Ochsenkopf',   stars: '★★★',  cat: 'kompositum' },
  { eva: 'otalef',     heb: 'אוֹת+אָלֶף',        de: 'Zeichen des Aleph / Zeichen des Ochsen — ot-Präfix + alef; nur f72r1 S1.9 (otalef.as.ainam=)',                                                                      stars: '★★★',  cat: 'kompositum' },
  { eva: 'sheeolody',  heb: 'שְׁאוֹל+עֹ+דִּי',   de: 'von jenem Scheol — Scheol-Vollform + Vokalhelfer + Genitivpartikel; R52a-suffigiert — f71v R1',                                                                    stars: '★★★',  cat: 'prognose'   },
  { eva: 'sheoltey',   heb: 'שְׁאוֹל+טַ+יְ',     de: 'Scheol des Tau-Zeichens — Scheol-Vollform + Tet + Yod-Imperfekt; f72r1 R1 (neben shol medial)',                                                                     stars: '★★★',  cat: 'prognose'   },
  { eva: 'sholshdy',   heb: 'שׁוֹל+שׁ+דִּי',     de: 'Scheol — von dem Scheol (R24-Emphase-Dopplung mit Genitiv-Brücke); f71v S2.5',                                                                                      stars: '★★★',  cat: 'prognose'   },
  { eva: 'shokal',     heb: 'שׁוֹ+כָּל',          de: 'Scheol von allem — sho-Präfix (R30) + kol; f72r2 R2 (neues R30-Kompositum im Zodiak)',                                                                               stars: '★★★',  cat: 'prognose'   },
  { eva: 'chotam',     heb: 'כֹּ+אוֹת+אָם',      de: 'wie das Zeichen der Mutter — Komparativ-Dritte-Stufe der R19/R35-Intensivierungsreihe otam·otam·chotam (f72r1 R1)',                                                   stars: '★★★',  cat: 'kompositum' },
  { eva: 'cheekaiin',  heb: 'כֵּ+כְּ+עַיִן',     de: 'wie das Auge (B-Register Zodiak) — doppelter k-Komparativ mit Tsere (R50); f71v R3',                                                                                  stars: '★★★',  cat: 'akteur'     },
  { eva: 'okeodaly',   heb: 'עַ+כֵּ+עֹ+דַּל',    de: 'auf dem Weg des Schwachen — o-Direktional + kee + ol + dal; f71v R1 + f72r1 R1 (R43 erfüllt: 2 Folios)',                                                              stars: '★★★',  cat: 'kompositum' },
  // ── v7.0 (f22r + f22v — Bifolio bC3 Abschluss: Plantago + Veratrum album) ──
  { eva: 'oraiino',    heb: 'אוֹר+עַיִן+וֹ',       de: 'Licht seines Auges — Kolophon-Formel (or + aiin + Possessivsuffix 3. Sg. mask.); Erstbeleg f22r P.9',                                                        stars: '★★★★', cat: 'kolophon'   },
  { eva: 'ctheor',     heb: 'כְּ+תֶּ+אוֹר',         de: 'wie Licht-Gewähren / wie Erleuchtung (k + ten + or) — ★★★ Kand. (Erstbeleg f22r P.9)',                                                                          stars: '★★★',  cat: 'prognose'   },
  { eva: 'cphal',      heb: 'כְּ+פָּלַל',           de: 'wie Gebet/Urteil (פָּלַל = urteilen/beten) — ★★ (R43-Frist abgelaufen f29v, kein Folgebeleg)',                                                             stars: '★★',   cat: 'syntax'     },
  { eva: 'schor',      heb: 'שׂ+חֹר',               de: 'gleich der Pupille (Sin-Präfix + chor) — ★★★ Kand. (Erstbeleg f22r P.4)',                                                                                        stars: '★★★',  cat: 'symptom'    },
  { eva: 'ctheen',     heb: 'כְּ+תֵּן',             de: 'wie Gewähren/Geben — Kolophon-Kurzformel — ★★ (R43-Frist abgelaufen f29v, kein Folgebeleg)',                                                               stars: '★★',   cat: 'kolophon'   },
  { eva: 'pysaiinor',  heb: 'פִּי+שׂ+עַיִן+אוֹר',   de: 'Mund gleich dem Auge des Lichts (pi + sin + ayin + or) — ★★ (R43-Frist abgelaufen f29v, kein Folgebeleg)',                                                   stars: '★★',   cat: 'kompositum' },
  { eva: 'kchorl',     heb: 'כְּ+חֹר+לְ',           de: 'wie die Pupille hin — direktionaler Komplex (k + chor + lamed) — ★★ (R43-Frist abgelaufen f29v, kein Folgebeleg)',                                          stars: '★★',   cat: 'akteur'     },
  { eva: 'ykcheor',    heb: 'יְ+כְּ+כְּ+אוֹר',      de: 'er wird sein wie Licht — dreifach intensives Heilungsverb (y + k + k + or); R43 erfüllt: f22v P.5 + Zodiak-Register → ★★★★',                                    stars: '★★★★', cat: 'verb'       },
  { eva: 'okchain',    heb: 'עַ+כְּ+חַיִּין',        de: 'hin zu Leben / auf Leben hin — o-Direktional + k + chayyim; R43 erfüllt: f22v P.13 + Parallelbelege → ★★★★',                                                     stars: '★★★★', cat: 'kompositum' },
  { eva: 'daldalol',   heb: 'דַּל+דַּל+עוֹל',        de: 'doppelte Schwäche des Joches — R35-Duplikation in Titelposition (T-Klasse); R53-Strukturbeleg (R53 ★★★★ gesichert) — ★★ (R43-Frist abgelaufen, eigenständige Kandidaten-Stellung endet; bleibt als R53-Strukturbeleg dokumentiert)',                                  stars: '★★',   cat: 'kompositum' },
  { eva: 'dsheor',     heb: 'דְּ+שֶׁ+אוֹר',          de: 'von dem, was Licht ist — d-Relativpräfix + she + or (R45-Aramaismus); Erstbeleg f22r P.7',                                                                        stars: '★★★',  cat: 'prognose'   },
  { eva: 'olshly',     heb: 'עַל+שׁ+לְ+יְ',          de: 'auf Scheol hin — direktionale Scheol-Form (ol + sh + lamed + yod); Erstbeleg f22v P.14',                                                                          stars: '★★★',  cat: 'prognose'   },
  { eva: 'ytal',       heb: 'יְ+תַּל',               de: 'er wird suspendieren/aufhängen (y-Imperfekt von תלל) — ★★ Kand. (Erstbeleg f22v P.10)',                                                                            stars: '★★',   cat: 'verb'       },
  { eva: 'shotoly',    heb: 'שׁוֹ+תּ+עוֹל+יְ',        de: 'Scheol-Last hin — sho-Präfix (R30) + Joch-Direktional; Erstbeleg f22v P.13',                                                                                     stars: '★★★',  cat: 'prognose'   },
  { eva: 'cthoiin',    heb: 'כְּ+תּ+עַיִן',           de: 'wie vollständige Augen-Heilung — cthor-Variante mit aiin-Suffix; Erstbeleg f22r P.10',                                                                           stars: '★★★',  cat: 'verb'       },
  // ── v7.1 (f23r + f23v — Bifolio bC2 Abschluss: Geranium pratense + Borago officinalis) ──
  { eva: 'tshol',     heb: 'תְּ+שׁוֹל',              de: 'sie entfernt von Scheol — Vollform von tsho; strukturelles P.6-Eröffnungstoken auf beiden Seiten desselben Folios; Erstbeleg f23r P.6 + f23v P.6',                           stars: '★★★',  cat: 'prognose'   },
  { eva: 'daiidal',   heb: 'דִּין+דַּל',              de: 'Urteil der Schwäche (daiin+dal-Kompositum); Erstbeleg f23r P.6',                                                                                                               stars: '★★★',  cat: 'kompositum' },
  { eva: 'dalory',    heb: 'דַּל+אוֹר+יְ',            de: 'Schwäche zum Licht (Kolophon-Formel, R6-Kompositum) — ★★ (R43-Frist abgelaufen f29v, kein Folgebeleg)',                                                           stars: '★★',   cat: 'kolophon'   },
  { eva: 'ytom',      heb: 'יְ+תָּ+מ',               de: 'er wird vollständig/komplett (y-Imperfekt v. תמם; Var.: ytam) — ★★ (R43-Frist abgelaufen f29v, kein Folgebeleg)',                                              stars: '★★',   cat: 'verb'       },
  { eva: 'qokor',     heb: 'וְ+כֹּ+אָר',              de: 'und alles Licht (qo+kol+ar); Erstbeleg f23v P.8',                                                                                                                               stars: '★★★',  cat: 'kompositum' },
  { eva: 'sholol',    heb: 'שׁוֹל+עַל',               de: 'Scheol über [etwas] (Präpositionalkomplex); Erstbeleg f23v P.4',                                                                                                                stars: '★★',   cat: 'prognose'   },
  { eva: 'otshor',    heb: 'אוֹת+שׁ+אוֹר',            de: 'das Zeichen des Lichts (ot+shor-Kompositum); Erstbeleg f23v P.6',                                                                                                              stars: '★★★',  cat: 'kompositum' },
  { eva: 'olsar',     heb: 'עַל+שַׂר',                de: 'über den Arzt / ärztliche Aufsicht (ol + sar); Erstbeleg f23v P.6 rechts von {plant} — Arzt-Supervision-Marker im Therapie-Teil — ★★ (R43-Frist abgelaufen f29v, kein Folgebeleg)',                                            stars: '★★',   cat: 'akteur'     },
  { eva: 'aiior',     heb: 'עַ+יִ+אוֹר',              de: 'Auge des Lichts (ayin+yod+or); Erstbeleg f23v P.12 — ★★ (R43-Frist abgelaufen f29v, kein Folgebeleg)',                                                           stars: '★★',   cat: 'akteur'     },
  // ── v7.2 (f24r + f24v — Bifolio bC1 Abschluss: Silene vulgaris + Pulsatilla vulgaris) ──
  { eva: 'olom',       heb: 'עוֹלָם',                  de: 'Ewigkeit / Welt — Erstbeleg f24v P.7; Kontext: Pulsatilla / Toxizität / Scheol; semantisch kohärent',                                                                 stars: '★★★★', cat: 'prognose'   },
  { eva: 'otaiir',     heb: 'אֹת+עַ+יִ+ר',             de: 'Zeichen des Augenlichts (ot-Präfix + ayin + yod + or) — Erstbeleg f24v P.2 (ot-Kompositum-Dreikette); Zweitbeleg f25r T.7 (T-Klassen-Titel Subtyp C); R43 erfüllt → ★★★★★ Kand.',                                   stars: '★★★★★', cat: 'kompositum' },
  { eva: 'oro',        heb: 'אֹ+ר+אֹ',                 de: 'Licht-Palindrom / maximale Heilungs-Affirmation — Erstbeleg f23v P.12 (ol.oro.eeeoly=, 3/4 Transkriptoren); Zweitbeleg f24v P.5 (oro=, 4/4) — R43 erfüllt: 2 Folios → ★★★ regulär (kein Kandidaten-Status mehr; s. R55)',  stars: '★★★',  cat: 'kolophon'   },
  { eva: 'cheekdam',   heb: 'כְּ+אֵ+כְּ+דָּ+מ',         de: 'wie das Zeichen des Blutes (Komparativ-Dopplung + dam) — Erstbeleg f24v P.14',                                                                                       stars: '★★★★', cat: 'kompositum' },
  { eva: 'qodom',      heb: 'קֶדֶם',                   de: 'Osten / Vorzeit / Vergangenheit — f24v P.11 — ★★ (R43-Frist abgelaufen f29v, kein Folgebeleg)',                                                                stars: '★★',   cat: 'symptom'    },
  { eva: 'sam.chorly', heb: 'שָׁם+כֹּר+לִי',           de: 'so heile meine Pupille (T-Klassen-Formel: sham + kor + li) — f24r T.20; dritter T-Klassen-Beleg (R53 Subtyp)',                                                      stars: '★★★',  cat: 'kolophon'   },
  { eva: 'sshey',      heb: 'שׁ+שׁ+הֵי',               de: 'Doppel-Shin-Blässe (sho.sho-Emphase + sheey, R56) — f24r P.17 — ★★ (R43-Frist abgelaufen f29v, kein Folgebeleg)',                                                   stars: '★★',   cat: 'symptom'    },
  { eva: 'odaiim',     heb: 'עַ+דִּינִים',              de: 'auf den (kollektiven) Urteilen (o-Direktional + dayin-Plural-m) — f24v P.16; Abschluss-Kolophon-Marker (R57); ★★★ Kand.',                                            stars: '★★★',  cat: 'syntax'     },
  { eva: 'ydals',      heb: 'יְ+דַּ+לְ+שׁ',             de: 'er wird Schwäche läutern (y-Imperfekt + dal + shin) — f24v P.2 — ★★ (R43-Frist abgelaufen f29v, kein Folgebeleg)',                                            stars: '★★',   cat: 'verb'       },
  { eva: 'doiir',      heb: 'דֹּ+יִ+ר',                de: 'sehr schwache Erweckung (dol + yod + or) — f24v P.14; ★★★ Kand. (Folgebeleg erforderlich)',                                                                          stars: '★★★',  cat: 'prognose'   },
  { eva: 'daid',       heb: 'דַּ+אִי+דַּ',              de: '? / תָּמִיד = dauerhaft — f24v P.7; ★★ Kand. (Semantik noch offen)',                                                                                                  stars: '★★',   cat: 'syntax'     },
  { eva: 'otaiphy',    heb: 'אֹת+אַ+יְ+פֶּ+הֵי',       de: 'Hapax: Zeichen-Blässe-Mund (ot + ay + peh + hey) — f24r P.19; Einzelbeleg; ★★ Kand.',                                                                               stars: '★★',   cat: 'kompositum' },
  // ── v7.3 (f25r + f25v — Bifolio bD1 Eröffnung: Urtica dioica + Chelidonium majus) ──
  { eva: 'orchaiin',  heb: 'אֹ+ר+כְּ+עַ+יִין',        de: 'Licht-wie-Auge (Kolophon-Abschlussformel) — f25v P.7; or+chor/k+aiin: strukturell reichste Kolophon-Formel bisher; alle H/C/F einig',                           stars: '★★★★', cat: 'kolophon'   },
  { eva: 'otosy',     heb: 'אֹת+אֹ+שׂ+יְ',             de: 'Zeichen-Scheol-gleich-er (ot + sin + yod) — f25r T.7; Teil des T-Klassen-Titels Subtyp C (dair.otaiir.otosy=) — ★★ (R43-Frist abgelaufen, Direktsuche f25v–f27v negativ)',  stars: '★★',   cat: 'kompositum' },
  { eva: 'daiity',    heb: 'דִּין+תּ',                 de: 'Urteils-tav / juristische Abschlussform (daiin + tav) — f25v P.3 — ★★ (R43-Frist abgelaufen, Direktsuche f26r–f28r negativ)',                          stars: '★★',   cat: 'syntax'     },
  { eva: 'cheesees',  heb: 'כְּ+אֵ+שׂ+אֵ+שׁ',          de: 'Dreifach-Licht-Zeichen (k + esh + sin + esh) — f25r P.3; dreifaches Licht-Feuer-Kompositum — ★★ (R43-Frist abgelaufen, Direktsuche f25v–f27v negativ)',  stars: '★★',   cat: 'kompositum' },
  { eva: 'ckhear',    heb: 'כְּ+כְּ+אֵ+ר',              de: 'wie das Licht (ckh-Variante von cheor) — f25v P.4; Minimalpaar ckhear vs. chkear = Reihenfolgevarianz (Orthographienotiz); ★★★★',                               stars: '★★★★', cat: 'prognose'   },
  { eva: 'qokoral',   heb: 'וְ+כְּ+אֹ+ר+עַ+לְ',        de: 'und wie Licht-auf (qo + k + or + al-Direktional) — f25v P.6 — ★★ (R43-Frist abgelaufen, Direktsuche f26r–f28r negativ)',                             stars: '★★',   cat: 'kompositum' },
  { eva: 'soshy',     heb: 'שׂ+אֹ+שׁ+יְ',               de: 'gleich Scheol-er (Doppel-Shin: sin + alef + shin + yod) — f25r P.1; ★★★ Kand. (Erstbeleg, Folgebeleg erforderlich)',                                            stars: '★★★',  cat: 'prognose'   },
  // ── v7.4 (Härtetests f1r + f1v — Quire A, bA1: Haskama-Analyse) ──
  { eva: 'daiiin',    heb: 'דִּינִין',                  de: 'Urteile (Aramäischer Emphase-Plural von דִּין; Aram. Plural-iin, 3× Yod) — f1r T3 `otol.daiiin=`; 6/6 Transkriptoren einig (H/C/F/N/X/U); R40-Ausnahme b+c; f26v P.1 + P.7 (2. Folio-Beleg); f27r P.12 (3. Folio-Beleg) = R43 dreifach erfüllt → ★★★★',            stars: '★★★★',  cat: 'syntax'     },
  { eva: 'dain',      heb: 'דָּן',                      de: 'Richter (Partizip QAL von דין) — f1r T2 `dain.os.teody=` + P3.L14; morphologische Distinktion zu daiin (Substantiv) und daiiin (Plural) — R43 erfüllt: f1r T2/P3 + f30v P.5 = 2 Folios → ★★★ validiert',  stars: '★★★',  cat: 'akteur'     },
  // ── v7.6 (f26r + f26v — Bifolio bD2: Solanum nigrum + Centaurea cyanus) ──
  { eva: 'saraiir',   heb: 'שַׂר+אִיר',              de: 'Arzt des Leuchtenden (sar + aiir Komposit) — f26v P.2 — ★★ (R43-Frist abgelaufen, Direktsuche f27r–f29r negativ)',                stars: '★★',   cat: 'akteur'  },
  { eva: 'ykeechy',   heb: 'יְ+כְּ+אֵ+כְּ+הֵי',       de: 'er heilt wie Blässe-Licht (8. y+k-Verb) — f26r P.9 — ★★ (R43-Frist abgelaufen, Direktsuche f26v–f28v negativ)',          stars: '★★',   cat: 'verb'    },
  { eva: 'qoteedar',  heb: 'וְ+תֵּ+דַּר',             de: 'und er/du wirst leuchten (qo + Tsere + dar) — f26r P.8 — ★★ (R43-Frist abgelaufen, Direktsuche f26v–f28v negativ)',           stars: '★★',   cat: 'verb'    },
  { eva: 'cheeol',    heb: 'כְּ+אֵ+עַל',             de: 'wie kein Joch / wie Ende des Joches — ★★★ validiert (R43 erfüllt: f26v P.3 + f29r P.5 = 2 Folios)',                           stars: '★★★',  cat: 'symptom' },
  { eva: 'ory',       heb: 'אוֹר+יְ',                de: 'sein Licht / er erleuchtet — f26v P.8 — ★★★ Kand. (R43-Frist: 5 Folios)',                                                        stars: '★★★',  cat: 'prognose' },
  { eva: 'eedy',      heb: 'אֵ+דִּי',                de: 'kein Licht — von (Negativ-Licht-Genitiv) — f26r P.5 — ★★★ Kand. (R43-Frist: 5 Folios)',                                          stars: '★★★',  cat: 'prognose' },
  // ── v7.7 (f27r + f27v — Bifolio bD3: Symphytum officinale + Leucanthemum vulgare) ──
  { eva: 'ksor',      heb: 'כֵּ+שָׁר',               de: 'denn/wie passend/gesund (כָּשֵׁר = angemessen) — ★★★ Kand. (R43-Frist: 5 Folios; Erstbeleg f27r P.1)',                            stars: '★★★',  cat: 'syntax'     },
  { eva: 'shod',      heb: 'שׁוֹד',                  de: 'Verheerung / Verwüstung (שׁוֹד = devastation) — ★★★ validiert (R43 erfüllt: f27r P.1 + f28r P.1 = 2 Folios)',                       stars: '★★★',  cat: 'symptom'    },
  { eva: 'keeod',     heb: 'כֵּ+עוֹד',               de: 'denn noch / immer noch (temporaler Adverb) — ★★★ Kand. (R43-Frist: 5 Folios; Erstbeleg f27r P.9)',                               stars: '★★★',  cat: 'syntax'     },
  { eva: 'cphary',    heb: 'כְּ+פַּר+יְ',             de: 'wie sein Sühnopfer / wie seine Expiation — f27r P.5 — ★★ (R43-Frist abgelaufen, Direktsuche f27v–f29v negativ)',           stars: '★★',   cat: 'kompositum' },
  { eva: 'fochof',    heb: 'פֹ+כֹ+פְ',               de: 'Mund/Kehle-alles / Kehlenbereich (Var.: chof = כֹ+פְ) — ★★★ Kand. (R43-Frist: 5 Folios; Erstbeleg f27v P.1)',                    stars: '★★★',  cat: 'akteur'     },
  { eva: 'kshy',      heb: 'כְּ+שֵׁי',               de: 'wie die Gabe (k-Präfix + sheey) — ★★★ Kand. (R43-Frist: 5 Folios; Erstbeleg f27v P.8)',                                          stars: '★★★',  cat: 'kompositum' },
  // ── v7.8 (f28r + f28v — Bifolio bD4: Plantago major + Agrimonia eupatoria) ──
  { eva: 'sor',       heb: 'שׂ+אֹר',                de: 'Arzt des Lichts (Sprache-A-Vokalalternanz von sar, a↔o R33-konform) — ★★★★; f28v P2.9 Kolophon (Heilerkolophon sor·dar=)',               stars: '★★★★', cat: 'akteur'     },
  { eva: 'pchodar',   heb: 'פְּ+כֹּ+דַּ+ר',          de: 'wie Finsternis/Dunkelheit (von כָּדַר aram.) — ★★★ Kand. (R43-Frist: 5 Folios; Erstbeleg f28r P.1)',                                      stars: '★★★',  cat: 'symptom'    },
  { eva: 'opchol',    heb: 'עַ+פְּ+כֹּ+ל',           de: 'auf allem wirkend (Pe-Präfix + chol) — R43 erfüllt: f28r P.1 + f30r P.8 = 2 Folios → ★★★ validiert',                                    stars: '★★★',  cat: 'akteur'     },
  { eva: 'dchar',     heb: 'דְּ+כַּ+ר',              de: 'vom Widder/männlich (Zutaten-Term, d-Genitiv + kar) — ★★★ Kand. (R43-Frist: 5 Folios; Erstbeleg f28r P.2)',                              stars: '★★★',  cat: 'akteur'     },
  { eva: 'chakod',    heb: 'כְּ+עַ+כֹּ+ד',           de: 'wie zusammen/versammelt (k-Komparativ + akod) — ★★★ Kand. (R43-Frist: 5 Folios; Erstbeleg f28r P.2)',                                   stars: '★★★',  cat: 'syntax'     },
  { eva: 'cthol',     heb: 'כְּ+ת+הֹ+ל',             de: 'Vollständigkeits-Marker (strukturell: 3× in f28r P.2–P.4) — ★★★ Kand. (R43-Frist: 5 Folios; Erstbeleg f28r P.2)',                      stars: '★★★',  cat: 'kolophon'   },
  { eva: 'okam',      heb: 'עַ+כַּ+ם',               de: 'für das Volk / für alle (universale Therapieangabe) — ★★★ Kand. (R43-Frist: 5 Folios; Erstbeleg f28r P.6)',                             stars: '★★★',  cat: 'akteur'     },
  { eva: 'shocthy',   heb: 'שׁוֹ+כְּ+ת+יְ',           de: 'vollständiges Scheol (Intensivform: sho + Vollständigkeits-tav + yod) — ★★★ validiert (R43 erfüllt: f28r P.7 + f29r P.6 = 2 Folios)',  stars: '★★★',  cat: 'prognose'   },
  { eva: 'ytchol',    heb: 'יְ+ת+כֹּ+ל',             de: 'er wird alles vollenden (y+t Doppelpräfix + kol; Kolophon f28r P.9) — ★★★★',                                                            stars: '★★★★', cat: 'verb'       },
  { eva: 'yteol',     heb: 'יְ+ת+אֵ+עֹ+ל',           de: 'er wird handeln/vollbringen (y+t Doppelpräfix; Kolophon f28r P.9 neben ytchol) — ★★★★',                                                 stars: '★★★★', cat: 'verb'       },
  { eva: 'deaiin',    heb: 'דְּ+עַ+יִן',              de: 'vom Auge (Direktional, d-Relativpräfix + ayin; Kolophon f28r P.9) — ★★★★',                                                             stars: '★★★★', cat: 'akteur'     },
  { eva: 'kshol',     heb: 'כְּ+שׁוֹל',               de: 'wie Scheol (Komparativ, k-Präfix + shol) — ★★★★; f28v P1.1',                                                                            stars: '★★★★', cat: 'prognose'   },
  { eva: 'ykcholy',   heb: 'יְ+כְּ+כֹּ+ל+יְ',         de: 'er heilt alles (y+k+chol Paradigma + Possessiv-yod) — ★★★★; f28v P1.2',                                                               stars: '★★★★', cat: 'verb'       },
  { eva: 'tshoiin',   heb: 'ת+שׁוֹ+עַ+יִן',            de: '[sie] wendet das Auge von Scheol (t-Imperfekt + sho + ayin) — ★★★★; f28v P1.4',                                                       stars: '★★★★', cat: 'verb'       },
  { eva: 'chear',     heb: 'כְּ+אֵ+עַ+ר',             de: 'wie erleuchten / wie das Licht wirkt (Heilerkolophon-Term) — ★★★ Kand. (R43-Frist: 5 Folios; Erstbeleg f28v P2.9)',                    stars: '★★★',  cat: 'prognose'   },
  // ── v7.9 (f29r + f29v — Bifolio bD4 Abschluss: Rumex crispus + Echium vulgare) ──
  { eva: 'poraiin',   heb: 'פְּ+אוֹר+עַיִן',          de: 'Licht des Auges (p-Präfix + or + ayin) — ★★★ Kand. (Erstbeleg f29r P.1)',                                                             stars: '★★★',  cat: 'akteur'     },
  { eva: 'shos',      heb: 'שׁ+עַ+שׁ',                de: 'Feuer-Ähnliches (Variante von sheos/shees, shin + ayin + shin) — ★★★ Kand. (Erstbeleg f29r P.5)',                                     stars: '★★★',  cat: 'symptom'    },
  { eva: 'shokchy',   heb: 'שׁוֹ+כְּ+כֵּי',            de: 'Scheol-Blässe / Blässe des Todes (sho + k + key) — ★★★ Kand. (Erstbeleg f29r P.7)',                                                   stars: '★★★',  cat: 'prognose'   },
  { eva: 'ychom',     heb: 'יְ+חוֹם',                 de: 'er wird genesen / er wird warm (y-Imperfekt von חום) — ★★★ Kand. (Erstbeleg f29r P.9)',                                               stars: '★★★',  cat: 'verb'       },
  { eva: 'shot',      heb: 'שׁוֹ+תְּ',                de: 'vollständiges Scheol (sho-Präfix + tav-Intensiv) — ★★★ Kand. (Erstbeleg f29v P.4)',                                                   stars: '★★★',  cat: 'prognose'   },
  { eva: 'chain',     heb: 'חַ+עַיִן',                de: 'lebendiges Auge / Auge des Lebens (cham-Stamm + ayin) — R43 erfüllt: f29v P.5 + f30r P.7 = 2 Folios → ★★★ validiert',               stars: '★★★',  cat: 'akteur'     },
  { eva: 'chykar',    heb: 'כְּ+הֵי+כַּ+ר',            de: 'Blässe-Kraft (Zutaten-Variante? k + hey + kar) — ★★ Kand. (Erstbeleg f29v P.10)',                                                     stars: '★★',   cat: 'symptom'    },
  // ── v8.0 (f69r — Quire J/X: Kosmologisches Rad-Diagramm bJ1) ──
  { eva: 'cholam',   heb: 'כֹּ+עוֹלָם',               de: 'wie die Welt / wie Ewigkeit (ko-Komparativ + olam; kosmologisch kohärent) — ★★★★ Kand. (Erstbeleg f69r C.3)',                            stars: '★★★★', cat: 'prognose'   },
  { eva: 'otolam',   heb: 'אוֹת+עַל+אָם',             de: 'Zeichen über alle / Zeichen der Ewigkeit (ot + ol + am) — ★★★★ Kand. (Erstbeleg f69r C.9)',                                               stars: '★★★★', cat: 'akteur'     },
  { eva: 'dairam',   heb: 'דְּ+אִיר+אָם',              de: 'von dem Leuchtenden aller (d-Genitiv + air + am; Radial-Kolophon-Form) — ★★★ Kand. (Erstbeleg f69r R.3)',                                  stars: '★★★',  cat: 'akteur'     },
  { eva: 'tam',      heb: 'תָּם',                      de: 'vollständig / rein — Radial-Kolophon-Typ, Unterform von cthom (tam= als Abschlussmarker in f69r R.5) — ★★★★ Kand. (Erstbeleg f69r R.5)', stars: '★★★★', cat: 'kolophon'   },
  // ── v8.1 (f30r + f30v — Bifolio bD3 Abschluss: Polygonatum multiflorum + Urtica dioica) ──
  { eva: 'chorain',   heb: 'כְּ+אוֹר+עַיִן',          de: 'wie das Licht des Auges (k-Komparativ + or + ayin; Strukturanalog zu poraiin, aber komparativ statt direktional) — ★★★ Kand. (Erstbeleg f30r P.3)',              stars: '★★★',  cat: 'akteur'     },
  { eva: 'cthorchy',  heb: 'כְּ+תְּ+אוֹר+כְּ+הִי',   de: 'vollständige Heilung der Blässe (cthor + chy) — positives Therapie-Kompositum im Kolophon; Kolophon-Abschluss P.7 oberer Textblock — ★★★ Kand. (Erstbeleg f30r P.7)',  stars: '★★★',  cat: 'kolophon'   },
  { eva: 'dchorol',   heb: 'דְּ+כְּ+אוֹר+עֹ+לְ',     de: 'von der Pupille hin (d-Relativpräfix R45 + chor + ol-Direktional) — gibt der Scheol-Licht-Dichotomie einen direktionalen Rahmen — ★★★ Kand. (Erstbeleg f30r P.6)', stars: '★★★',  cat: 'prognose'   },
  { eva: 'chseeor',   heb: 'כְּ+שֵׁ+אוֹר',            de: 'wie die Gabe des Lichts (k-Komparativ + shee + or; Dreifach-Kompositum) — positiver Heilungsabschluss — ★★★ Kand. (Erstbeleg f30r P.6)',                             stars: '★★★',  cat: 'prognose'   },
  { eva: 'soin',      heb: 'שׂ+עַ+יִן',               de: 'Feuer des Auges / Augenentzündung (sin + ayin + yod; Diagnose-Term für akute Augenentzündung) — ★★★ Kand. (Erstbeleg f30r P.4)',                                    stars: '★★★',  cat: 'symptom'    },
  { eva: 'chokcheey', heb: 'חֹק+חֵיי',                de: 'Lebensvorschrift (chok + cheey; Rezept-Substantiv: Therapieanweisung + Lebensprinzip) — stärkstes therapeutisches Kompositum in bD3; Kolophon-Abschluss f30v P.11 — ★★★★ Kand. (Erstbeleg f30v P.11, 3/3 Transkriptoren)',  stars: '★★★★', cat: 'kolophon'   },
  { eva: 'cphoaiin',  heb: 'כְּ+פְּ+עַ+יִן',          de: 'wie der Atemweg des Auges (k-Komparativ + pho + ayin; anatomisch-funktionale Verbindung Atem–Sehorgan) — ★★★ Kand. (Erstbeleg f30v P.8, 3/3 Transkriptoren)',         stars: '★★★',  cat: 'symptom'    },
  { eva: 'sos',       heb: 'שׁ+עַ+שׁ',                de: 'Feuer auf Feuer / Fieber-Intensivierung (Doppel-Shin: shin + ayin + shin) — 2× auf f30v (P.7 + P.9) — ★★★ Kand. (Erstbeleg f30v P.7)',                              stars: '★★★',  cat: 'symptom'    },
  { eva: 'shoty',     heb: 'שׁוֹ+תְּ+יְ',             de: 'vollständiges Scheol von ihm (sho-Apokope + t-Intensivator + y-Possessiv; Distinktion zu shot f29v) — ★★★ Kand. (Erstbeleg f30v P.5)',                              stars: '★★★',  cat: 'prognose'   },
  { eva: 'shosaiin',  heb: 'שׁוֹ+שַׂ+עַיִן',           de: 'Scheol des Augenarztes (sho-Apokope + saiin; diagnostisches Maximalsignal: Augenarzt vor lebensbedrohlichem Befund) — ★★★★ Kand. (Erstbeleg f30v P.1)',              stars: '★★★★', cat: 'prognose'   },
  { eva: 'chokeor',   heb: 'חֹק+אֵ+אוֹר',             de: 'Vorschrift des Lichts (chok + eor; therapeutisches Kompositum: Lichtbehandlungsanweisung) — ★★★ Kand. (Erstbeleg f30v P.3)',                                        stars: '★★★',  cat: 'symptom'    },
  // ── v8.4 (Retroanalyse f1v + f13r + f13v + f57r + f33r — Pflanzenteil-Positionskarten) ──
  { eva: 'fol',       heb: 'פּוּל/פֹּל',              de: 'Röhrenschaft / Stiel-Hülse (CAULIS-Eröffner bei Equisetum — Erstbeleg f13v P.6 als Öffnungsterm des gesamten CAULIS-Blocks; Etymologie: pūlāʾ aram. = Hohlstängel)',                           stars: '★★★',  cat: 'akteur',  part: 'CAULIS'    },
  { eva: 'tal',       heb: 'טַל',                    de: 'Tau / Pflanzensaft / Feuchtigkeit (CAULIS-Term: Stiel als Saft-/Nährstoffleiter; 3× in einem CAULIS-Paragraphen: otal · ytal · tal — R15-Emphase-Triplung) — ★★★ Kand. (Erstbeleg f13v P.9)', stars: '★★★',  cat: 'symptom', part: 'CAULIS'    },
  // ── v8.4 Quire-A-Retroanalyse + f33r (Sprache B) ─────────────────────────
  { eva: 'tshdar',    heb: 'תְּ+שׁ+דָּ+אַר',          de: 'Jahreszeit-Zeichen (Sprache-B-Variante von torshor; Erstbeleg f33r P.1) — ★★★ Kand.', stars: '★★★',  cat: 'symptom' },
  { eva: 'yteey',     heb: 'יְ+תֵּ+אֵי',              de: 'er wird [es] bringen / heilen (Sprache-B-Form; Erstbeleg f33r P.6) — ★★★ Kand.',      stars: '★★★',  cat: 'verb'    },
  { eva: 'okeeey',    heb: 'עַ+כְּ+אֵ+אֵ+אֵ',         de: 'auf das dreifache Licht (emphatischer Schlusskolophon, Sprache B; Erstbeleg f33r P.7) — ★★★ Kand.', stars: '★★★',  cat: 'kolophon' },
];
