// Verified reference sequences — single source of truth for both HTML and markdown export.
// Entries with `sides` use the two-column antonym-grid layout; others use the single-block layout.
export const REFS = [
  {
    id: 1,
    folio: 'f57r P.9',
    title: 'Die stärkste Ankersequenz',
    color: 'blue',
    eva: 'sar · al · daiindy',
    heb: 'שַׂר עַל דִּין דִּי',
    de: '„Arzt über — das Urteil dessen"',
    note: 'Drei unabhängig bestätigte Wörter + aramäischer Genitiv-Suffix in natürlicher Wortfolge.',
    stars: '★★★★★',
    insert: 'sar al daiindy',
  },
  {
    id: 2,
    folio: 'f103r P.23',
    title: 'Fünf-Wort-Prognose',
    color: 'blue',
    eva: 'daiin · sheckhy · lchedy · chckhy · shol',
    heb: 'שְׁאוֹל · כְּכְּהִי · לְכְּדֵי · שֶׁכְּהִי · דִּין',
    de: '„Das Urteil: [der,] der Blässe zeigt — um [sie] zu behandeln — wie Blässe — Scheol."',
    note: 'Vollständiges hippokratisches Prognose-Schema in fünf Wörtern.',
    stars: '★★★★★',
    insert: 'daiin sheckhy lchedy chckhy shol',
  },
  {
    id: 3,
    folio: 'f103r P.17',
    title: 'Binäre Prognose-Formel',
    color: 'blue',
    eva: '… or · aiin',
    heb: 'אַיִן · אוֹר',
    de: '„Licht — Nichts."',
    note: 'Zeilenende-Formel: binäre Prognose (Heilung oder Ausweg-los), identisch mit hippokratisch-arabischem Prognostikon-Schema.',
    stars: null,
    insert: 'or aiin sheol daiin',
  },
  {
    id: 4,
    folio: 'f6v/f7v',
    title: 'Direktionales Antonymenpaar',
    color: 'green',
    sides: [
      { eva: 'lor', heb: 'לְאוֹר', de: '„zum Licht / zur Heilung"' },
      { eva: 'lshol', heb: 'לְשׁוֹל', de: '„zum Tod / zu Scheol"' },
    ],
    note: 'Identische l-Direktional-Morphologie, entgegengesetzte Semantik. Hauptneufund v5.2.',
    stars: '★★★★★',
    insert: 'lor lshol kaiim',
  },
  {
    id: 5,
    folio: 'f103r P.42',
    title: 'Sterbens-Terminologie',
    color: 'blue',
    eva: 'tshey · sheol · cheolshy · chalal',
    heb: 'חָלָל · [כְּעוֹלְשִׁי] · שְׁאוֹל · תְּשֵׁי',
    de: '„Erschöpfung — Scheol — [wie die Last] — der Sterbende."',
    note: 'Dreifache Prognose: Erschöpfung → Tod → Patient im Sterben. chalal erscheint ausschließlich nach sheol.',
    stars: null,
    insert: 'tshey sheol cheolshy chalal',
  },
  {
    id: 6,
    folio: 'f11r P.6 / f11v P.6',
    title: 'Pupillenheilung & positiver Kolophon',
    color: 'green',
    sides: [
      {
        eva: 'odl · chaiin · ykchor · dair',
        heb: 'דְּ+אִיר · יְ+כְּ+חֹר · חַיִּין · עַ+דַּל',
        de: '„Über die Schwäche — Leben — er heilt die Pupille — der Leuchtende."',
      },
      {
        eva: 'ycheor · dor · schold=',
        heb: 'שׁ+כֹּ+לֵד · דּוֹר · יְ+כְּ+אוֹר',
        de: '„Er wird wie Licht heilen — Generation — [Schlussformel]."',
      },
    ],
    note: 'Erster Beleg von ykchor (er heilt die Pupille — 4. Verb im y+k+[Terminus]-Paradigma) und von ycheor= als positivem Schluss-Kolophon. f11v (Borago-Typ) ist das positivste Prognosefolio in Quire B.',
    stars: '★★★★★',
    insert: 'odl chaiin ykchor dair ycheor',
  },
  {
    id: 7,
    folio: 'f14r P.8 / f14v P.8',
    title: 'y+k-Paradigma & Blut-Triade',
    color: 'green',
    sides: [
      {
        eva: 'ykaiin',
        heb: 'יְ+כְּ+עַיִן',
        de: '„er heilt das Auge" — 5. y+k+Terminus-Verb',
      },
      {
        eva: 'dol · dair · dam',
        heb: 'דֶּוֶה · דְּ+אִיר · דָּם',
        de: '„Schmerz — das Licht davon — Blut"',
      },
    ],
    note: 'ykaiin vervollständigt das y+k+[Terminus]-Paradigma auf fünf klinische Verbformen (Leben, Licht, Pupille, Blässe, Auge). Die Blut-Triade dol·dair·dam (f14v P.8) ist der erste dam-Beleg in Quire B und verbindet f14v mit f3r (Blutpflanze).',
    stars: '★★★★★',
    insert: 'ykaiin dol dair dam',
  },
  {
    id: 8,
    folio: 'f15r / f15v',
    title: 'Bifolio bB2 Abschluss',
    color: 'green',
    sides: [
      {
        eva: 'qotchor · chaiin · chy · kol · daky=',
        heb: 'קוֹ+תְּ+כֹּר · חַיִּין · כְּהִי · כֹּל · דַּכִּי=',
        de: 'f15r Kolophon: „Zeichen der Pupille — Leben — Blässe — alles — Reinheit" (positiv-ambivalent)',
      },
      {
        eva: 'daiin · cthor · chol · chor=',
        heb: 'דִּין · כְּ+תֹּר · כֹּל · כֹּר=',
        de: 'f15v Kolophon: „Urteil — vollständige Heilung — alles — Pupille" (positiv)',
      },
    ],
    note: 'soloiin (f15v P.11) = „Arznei für das Auge" — therapeutisch präzisestes Kompositum im Gesamtkorpus. ykshol (f15r P.12) = erster negativer y+k+Terminus — Paradigma mit 6 Gliedern + Kandidat ykair. Bifolio bB2 (f10r/f10v/f15r/f15v) schließt konsistentes ophthalmologisches Programm ab.',
    stars: '★★★★★',
    insert: 'soloiin sor cthor chor',
  },
  {
    id: 9,
    folio: 'f16r / f16v',
    title: 'Bifolio bB1 · Quire-B-Abschluss',
    color: 'green',
    sides: [
      {
        eva: 'saiin · ytaiin=',
        heb: 'יְ+תָּ+עַיִן · שַׂעַיִן',
        de: 'f16r Mini-Kolophon: „Augenarzt — er wird das Auge heilen" (positiv)',
      },
      {
        eva: 'sokar · oaorar=',
        heb: 'שׂ+אוֹ+כְּ+אָר · עַ+אַ+אוֹר+אָר',
        de: 'f16v Quire-Kolophon: „Heilungs-Arzt des Lichts — auf das Licht der Heilung" (positiv)',
      },
    ],
    note: 'tchor (תְּ+חֹר) — fem. Pupillen-Heilungsverb, zwei Belege in bB1 bestätigt ★★★★. chkar·chkar (f16v P.6) — erste Doppel-Untersuchungsformel im Corpus. Bifolio bB1 (f9r/f9v/f16r/f16v) vollständig — Quire B abgeschlossen; erster rein positiver Quire-Abschluss im analysierten Corpus.',
    stars: '★★★★★',
    insert: 'saiin ytaiin sokar oaorar',
  },
  {
    id: 10,
    folio: 'f18r / f18v',
    title: 'Bifolio bC2 · Quire C',
    color: 'green',
    sides: [
      {
        eva: 'or · shaiin · cthor · cthal · okal · dar=',
        heb: 'אוֹר · שַׁ+עַיִן · כְּ+תֹּר · כְּ+תַּ+חַל · עַ+כָּל · דַּר=',
        de: 'f18r Schlusskolophon P.13: „Licht des Auges — vollständige Heilung — wie vollständig — über alles — leuchtend." (stark positiv ★★★★★)',
      },
      {
        eva: 'yko · dshy · dair · ykol · dom=',
        heb: 'יְ+כוֹ · דְּ+שֵׁי · דְּ+אִיר · יְ+כֹּל · דּוֹם=',
        de: 'f18v Schlusskolophon P.10: „Er wird sich erholen — von der Gabe — der Leuchtende — er heilt alles — Stille/Ende." (positiv-neutral, R39-Erstbeleg dom= in Spr. A)',
      },
    ],
    note: 'f18r: Centaurea montana — stärkstes Schlusskolophon in Quire C; dar·dar (R36-Erstbeleg), doldaiin (Krankheits-Urteil, Corpus-Erstbeleg). f18v: Dracunculus vulgaris — erste zoomorphe Begleitfigur im botanischen Corpus; ykam/ytor Auferstehungsverben; qokchy·qokchy R37-Erstbeleg.',
    stars: '★★★★',
    insert: 'or shaiin cthor okal dar doldaiin ykam ytor dom',
  },
];
