// EVA → Hebrew character mapping
export const MAPPING = [
  { eva: 'a',    heb: 'אַ',    name: 'Alef / Patach' },
  { eva: 'b',    heb: 'בּ',    name: 'Bet' },
  { eva: 'c',    heb: 'כּ',    name: 'Kaf (stark)' },
  { eva: 'ch',   heb: 'כ/ח',  name: 'Kaf / Ḥet' },
  { eva: 'd',    heb: 'ד',    name: 'Dalet' },
  { eva: 'e',    heb: 'ֶ',    name: 'Vokal: Segol' },
  { eva: 'ee',   heb: 'ֵ',    name: 'Vokal: Ṣere' },
  { eva: 'f',    heb: 'פ/ף',  name: 'Pe (schwach)' },
  { eva: 'g',    heb: 'ג',    name: 'Gimel' },
  { eva: 'h',    heb: 'ה',    name: 'He' },
  { eva: 'i',    heb: 'י',    name: 'Yod / Ḥiriq' },
  { eva: 'ii',   heb: 'יִ',   name: 'Yod + Ḥiriq' },
  { eva: 'k',    heb: 'כ',    name: 'Kaf (weich)' },
  { eva: 'l',    heb: 'ל',    name: 'Lamed' },
  { eva: 'm',    heb: 'מ',    name: 'Mem' },
  { eva: 'n',    heb: 'נ',    name: 'Nun' },
  { eva: 'o',    heb: 'ע/ֹ',  name: 'Ayin / Ḥolam' },
  { eva: 'oo',   heb: 'וֹ',   name: 'Vav Ḥolam' },
  { eva: 'p',    heb: 'פּ',   name: 'Pe (stark)' },
  { eva: 'q',    heb: 'ק',    name: 'Qof' },
  { eva: 'r',    heb: 'ר',    name: 'Reš' },
  { eva: 's',    heb: 'שׂ/ס', name: 'Sin / Samech' },
  { eva: 'sh',   heb: 'שׁ',   name: 'Šin' },
  { eva: 't',    heb: 'ת/ט',  name: 'Tav / Ṭet' },
  { eva: 'y',    heb: 'יְ/וֹ', name: 'Yod-Vav / Verb-Präfix' },
  { eva: 'aiin', heb: 'עַיִן', name: 'Auge-Suffix' },
  { eva: 'ai',   heb: 'ַי',   name: 'Patach + Yod' },
];

// Morphological prefix table (sorted longest-first for greedy matching)
export const PREFIXES = [
  { eva: 'qok', heb: 'וְכְּ', de: 'und wie' },
  { eva: 'qod', heb: 'וְדְּ', de: 'und von' },
  { eva: 'qo',  heb: 'וְ',   de: 'und/auch' },
  { eva: 'o',   heb: 'עַ',   de: 'auf/bei' },
  { eva: 'l',   heb: 'לְ',   de: 'zu/für' },
  { eva: 'd',   heb: 'דְּ',  de: 'von/aus' },
  { eva: 'p',   heb: 'פְּ',  de: 'Pe-Präfix' },
  { eva: 'y',   heb: 'יְ',   de: 'Imperfekt 3.Sg.m.' },
  { eva: 't',   heb: 'תָּ',  de: 'Imperfekt 3.Sg.f./2.Sg.' },
];

// Confirmed lexicon v5.3 — 98 entries ★★★+
export const LEXICON = [
  // ── Medizinische Nomina & Symptome ──────────────────
  { eva: 'dam',       heb: 'דָּם',         de: 'Blut',                             stars: '★★★★★', cat: 'symptom' },
  { eva: 'dal',       heb: 'דַּל',         de: 'schwach / abgemagert',             stars: '★★★★',  cat: 'symptom' },
  { eva: 'daly',      heb: 'דַּלִּי',      de: 'seine/meine Schwäche (Possessiv)', stars: '★★★★',  cat: 'symptom' },
  { eva: 'ckhy',      heb: 'כְּהִי',       de: 'Blässe / Trübheit',                stars: '★★★★',  cat: 'symptom' },
  { eva: 'okaiin',    heb: 'עַכְּעַיִן',   de: 'auf das Auge',                     stars: '★★★★',  cat: 'symptom' },
  { eva: 'qokaiin',   heb: 'וְכְּעַיִן',   de: 'und gemäß dem Auge',               stars: '★★★★',  cat: 'symptom' },
  { eva: 'qotal',     heb: 'וְטַל',        de: 'Tau / Schweißzeichen',             stars: '★★★',   cat: 'symptom' },
  { eva: 'ram',       heb: 'רָם',          de: 'erhöht / Fieber',                  stars: '★★★',   cat: 'symptom' },
  { eva: 'chor',      heb: 'חֹר',          de: 'Pupille / Höhle',                  stars: '★★★★',  cat: 'symptom' },
  { eva: 'otchor',    heb: 'אוֹת+חֹר',     de: 'das Zeichen der Pupille',          stars: '★★★★',  cat: 'symptom' },
  { eva: 'oraiin',    heb: 'אוֹר+עַיִן',   de: 'Licht des Auges / Augenheilung',   stars: '★★★★',  cat: 'symptom' },
  { eva: 'sheoldam',  heb: 'שְׁאוֹל+דָּם', de: 'tödlicher Blutverlust',            stars: '★★★★★', cat: 'symptom' },
  { eva: 'damo',      heb: 'דָּמוֹ',       de: 'sein Blut (Possessiv)',            stars: '★★★★',  cat: 'symptom' },
  { eva: 'cham',      heb: 'חַם',          de: 'Wärme / Entzündung',               stars: '★★★',   cat: 'symptom' },
  { eva: 'dalor',     heb: 'דַּלאוֹר',     de: 'schwaches Augenlicht',             stars: '★★★',   cat: 'symptom' },
  { eva: 'char',      heb: 'חַר',          de: 'heiß / Fieber',                    stars: '★★★★',  cat: 'symptom' },
  { eva: 'chary',     heb: 'חַרִי',        de: 'sein Fieber (Possessiv)',           stars: '★★★',   cat: 'symptom' },
  { eva: 'ckhal',     heb: 'כְּהַל',       de: 'Nachlassen des Fiebers',            stars: '★★★',   cat: 'symptom' },
  { eva: 'dol',       heb: 'דָּוֶה',       de: 'Schmerz / Krankheit',              stars: '★★★',   cat: 'symptom' },
  { eva: 'odol',      heb: 'עַ+דָּוֶה',    de: 'auf die Krankheit (o+dol)',         stars: '★★★★',  cat: 'symptom' },
  { eva: 'dolar',     heb: 'דָּוֶה+לְאוֹר', de: 'Krankheit zur Heilung',            stars: '★★★',   cat: 'symptom' },
  { eva: 'shees',     heb: 'אֵשׁ',         de: 'Feuer / Fieberbrand',              stars: '★★★',   cat: 'symptom' },
  // ── Prognose-Termini ────────────────────────────────
  { eva: 'or',        heb: 'אוֹר',         de: 'Licht / Heilung',                  stars: '★★★★',  cat: 'prognose' },
  { eva: 'sheol',     heb: 'שְׁאוֹל',      de: 'Scheol / Tod',                     stars: '★★★★',  cat: 'prognose' },
  { eva: 'shol',      heb: 'שׁוֹל',        de: 'Tod (apokor. Spr. A)',              stars: '★★★★★', cat: 'prognose' },
  { eva: 'daiin',     heb: 'דִּין',        de: 'Urteil / Prognose',                stars: '★★★★',  cat: 'prognose' },
  { eva: 'chalal',    heb: 'חָלָל',        de: 'Sterbender',                       stars: '★★★★',  cat: 'prognose' },
  { eva: 'chodl',     heb: 'חֹדֵל',        de: 'der Aufhörende / der Sterbende',   stars: '★★★',   cat: 'prognose' },
  { eva: 'dair',      heb: 'דְּ+אִיר',     de: 'der Leuchtende / Licht davon',     stars: '★★★',   cat: 'prognose' },
  { eva: 'aiin',      heb: 'אַיִן',        de: 'nichts / nicht vorhanden',         stars: '★★★',   cat: 'prognose' },
  { eva: 'eeor',      heb: 'אֵאוֹר',       de: 'kein Licht',                       stars: '★★★',   cat: 'prognose' },
  { eva: 'lor',       heb: 'לְאוֹר',       de: 'zum Licht / zur Heilung',          stars: '★★★★★', cat: 'prognose' },
  { eva: 'lshol',     heb: 'לְשׁוֹל',      de: 'zum Tod / zu Scheol',              stars: '★★★★★', cat: 'prognose' },
  { eva: 'chaiin',    heb: 'חַיִּין',      de: 'Leben (Chayyim)',                  stars: '★★★★',  cat: 'prognose' },
  { eva: 'sheey',     heb: 'שֵׁי',         de: 'Gabe / Wohlbefinden',              stars: '★★★★',  cat: 'prognose' },
  { eva: 'cheor',     heb: 'כְּאוֹר',      de: 'wie Licht (Heilungszeichen)',      stars: '★★★★',  cat: 'prognose' },
  { eva: 'otshol',    heb: 'אוֹתשׁוֹל',    de: 'das Zeichen des Todes',            stars: '★★★★★', cat: 'prognose' },
  { eva: 'chan',      heb: 'חָן',          de: 'Gnade / günstige Prognose',        stars: '★★★★',  cat: 'prognose' },
  { eva: 'dom',       heb: 'דּוֹם',        de: 'Stille / Ende',                    stars: '★★★★',  cat: 'prognose' },
  { eva: 'dsholdy',   heb: 'דְּ+שׁוֹל+דִּי', de: 'von Scheol — dessen (Genitiv)',   stars: '★★★★★', cat: 'prognose' },
  { eva: 'dsho',      heb: 'דְּ+שׁוֹ',     de: 'von Scheol (Kurzform)',             stars: '★★★★',  cat: 'prognose' },
  { eva: 'shoiin',    heb: 'שׁוֹ+עַיִן',   de: 'Scheol des Auges',                 stars: '★★★★',  cat: 'prognose' },
  { eva: 'darchor',   heb: 'דַּרְכּוֹר',   de: 'sein Krankheitsverlauf',           stars: '★★★',   cat: 'prognose' },
  { eva: 'otan',      heb: 'עֹתָן',        de: 'Zeit / Jahreszeit der Erkrankung', stars: '★★★',   cat: 'prognose' },
  { eva: 'kaiim',     heb: 'קַיָּם',       de: 'gültig / beständig (Schlussformel)', stars: '★★★★★', cat: 'kolophon' },
  { eva: 'cphar',     heb: 'כְּ+פַּר',     de: 'Sühne / Bedeckung (Kolophon-Formel)', stars: '★★★', cat: 'kolophon' },
  // ── Syntaktische Konnektoren ────────────────────────
  { eva: 'chedy',     heb: 'כְּדֵי',       de: 'damit / um zu',                    stars: '★★★★',  cat: 'syntax' },
  { eva: 'kedy',      heb: 'כְּדֵי',       de: 'damit / um zu',                    stars: '★★★★',  cat: 'syntax' },
  { eva: 'shedy',     heb: 'שֶׁדִּי',      de: 'das/welches von',                  stars: '★★★★',  cat: 'syntax' },
  { eva: 'shdy',      heb: 'שֶׁדִּי',      de: 'das/welches von (Kurz)',           stars: '★★★★',  cat: 'syntax' },
  { eva: 'dy',        heb: 'דִּי',         de: 'von / dessen (Aram.)',             stars: '★★★★',  cat: 'syntax' },
  { eva: 'lchedy',    heb: 'לְכְּדֵי',     de: 'um zu / bis zur Grenze',           stars: '★★★★',  cat: 'syntax' },
  { eva: 'chal',      heb: 'חָל',          de: 'gilt für / betrifft',              stars: '★★★',   cat: 'syntax' },
  { eva: 'shodaiin',  heb: 'שׁוֹדִּין',    de: 'Todesurteil',                      stars: '★★★★',  cat: 'syntax' },
  { eva: 'sheodaiin', heb: 'שְׁאוֹדִּין',  de: 'Todesurteil (Vollform)',           stars: '★★★★★', cat: 'syntax' },
  { eva: 'daiidy',    heb: 'דִּין+דִּי',   de: 'das Urteil dessen',                stars: '★★★★★', cat: 'syntax' },
  { eva: 'daiindy',   heb: 'דִּין+דִּי',   de: 'das Urteil dessen',                stars: '★★★★★', cat: 'syntax' },
  { eva: 'qodaiin',   heb: 'וְדִּין',      de: 'und Urteil',                       stars: '★★★★',  cat: 'syntax' },
  { eva: 'daiim',     heb: 'דִּין+ם',      de: 'Urteile (Plural)',                 stars: '★★★',   cat: 'syntax' },
  { eva: 'keey',      heb: 'כֵּי',         de: 'denn / weil (Kausalpartikel)',     stars: '★★★★',  cat: 'syntax' },
  { eva: 'cthom',     heb: 'כְּ+תֹם',      de: 'wie Vollständigkeit (Kolophon)',   stars: '★★★',   cat: 'kolophon' },
  // ── Verbformen ──────────────────────────────────────
  { eva: 'taiir',     heb: 'תָּאִיר',      de: 'es wird leuchten / heilen',        stars: '★★★★',  cat: 'verb' },
  { eva: 'yteechy',   heb: 'יִחְיֶה',      de: 'er wird gesund',                   stars: '★★★',   cat: 'verb' },
  { eva: 'yshdal',    heb: 'יְשַׁדַּל',    de: 'er wird schwächen',                stars: '★★★',   cat: 'verb' },
  { eva: 'ykeedy',    heb: 'יְכֵּדֵי',     de: 'er wird anordnen',                 stars: '★★★',   cat: 'verb' },
  { eva: 'ykchy',     heb: 'יְ+כְּ+הִי',   de: 'er wird Blässe zeigen',            stars: '★★★★',  cat: 'verb' },
  { eva: 'tsheoarom', heb: 'תְּשְׁאוֹרוֹם', de: 'du wirst von Scheol aufsteigen', stars: '★★★★',  cat: 'verb' },
  { eva: 'chkar',     heb: 'חֲקַר',        de: 'er untersucht',                    stars: '★★★',   cat: 'verb' },
  { eva: 'ydaiin',    heb: 'יְדִּין',      de: 'er urteilt',                       stars: '★★★★',  cat: 'verb' },
  { eva: 'ysho',      heb: 'יְשׁוֹ',       de: 'es führt zum Tod',                 stars: '★★★★',  cat: 'verb' },
  { eva: 'ykeor',     heb: 'יְכְּאוֹר',    de: 'er heilt / wie Licht',             stars: '★★★★',  cat: 'verb' },
  { eva: 'ykchaiin',  heb: 'יְ+כְּ+חַיִּין', de: 'er wird wie Leben werden',      stars: '★★★★',  cat: 'verb' },
  { eva: 'ykchor',    heb: 'יְ+כְּ+חֹר',   de: 'er heilt die Pupille',             stars: '★★★★★', cat: 'verb' },
  { eva: 'ycheor',    heb: 'יְ+כְּ+אוֹר',  de: 'er wird wie Licht werden',         stars: '★★★★',  cat: 'verb' },
  { eva: 'tchey',     heb: 'תְּחִי',       de: 'möge es/sie leben! (Jussiv)',      stars: '★★★★',  cat: 'verb' },
  { eva: 'ychor',     heb: 'יְ+חֹר',      de: 'er wird die Pupille weiten',        stars: '★★★★',  cat: 'verb' },
  { eva: 'yodaiin',   heb: 'יוֹדִּין',     de: 'er weiß das Urteil',               stars: '★★★★',  cat: 'verb' },
  { eva: 'ytchody',   heb: 'יְ+תְּ+כֹּ+דִּי', de: 'er wird urteilen (Doppelpräfix)', stars: '★★★',   cat: 'verb' },
  { eva: 'ykoiin',    heb: 'יְכוֹיִן',     de: 'er wird sich erholen',             stars: '★★★',   cat: 'verb' },
  // ── Akteure, Anatomie & Botanik ─────────────────────
  { eva: 'sar',       heb: 'שַׂר',         de: 'Arzt / Meister / Vorsteher',       stars: '★★★★',  cat: 'akteur' },
  { eva: 'sary',      heb: 'שַׂרִי',       de: 'mein Arzt (Possessiv)',             stars: '★★★',   cat: 'akteur' },
  { eva: 'pchy',      heb: 'פְּחִי',       de: 'mein Atem / mein Mund',             stars: '★★',    cat: 'akteur' },
  { eva: 'al',        heb: 'עַל',          de: 'auf / über / betreffend',          stars: '★★★★',  cat: 'akteur' },
  { eva: 'ol',        heb: 'עַל',          de: 'auf / über / betreffend',          stars: '★★★★',  cat: 'akteur' },
  { eva: 'saiin',     heb: 'שַׂעַיִן',     de: 'Augenarzt',                        stars: '★★★★',  cat: 'akteur' },
  { eva: 'dain',      heb: 'דַּ+עַיִן',    de: 'das Auge (Kurzform)',              stars: '★★★',   cat: 'akteur' },
  { eva: 'sam',       heb: 'שַׂם',         de: 'Arznei / er gibt',                 stars: '★★★',   cat: 'akteur' },
  { eva: 'shty',      heb: 'שְׁתִי',       de: 'Getränk / Trank',                  stars: '★★★',   cat: 'akteur' },
  { eva: 'pol',       heb: 'פֹּל',         de: 'Bohne / Beere',                    stars: '★★★',   cat: 'akteur' },
  { eva: 'otoaiin',   heb: 'עַתוֹעַיִן',   de: 'auf seine Augen',                  stars: '★★★',   cat: 'akteur' },
  { eva: 'chokeos',   heb: 'כֹּכֵּאוֹס',   de: 'wie ein Kelch (Botanik)',          stars: '★★★',   cat: 'akteur' },
  // ── Bestätigte Komposita ────────────────────────────
  { eva: 'qokedam',   heb: 'וְ+כְּ+דָּם',  de: 'und wie das Blut',                 stars: '★★★★',  cat: 'kompositum' },
  { eva: 'okoldm',    heb: 'עַל+כֹּל+דָּם', de: 'über alles Blut',                 stars: '★★★★',  cat: 'kompositum' },
  { eva: 'pchedal',   heb: 'פְּ+כֶּ+דַּל', de: 'bei dem Schwachen',                stars: '★★★',   cat: 'kompositum' },
  { eva: 'cholar',    heb: 'כֹּ+לוֹ+ר',    de: 'alles sein Licht',                  stars: '★★★',   cat: 'kompositum' },
  { eva: 'qokchor',   heb: 'וְ+עַ+כְּ+חֹר', de: 'und für die Pupille',              stars: '★★★★★', cat: 'kompositum' },
  { eva: 'shydal',    heb: 'שֵׁי+דַּל',    de: 'die Gabe der Schwäche',             stars: '★★★',   cat: 'kompositum' },
  // ── Possessiv-Formen ────────────────────────────────
  { eva: 'olsho',     heb: 'שׁוֹ+לוֹ',     de: 'sein Scheol (Possessiv)',           stars: '★★★',   cat: 'possessiv' },
];

// Folio pages — grouped by quire
export const FOLIO_PAGES = [
  { q: 'q01', label: 'Lage 1 — Kräuter A · f1–f8',         pages: ['f1r','f1v','f2r','f2v','f3r','f3v','f4r','f4v','f5r','f5v','f6r','f6v','f7r','f7v','f8r','f8v'] },
  { q: 'q02', label: 'Lage 2 — Kräuter A · f9–f16',        pages: ['f9r','f9v','f10r','f10v','f11r','f11v','f13r','f13v','f14r','f14v','f15r','f15v','f16r','f16v'] },
  { q: 'q03', label: 'Lage 3 — Kräuter A · f17–f24',       pages: ['f17r','f17v','f18r','f18v','f19r','f19v','f20r','f20v','f21r','f21v','f22r','f22v','f23r','f23v','f24r','f24v'] },
  { q: 'q04', label: 'Lage 4 — Kräuter A · f25–f32',       pages: ['f25r','f25v','f26r','f26v','f27r','f27v','f28r','f28v','f29r','f29v','f30r','f30v','f31r','f31v','f32r','f32v'] },
  { q: 'q05', label: 'Lage 5 — Kräuter A/B · f33–f40',     pages: ['f33r','f33v','f34r','f34v','f35r','f35v','f36r','f36v','f37r','f37v','f38r','f38v','f39r','f39v','f40r','f40v'] },
  { q: 'q06', label: 'Lage 6 — Kräuter B · f41–f48',       pages: ['f41r','f41v','f42r','f42v','f43r','f43v','f44r','f44v','f45r','f45v','f46r','f46v','f47r','f47v','f48r','f48v'] },
  { q: 'q07', label: 'Lage 7 — Kräuter B · f49–f56',       pages: ['f49r','f49v','f50r','f50v','f51r','f51v','f52r','f52v','f53r','f53v','f54r','f54v','f55r','f55v','f56r','f56v'] },
  { q: 'q08', label: 'Lage 8 — Astronomisch · f57–f66',    pages: ['f57r','f57v','f58r','f58v','f65r','f65v','f66r','f66v'] },
  { q: 'q09', label: 'Lage 9 — Zodiak · f67–f68',          pages: ['f67r1','f67r2','f67v2','f67v1','f68r1','f68r2','f68r3','f68v3','f68v2','f68v1'] },
  { q: 'q10', label: 'Lage 10 — Biologisch · f69–f70',     pages: ['f69r','f69v','f70r1','f70r2','f70v2','f70v1'] },
  { q: 'q11', label: 'Lage 11 — Biologisch · f71–f72',     pages: ['f71r','f71v','f72r1','f72r2','f72r3','f72v3','f72v2','f72v1'] },
  { q: 'q12', label: 'Lage 12 — Biologisch · f73',         pages: ['f73r','f73v'] },
  { q: 'q13', label: 'Lage 13 — Biologisch · f75–f84',     pages: ['f75r','f75v','f76r','f76v','f77r','f77v','f78r','f78v','f79r','f79v','f80r','f80v','f81r','f81v','f82r','f82v','f83r','f83v','f84r','f84v'] },
  { q: 'q14', label: 'Lage 14 — Kosmologisch · f85–f86',   pages: ['f85r1','f85r2','fRos','f86v4','f86v6','f86v5','f86v3'] },
  { q: 'q15', label: 'Lage 15 — Pharmazeutisch · f87–f90', pages: ['f87r','f87v','f88r','f88v','f89r1','f89r2','f89v2','f89v1','f90r1','f90r2','f90v2','f90v1'] },
  { q: 'q16', label: 'Lage 16 — Pharmazeutisch · f91–f92', pages: ['f91r','f91v','f92r','f92v'] },
  { q: 'q17', label: 'Lage 17 — Pharmazeutisch · f93–f96', pages: ['f93r','f93v','f94r','f94v','f95r1','f95r2','f95v2','f95v1','f96r','f96v'] },
  { q: 'q18', label: 'Lage 18 — Pharmazeutisch · f97–f98', pages: ['f97r','f97v','f98r','f98v'] },
  { q: 'q19', label: 'Lage 19 — Pharmazeutisch · f99–f102', pages: ['f99r','f99v','f100r','f100v','f101r','f101v2','f101v1','f102r1','f102r2','f102v2','f102v1'] },
  { q: 'q20', label: 'Lage 20 — Rezepte/Sterne · f103–f116', pages: ['f103r','f103v','f104r','f104v','f105r','f105v','f106r','f106v','f107r','f107v','f108r','f108v','f111r','f111v','f112r','f112v','f113r','f113v','f114r','f114v','f115r','f115v','f116r','f116v'] },
];
